image: l3iggs/archlinux-aur
Build:
  script:
  - export BINDIR=$(mktemp -d)
  - curl -o ${BINDIR}/pacman2 http://mortzu.andromeda.hostedinspace.de/ci-runner/pacman2
  - chmod +x ${BINDIR}/pacman2
  - export PATH=$BINDIR:$PATH
  - export TERM='linux'
  - export PACMAN='pacman2'
  - yaourt -Syu --noconfirm
  - makepkg --cleanbuild --clean --force --syncdeps --rmdeps --noconfirm --asdeps
  tags: 
  except:
  - tags
