assets_dir = "/usr/share/ludo/assets"
cores_dir = "/usr/lib/libretro"
database_dir = "/usr/share/ludo/database"

[core_for_playlist]
  "Atari - 2600" = "stella_libretro"
  "Atari - 5200" = "atari800_libretro"
  "Atari - 7800" = "prosystem_libretro"
  "Atari - Jaguar" = "virtualjaguar_libretro"
  "Atari - Lynx" = "handy_libretro"
  "Atari - ST" = "hatari_libretro"
  "Bandai - WonderSwan" = "mednafen_wswan_libretro"
  "Bandai - WonderSwan Color" = "mednafen_wswan_libretro"
  "Cave Story" = "nxengine_libretro"
  ChaiLove = "chailove_libretro"
  "Coleco - ColecoVision" = "bluemsx_libretro"
  "FBNeo - Arcade Games" = "fbneo_libretro"
  "GCE - Vectrex" = "vecx_libretro"
  "Magnavox - Odyssey2" = "o2em_libretro"
  "Microsoft - MSX" = "bluemsx_libretro"
  "Microsoft - MSX2" = "bluemsx_libretro"
  "NEC - PC Engine - TurboGrafx 16" = "mednafen_pce_fast_libretro"
  "NEC - PC Engine SuperGrafx" = "mednafen_supergrafx_libretro"
  "Nintendo - Family Computer Disk System" = "nestopia_libretro"
  "Nintendo - Game Boy" = "gambatte_libretro"
  "Nintendo - Game Boy Advance" = "mgba_libretro"
  "Nintendo - Game Boy Color" = "gambatte_libretro"
  "Nintendo - Nintendo Entertainment System" = "nestopia_libretro"
  "Nintendo - Pokemon Mini" = "pokemini_libretro"
  "Nintendo - Super Nintendo Entertainment System" = "snes9x_libretro"
  "Nintendo - Virtual Boy" = "mednafen_vb_libretro"
  "SNK - Neo Geo Pocket" = "mednafen_ngp_libretro"
  "SNK - Neo Geo Pocket Color" = "mednafen_ngp_libretro"
  "Sega - 32X" = "picodrive_libretro"
  "Sega - Game Gear" = "genesis_plus_gx_libretro"
  "Sega - Master System - Mark III" = "genesis_plus_gx_libretro"
  "Sega - Mega Drive - Genesis" = "genesis_plus_gx_libretro"
  "Sega - PICO" = "picodrive_libretro"
  "Sega - SG-1000" = "genesis_plus_gx_libretro"
  "Sega - Saturn" = "yabause_libretro"
  "Sony - PlayStation" = "mednafen_psx_libretro"
