# Generated by mksrcinfo v8
# Thu Apr 13 20:19:37 UTC 2017
pkgbase = asp
	pkgdesc = Arch Linux build source file management
	pkgver = 1
	pkgrel = 2
	url = https://github.com/falconindy/asp
	arch = any
	license = MIT
	makedepends = asciidoc
	depends = awk
	depends = bash
	depends = jq
	source = asp-1.tar.gz::https://github.com/falconindy/asp/archive/v1.tar.gz
	sha512sums = e984a319222f48cb799c79adb19c458bd4628cbf4a4963b1556b14ce84e65a4831cdeadec1eda9c8adada53dab07ec4dd2328f8fe08958ba785b91b6bf356536

pkgname = asp

