# Generated by mksrcinfo v8
# Wed Mar 30 15:12:28 UTC 2016
pkgbase = pan
	pkgdesc = A powerful Newsgroup Article reader
	pkgver = 0.140
	pkgrel = 1
	url = http://pan.rebelbase.com/
	arch = i686
	arch = x86_64
	license = GPL2
	makedepends = gnome-common
	makedepends = intltool
	depends = gtk2
	depends = gmime
	depends = gtkspell
	depends = gnutls
	conflicts = pan-git
	options = !makeflags
	source = http://pan.rebelbase.com/download/releases/0.140/source/pan-0.140.tar.bz2
	sha256sums = ba1c65ee75b9eca1f15f6249ea762492309731446edc8b09085b63ad34351c71

pkgname = pan

