pipeline:
  build:
    image: archlinux/makepkg
    pull: true
    makepkg_flags: "--skippgpcheck"
    volumes:
      - /etc/makepkg.conf:/etc/makepkg.conf
      - /etc/pacman.d/gnupg/gpg.conf:/etc/pacman.d/gnupg/gpg.conf

  repoadd:
    image: archlinux/repoadd
    pull: true
    when:
      branch: master
    override_files: "linux-ath-dfs*.zst"
    repo_name: archrepo
    repo_ownerid: 972
    repo_groupid: 971
    volumes:
      - /home/woodpecker/archrepo/:/repo/
