image: archlinux
packages:
    - base-devel
    - xbitmaps
    - rpcbind
    - ksh
    - ncurses
    - libxss
    - libxinerama
    - libutempter
    - rpcsvc-proto
    - xorg-mkfontdir
    - xorg-bdftopcf
    - xorg-xrdb
    - libxpm
    - libxaw
    - tcl
    - ncompress
    - bison
#sources:
#- git+https://git.code.sf.net/p/cdesktopenv/code
tasks:
  - precheck: |
      cd cdesktopenv-git
      namcap PKGBUILD
  - build: |
      cd cdesktopenv-git
      time makepkg
  - show: |
      cd cdesktopenv-git
      ls
      tar taf cdesktopenv-git-*.pkg.tar*
  - postcheck: |
      cd cdesktopenv-git
      namcap cdesktopenv-git-*.pkg.tar*
