concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - xdelta
        - qt5-matrixclient-git
        - vapoursynth-plugin-noisegen-hg
        - mingw-w64-cmake
        - tamanoir-svn
        - libglvnd12
        - cemu-git
        - ros-lunar-tf2
        - oguri-git
        - lighttpd2-git
        - noto-fonts-emoji-git
        - kyma
        - electron-cash-slp
        - yarock
        - eiciel-git
        - ros-jade-mk
        - baka-mplayer
        - input-redirection-client-qt
        - mcabber-hg
        - denemo
        - zathura-pdf-poppler-git
        - xdgurl
        - ow-libbz2
        - urdfdom
        - rigetti-qvm-git
        - pcalc
        - sketchsynth
        - libcintelhex-git
        - mingw-w64-kwidgetsaddons
        - ros-melodic-rqt-srv
        - ros-lunar-rqt-rviz
        - scim-uim
        - l1_logreg
        - metronome
        - httping
        - hyperstart
        - radium_compressor
        - gsettings-qt-bzr
        - tap-plugins-lv2-git
        - liri-screencast-git
        - libmatemixer-dev
        - vrpn-git
        - aria2fe
        - picom-animations-git
        - 4chan-downloader
        - crunch-unv-git
        - lib32-libdc1394
        - rq-git
        - php-xattr
        - lib32-libbonobo
        - pinball-unofficial
        - low-memory-monitor-git
        - darkplaces-xonotic
        - beagle-lib-git
        - kontrast-git
        - openblas-lapack-git
        - rose-browser-git
        - ros-noetic-geometric-shapes
        - libkqueue
        - notepadqq-git
        - giara
        - waynergy-git
        - mate-user-share-gtk2
        - libretro-pcsx2-launcher
        - ros-kinetic-hector-gazebo-plugins
        - zestginx
        - libucl
        - bitcoin-git
        - libgnomecups
        - qt5-xmlpatterns-git
        - lightpad
        - lxqt-common-git
        - downgrader
        - pure-sql3
        - maui-booth-git
        - ros-kinetic-ecl-threads
        - vdr-lcdproc
        - android-aarch64-libjpeg-turbo
        - dmenu-pango-imlib
        - grconv-git
        - od-datastructuregenerator-ref-git
        - revda-git
        - tpm2-tss-engine-git
        - dune-logging
        - orocos-kdl-python2
        - xdg-desktop-portal-gnome-git
        - mplayer2
        - uthenticode-git
        - gr-hrpt-git
        - tsc
        - package-query-git
        - tiny-dnn-git
        - abiword-minimal
        - wayfire-plugins-extra-git
        - libcm
        - wxlauncher-git
        - snowman
        - git-warp-time-git
        - finalcut
        - amd-adl-sdk
        - spotify-tray-git
        - libparsifal
        - purrdata-lv2plugin-git
        - vobcopy
        - telegram-cli-git
        - blugon
        - msp430-elf-libstdc++
        - intarna-git
        - libqhy
        - xorg-server-multimonitor-vrr-git
        - tofi
        - surface-evolver
        - ros-lunar-map-msgs
        - easystroke-git
        - libnfc-nci-lpcusbsio
        - ros-noetic-dynamic-reconfigure
        - arm-none-eabi-yiolibc
        - linuxsampler-svn
        - mingw-w64-capstone
        - libzrtpcpp
        - glib2-sched-policy
        - cereal
        - gluqlo-git
        - ttf-ezhuthu
        - ffmpeg-full-nodecklink
        - jbig2enc
        - mlvwm
        - obs-scene-tree-view-git
        - unbound-git
        - nodm
        - spx2wav
        - netcdf-cxx-legacy
        - fso-unbootimg
        - ly-git-openrc
        - gmpmee-git
        - wmckgmail
        - f38-backgrounds
        - hpx-git
        - dssi-vst
        - ifcplusplus-git
        - soapyremote-git
        - cheese-csd-headerbar
        - libast
        - libvterm-0.1
        - kdelibs4support-git
        - screenshotgun-git
        - gnome-maps-git
        - mono-emby
        - allegro-git
        - wingpanel-indicator-nightlight
        - gyroflow-git
        - ros-melodic-octomap-ros
        - libfirefly-git
        - audio-recorder
        - mbm-gps-control-git
        - ryzenctrl-git
        - gnome-shell-extension-smart-auto-move
        - libodb-sqlite
        - ros-indigo-slam-gmapping
        - salome-hexablock
        - hqp
        - weborf
        - polkit-qt6-git
        - nougat-git
        - arptables
        - plustache
        - hnsd-git
        - libsigsegv-git
        - ttydisp-git
        - signon-kwallet-extension-git
        - isight-firmware-tools
        - lib32-qjson
        - optionmatrix
        - jd
        - soundconverter-py3k-git
        - rippled
        - dippi
        - sope
        - php7-homegear
        - pftools
        - spearmint-git
        - wireguard-hardened
        - ros-indigo-ecl-filesystem
        - llvm-tce
        - slit
        - bbswitch-think
        - apertium-en-ca
        - freemajor
        - ttysterm
        - ruler-git
        - ros-melodic-self-test
        - tiscamera
        - ponysay-rust-git
        - kdm-plugin-pam-face-authentication
        - sleep-until
        - cpufreqd
        - avahi-gtk2
        - birtty-git
        - rasdaemon-git
        - scron-git
        - ofono-git
        - gr-drm-git
        - tilix
        - firefox-extension-ublock-git
        - libretro-pcsx2-git
        - ros-indigo-rosbuild
        - nausea-git
        - trellis-git
        - libopusenc-git
        - kodi-addon-xvdr
        - mingw-w64-libtre-git
        - libx32-keyutils
        - roadfighter
        - ros-noetic-voxel-grid
        - affinity
        - libva-intel-driver-hybrid-gcc10
        - ros-melodic-rotors-control
        - kate-bracesane-plugin
        - libvips-git
        - qt5-enginio-git
        - ros-noetic-graph-msgs
        - ros-noetic-tf2-geometry-msgs
        - lib32-vkd3d-valve-git
        - knot-resolver
        - synapse-bzr
        - rofi-top-git
        - cups-filters-patched
        - gxkb-ru-by-flags
        - ylva-git
        - openrdate
        - equalx
        - mingw-w64-qwt-qt4
        - lib32-libpng12
        - libglvnd-git
        - dmenu-pryme-svg
        - libggimisc
        - kde-cdemu-manager
        - openclaw
        - lame-altivec
        - poac-devel-git
        - vmware-horizon-client
        - health
        - kdeplasma-applets-quickaccess
        - sdl2_compat12-git
        - ros-ardent-fastcdr
        - dispad-git
        - cutecw
        - cxxmatrix
        - timeshift
        - gtk-gnutella-git
        - dragon-drag-and-drop
        - gdash
        - rexuiz-bytecode-git
        - flwm
        - gimp-elsamuko-plugins
        - fbvnc-git
name: BUILD-49
'on':
  workflow_dispatch: ''
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-48
