concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - openra-kknd-git
        - ceaflate
        - lagraph-git
        - vim-git
        - libplayback
        - teg
        - dconf-editor-git
        - eolie-git
        - findwild
        - brotherhood-gui-git
        - gdbm-git
        - or-tools
        - dynarmic-git
        - tmux-24bit-color
        - switchboard-bzr
        - cage-no-xwayland
        - proton-ge-custom
        - snitch
        - ceph-octopus
        - libretro-beetle-wswan-git
        - lib32-liblphobos
        - libx32-ncurses
        - texi2html1.82
        - ros-noetic-move-base-msgs
        - heirloom-doctools
        - dict-freedict-eng-fra-svn
        - batch
        - yate-qt4
        - odio-edit-bzr
        - gnome-metronome-git
        - bergamont-marian-git
        - cockatrice-git
        - bfs
        - skabus-git
        - voikko-libreoffice
        - portsmf-git
        - ndpi-netfilter-dkms-git
        - mintcoin-daemon-git
        - onboard-sdk-git
        - mingw-w64-geany
        - lib32-glibmm
        - git-weave
        - gnome-twitch-player-backend-gstreamer-opengl
        - vim-qt-qt5-git
        - nvidia-think
        - lib32-libx264-stable-git
        - serioussam-oddworld
        - nuvola-app-siriusxm
        - cadence-riccardocagnasso-git
        - vcprompt-git
        - dodo-git
        - chk4mail
        - biblereader
        - repose-git
        - havm-epita
        - grub-legacy
        - speedtest++
        - karmen-svn
        - rl78-elf-gcc
        - autoconf-archive-git
        - mate-applets-dev
        - intel-openamt
        - tcltls
        - sameboy
        - gnonograms-git
        - kasts-git
        - ros-jade-qt-gui-cpp
        - pingnoo
        - xreader
        - gnome-pomodoro-git
        - squidclamav
        - linux-lts49-kallsyms
        - lua-sdl2-git
        - alertmanager-matrix
        - bigsh0t-plugins-git
        - cglm-git
        - quartet-git
        - dogecoindark-qt-git
        - lgx2userspace-git
        - opencascade
        - clang8
        - libmdbx
        - digup
        - libshout-git
        - minetest-git-leveldb
        - ros-jade-rqt-bag-plugins
        - qscintilla-qt4
        - bchoppr-git
        - libhugetlbfs
        - goattracker
        - sarndbox-git
        - umps3
        - coin-or-osi-git
        - bitcoin-cash
        - lib32-libgcrypt15-git
        - qtnotifydaemon
        - astromenace-svn
        - nvim-with-restricted-mode
        - google-compute-engine-oslogin
        - lazarus-qt5-svn
        - brumbrumrally
        - tgif
        - libdbusmenu-qt4
        - gplugin
        - passt-git
        - nginx-passenger-mod-auth-kerb-git
        - ros-ardent-ament-cmake-pyflakes
        - gx-lv2-git
        - wingpanel-indicator-powersave-git
        - rclone-browser-git
        - turtlico-git
        - pyxis
        - chaiscript-git
        - dovecot2-antispam-git
        - imagine++
        - ros-melodic-orocos-kdl
        - kimi-linphone-desktop
        - lib32-cairo-git
        - commento
        - lostfiles
        - enyo-launcher
        - pure-mpfr
        - deadbeef-plugin-fb-gtk3
        - ucto
        - typewriter
        - refind-efi-git
        - synfig-dev
        - synfigstudio-git
        - xchat-fish
        - emulsion-palette
        - teco-git
        - libgnt3-hg
        - methuselah-qt
        - pomodoro-applet
        - messenger-cli-git
        - autoygg-git
        - editorconfig-core-lua-git
        - ksmtp-git
        - xnp2kai-azo234
        - xfce4-panel-devel
        - qvm
        - xmppc
        - pyvtlock-git
        - attr-git
        - exrtools
        - sndio
        - pdftk
        - ros-noetic-ompl
        - libretro-mess-git
        - linux-libre-rt
        - gnome-symphony-git
        - dseams-git
        - delay-architect-git
        - ndsplus-git
        - blis-cblas-openmp
        - libejdb
        - ros-ardent-rviz-default-plugins
        - atlas-lapack-for-flexiblas
        - vkd3d-valve
        - literm-git
        - tomoyo-tools
        - dcmtk
        - incrtk
        - lua52-jwtjitsi
        - nvidia-bfs-340xx
        - gregorio
        - cras
        - phyml-git
        - xdaliclock
        - libretro-higan
        - ros-indigo-web-video-server
        - rtpproxy
        - lib32-lzo
        - xpaint
        - swcdb-manager
        - libowfat-cvs
        - colpack
        - ros-kinetic-rospy-tutorials
        - networkmanager-applet-git
        - soup-sharp
        - xbindkeys-git
        - switchboard-plug-printers-git
        - theframe
        - android-x86-libpng
        - echat
        - carla-git
        - maliit-framework-git
        - polyorb
        - diff-pdf
        - vlsmsolver
        - lib32-libkqueue
        - bitcoin-abc-qt-bchn
        - lib32-libudev0
        - argh
        - gnome-icon-theme-symbolic
        - redis6
        - spamprobe
        - evrouter
        - fuse-emulator-utils
        - libinstpatch
        - mp3gain
        - znc-push-git
        - libt3key
        - memtest86+-6-git
        - libaom
        - kwin-effects-appear1
        - qt5-x11extras-595
        - photoflare-git
        - spl-linux-zen
        - opendnssec
        - owncloud-client-git
        - openssl-tls1.3-git
        - vapoursynth-plugin-fmtconv_wrapper-git
        - pecl-http
        - vdr-cdplayer
        - lci
        - fortune-mod-tgagaapp
        - navcoin-git
        - librevisa
        - goldendict_qt4
        - ros-kinetic-resource-retriever
        - gnome-shell-extension-redshift-git
        - koules
        - pam_sqlite-git
        - collada-dom-mitsuba
        - eog-frameless
        - nymphcast-git
        - tophat
        - caffe-dr-git
        - gogios-plugins
        - ros-kinetic-image-transport-plugins
        - aarch64-gcc
        - kde1-kdetoys-git
        - krathalans-endlessh-git
        - openbsc
        - mingw-w64-gtk3
        - desq-settings-git
        - chroma
        - ossec-server
        - keepassx2-yubikey-git
        - qcl
        - libnbd
        - qt-dab-git
        - remmina-plugin-kwallet
        - phodav
        - hpp-model-git
        - gr-dvbt-git
        - morsetran
        - dlume
        - wineasio-pipewire
        - apertium-afr
        - textpieces
        - bashnapi
        - fondu
        - telepathy-kde-desktop-applets-git
        - amarok1
name: BUILD-20
'on':
  workflow_dispatch: ''
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-19
