concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - evisum
        - gl2ps-svn
        - bshapr-git
        - evtest-qt-git
        - mingw-w64-libmodbus
        - bfgminer
        - accountsservice-elogind
        - libopenblt
        - gnomit
        - passwordsafe-git
        - linux-rpi-legacy
        - exanic-git
        - mopac
        - shen-sbcl
        - apertium-afr-nld
        - deadbeef-plugin-fb-git
        - pentobi-git
        - exactcolors-git
        - ros-melodic-marti-common-msgs
        - atta
        - redis-graph
        - roll
        - telegram-desktop-wide
        - argagg
        - gol-git
        - box0-utils-git
        - fortune-mod-zh-hant
        - l3afpad
        - totp
        - dromajo
        - moss-serpent-git
        - aurora-client-git
        - qmc2-svn
        - einstein
        - gtkdialog
        - ros-jade-rqt-gui-py
        - xorg-xwayland-hidpi-xprop
        - gnome-chemistry-utils
        - gtkhash-nemo
        - dvrescue
        - texman
        - gxmessage-gtk2
        - rofi
        - sais
        - napi-bash
        - xrootconsole
        - ros-noetic-slime-wrapper
        - gnome-shell-extension-disconnect-wifi-git
        - libxdgdirs
        - itk-snap
        - udisks2-elogind
        - fastd
        - exabayes
        - googlemaps
        - shared-mime-info-git
        - tclkit
        - system76-kbd-led-git
        - kasync2-git
        - fcode-utils-git
        - gsopcast
        - timeoutd
        - fresco
        - ros-ardent-visualization-msgs
        - gmssl-git
        - cyrus-imapd2
        - button-lua
        - blueprint-compiler-docs-git
        - ros-melodic-interactive-markers
        - plasma5-applets-nx-systemtray
        - pidgin-znchelper
        - xdg-traymenu
        - blasfeo
        - wmbubble
        - libdeltachat-core-git
        - quickrdp
        - lan951x-led-ctl
        - libsh-git
        - steambridge-git
        - ros-noetic-roswtf
        - flannel-cni-plugin
        - dfu-util-git
        - cerberus-logging
        - ponymix-git
        - mutt_vc_query
        - nanopolish-git
        - avrdude-osuisp2-svn
        - swfdec-mozilla-xembed
        - dtkcommon-git
        - ortfo
        - smtube-svn
        - kodi-addon-inputstream-rtmp-git
        - copac-git
        - csfml-git
        - debugger
        - ros-kinetic-ros-environment
        - titanion
        - inetutils-git
        - hydrogen-cme-git
        - asmotor-git
        - lchat-git
        - opensph
        - mbm-gpsd-git
        - or1k-elf-gcc-stage1
        - polylib
        - pinta-git
        - gdmap-gtk3
        - libpurple-signald
        - caffe-cuda
        - qcomicbook
        - precomp
        - kmime-git
        - frox
        - rdfind
        - klayout-git
        - linux-c720
        - xbyak-git
        - npiet
        - epplet-base
        - devhelp-git
        - kodi-devel-pvr-mythtv
        - soil-git
        - monado-vulkan-layers-git
        - refind-git
        - ros-kinetic-geneus
        - g500-git
        - extramaus
        - kile21
        - tinygo-git
        - gimp-fourier
        - wine37
        - ignition-cmake-0
        - kodi-addon-graphlcd
        - android-aarch64-l-smash
        - ros-melodic-socketcan-interface
        - aludel-git
        - ixfrdist-git
        - twaindsm
        - kalarm-git
        - xmp
        - gss-git
        - trousers
        - snapd
        - nvdock-bumblebee
        - vitalium
        - libmpsse_spi
        - opencpn-plugin-oesenc
        - tytools-git
        - bruteforce-luks
        - lua-lpeglabel-git
        - libx32-libidn
        - libxc3
        - nut-multimedia-git
        - hidviz
        - gnome-shell-40alfa
        - kmod-minimal-git
        - mpd-lightest
        - kdbusaddons-git
        - bbcp-git
        - genius
        - pmonitor-git
        - kauth-git
        - switch-lan-play
        - deepin-boot-maker
        - openvpn-xor-git
        - dma330as-git
        - xfce4-power-manager-git
        - alif-git
        - nginx-mainline-addon-ndk-set-misc
        - atril-xfce
        - homegear-homematicwired
        - geomyidae
        - gopchop
        - xmlrpc-c-svn
        - libcaer
        - mingw-w64-brotli
        - linux-lts54
        - libxfce4ui-nocsd-devel
        - nettle4
        - libgba
        - kwalletmanager-git
        - cest-git
        - cin-git
        - mdadm-patched-intel-rst
        - telepathy-morse-git
        - avs-device-sdk
        - lua-ldbus
        - compiz-ubuntu
        - covergloobus
        - mingw-w64-l-smash
        - openssl-chacha20
        - octetos-db-maria
        - ocaml-ppx_tools-git
        - z3ntu-razer_test-git
        - octave40
        - loadcaffe-git
        - regextester
        - libtiff4-minimal
        - demolition
        - fxsdk-git
        - zenmonitor
        - hardened-malloc-git
        - relink
        - discimagecreator
        - gcc45-multilib
        - ros-indigo-voxel-grid
        - xorg-server1.19-git
        - zfs-dkms-raidz-expansion-git
        - ospray
        - katomic-git
        - libx32-krb5
        - php-pecl-oauth
        - bootcommander
        - zmusic-git
        - cve-check-tool
        - hamster-sidejack
        - englabgui
        - selfie-git
        - minidlna-custom-icon
        - tracks-player
        - aften-git
        - calindori
        - thextech-adventuresofdemo
        - omniorbpy
        - frc-wpilib-git
        - maui-sol-git
        - lua-lanes
        - gtksourceview3-git
        - linux-libre-lts-apparmor
        - dwm-pango
        - xcircuit-git
        - lib32-ncurses-git
        - wudcompress
        - faba-icon-theme
        - kdiff3-git
        - ros-indigo-stdr-resources
        - speedtest-zpeters
        - gnet
        - numatop
        - lib32-libxft-bgra
        - mingw-w64-tasmanian
        - mdocml
        - wxgtk-gtk3
        - elkirtasse-bin
        - mingw-w64-giflib
        - uim-debian
        - qt5-shadertools-git
        - google-breakpad-git
        - tungsten-renderer-git
        - nanocurrency
        - adflite-git
        - php71-imagick
        - binaryen-git
        - ratox-git
        - mingw-w64-opus
        - ricoh-r5u87x-webcam-drivers
        - beamerpresenter
name: BUILD-30
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-29
