concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - vdr-markad
        - xtreemfs
        - mingw-w64-qt6-websockets-static
        - waybar-no-systemd
        - botan-stable
        - mp-5-gtk
        - vo-amrwbenc_p
        - swarp
        - xfce4-power-manager-gtk2
        - hsa-rocr-git
        - wcalc
        - ros-melodic-mav-msgs
        - setroot-git
        - jsoncpp-cmake-git
        - sielo-navigateur
        - mongoose-git
        - mingw-w64-sassc
        - coreimage
        - libburn-git
        - xtensa-elf-binutils
        - pure-reduce-hg
        - asterisk-g72x
        - libkmfl
        - rbdl-git
        - lib32-libcanberra-gtk3
        - kopano-webapp-intranet
        - gpseq-git
        - xde-icons-git
        - kinit-nooom
        - le
        - cockpit-git
        - libcvtapi-git
        - mpboot
        - gnurl
        - mingw-w64-libxau
        - qt6-wayland
        - wsdlpull
        - pam_krb5
        - med-openmpi-docs
        - pilot-link-git
        - yaffs2utils-svn
        - lzbench
        - pegc
        - gjid
        - libsmall-git
        - gnome-shell-extension-gamemode-git
        - rawtherapee-git
        - ros-indigo-polled-camera
        - apertium-nn-nb
        - xdemorse
        - minisat
        - sregex-git
        - ros-kinetic-compressed-depth-image-transport
        - ros-kinetic-gazebo-dev
        - bluez-utils-compat
        - f26-backgrounds
        - libkdumpfile
        - subtitleripper
        - mingw-w64-xgboost
        - tweak-hexeditor
        - mingw-w64-avisynthplus
        - ros-kinetic-gazebo-msgs
        - libdisplay-info
        - fracplanet
        - osvr-libfunctionality-git
        - 7kaa
        - bomi-git
        - libretro-3dengine-git
        - z81
        - 8p
        - rename
        - ico2xpm
        - wolfssh-git
        - xorg-proxymngr
        - pstext
        - timeswitch-git
        - libar2simplified
        - mingw-w64-coin-or-cbc
        - lua-oocairo
        - ev-view
        - iqtree-latest
        - ros-melodic-gmapping
        - swfmill
        - flowtime
        - libfreenect2
        - dogcom-git
        - hawaii-workspace
        - rigsofrods
        - lib32-libbsd
        - gkrellm-snmp
        - vowpal-wabbit-git
        - xwrits
        - gtklock
        - ros-indigo-tf2
        - ros-lunar-rospack
        - stellarium
        - pulse-vumeter-git
        - ptxdist
        - flower
        - quimup
        - eventd-git
        - basiliskii-kanjitalk755-git
        - osmembrane
        - espa-product-formatter
        - liri-networkmanager-git
        - ros-indigo-depth-image-proc
        - thinkfan
        - libff7tk
        - licenseutils
        - kmscon
        - freenas-vm-tools-git
        - pcre2-git
        - fbautostart
        - badwolf
        - jfbterm-freebsd
        - yubico-pam-git
        - ayojs-git
        - lib32-tbb
        - taxi-git
        - wmmixer
        - station-git
        - print-manager-kde4
        - baires
        - aegisub-ttools-meson-git
        - gst-plugins-openwebrtc
        - metag-git
        - cmake-lint-git
        - nvidia-mainline
        - umps
        - ros-jade-fake-localization
        - uksmd-git
        - vndc-git
        - homegear-philipshue
        - spidriver-git
        - ser2net-git
        - cboard
        - pyside6-tools
        - eternallands
        - j8-git
        - rupass-git
        - pure-csv
        - emq
        - mate-disk-utility
        - apertium-recursive
        - ros-noetic-rqt-nav-view
        - copyevent-git
        - amxo_xml_to-git
        - ubuntu-themes
        - openpgl-git
        - wmweather+-git
        - scotch-git
        - lib32-xmlrpc-c
        - vdr-play
        - libosso
        - zimsearch-git
        - alienarena-svn
        - ros-indigo-laser-geometry
        - c_count
        - herwig
        - kronometer-git
        - amdcovc
        - opencv2
        - grisbi
        - textsnatcher-git
        - cmuscoverssdl-git
        - lib32-libmumble
        - dotnet-fixed
        - cx
        - lib32-libc++-rc
        - uci-lua-archwrt
        - ros-kinetic-stage
        - scotch-mpich
        - cage-wayland-git
        - mingw-w64-rhsrvany
        - docker-registry-git
        - fcitx5-paste-primary-git
        - swcdb-lib-fs
        - scilab
        - gajim-hg
        - xorg-server-nosystemd
        - one-tomato
        - kb-simple-http-server-git
        - grpc-git-cmake
        - signing-party
        - ros-indigo-ecl-concepts
        - gnabel-git
        - vapoursynth-winesupport
        - snap7
        - luajit-openresty
        - debsig-verify
        - libpng12-git
        - surgescript
        - avr-libc-git
        - boca
        - qt5-qpa-surfaceflinger-plugin
        - cmus-plugin-vgm
        - dwm-luke-git
        - suxpanel
        - fsniper
        - qservicemenuconfig
        - linphone-plugin-msamr
        - xmbmon
        - librevault-daemon-git
        - gnomint-git
        - corekeyboard
        - hypr-git
        - lib32-sndio
        - editorconfig-geany
        - kipi-plugins
        - autorevision
        - pd-lua-git
        - california
        - lxpanel-multiload-ng-plugin-gtk3
        - teleport
        - cachefilesd
        - alberta-wo-fem
        - argdata
        - roccat-vulcan
        - mafft
        - teatool-git
        - xkblayout-state-git
        - rofi-calc
        - lwp
        - aqsis-git
        - magnum-integration
        - screenshot-tool-bzr
        - switchboard-plug-network
        - libretro-prosystem-git
        - libhttpseverywhere-git
        - krecorder-git
        - cro-mag-rally-net
        - aom-psy-git
        - s6-linux-init
        - file-roller-ja
        - tilda-git
        - yaml-cpp0.3
        - fuse-emulator-sdl
        - krusader-frameworks-git
        - flatbuffers-git
        - librdrand
        - mingw-w64-szip
        - filmulator
        - pikchr-fossil
        - geopard
        - pacman-pb
        - switchboard-plug-display-bzr
        - systray-generic
        - fsearch
        - ros-lunar-rosmsg
        - moonlight-embedded-git
        - libflashsupport-pulse-git
        - ros-lunar-cmake-modules
        - optpp
        - tnftp6
        - betterspades
        - mcrypt
name: BUILD-79
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-78
