concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - hifive1-sdk-git
        - aarch64-gcc-bootstrap
        - something-for-reddit-git
        - emacs-evil
        - ros-kinetic-rqt-web
        - easymorse
        - mpvz-git
        - cntlm
        - thesafe
        - cdist
        - freefem-cs
        - xmonk-lv2-git
        - eel-language-git
        - ros-noetic-rqt-topic
        - minijail
        - mingw-w64-vulkan-loader
        - neotoma-git
        - neverball-git
        - java-14-openjdk
        - claws-mail-gtk2
        - rrr
        - openscenegraph-git
        - cosmic-comp-git
        - printproto-fix
        - xwinmosaic
        - ayatana-indicator-printers
        - apertium-fra-cat
        - u++
        - mingw-w64-srt
        - argh-git
        - vcvrack-goodsheperd
        - clx-git
        - cannelloni-git
        - optimus-manager-qt-git
        - ros-indigo-async-web-server-cpp
        - embutils
        - music-file-organizer
        - lib32-libgtk3-nocsd-git
        - xow
        - obs-linuxbrowser
        - projectm-libvisual-alsa
        - playonlinux-git
        - pidgin-mrim-prpl-git
        - libretro-mame-git
        - gwm-git
        - mingw-w64-qt5-gamepad-static
        - mingw-w64-qt6-translations
        - ly-plank-patched
        - croco-tools-git
        - petsc
        - dtv-scan-tables-git
        - qtemu
        - kpeoplevcard-git
        - java13-openjdk-hsdis
        - docker-credential-pass-git
        - ros-kinetic-visualization-msgs
        - gffcompare
        - lizardfs
        - clapper
        - epson-inkjet-printer-201207w
        - qt6-5compat
        - consoline-git
        - mingw-w64-gsl
        - gnome-shell-extensions-fly-pie-git
        - lib32-alure
        - kmd-compile-aasm
        - php7-smbclient
        - lated
        - catdvi
        - ogre-1.9
        - magichexagon-git
        - keeperrl-git
        - sh4eb-nofpu-elf-gcc
        - qgnomeplatform
        - libws2801
        - sfm-git
        - stripe
        - adjbacklight
        - i8086emu-git
        - kdepim-runtime-git
        - tao
        - wxformbuilder-svn
        - od-automotive-odcantools-git
        - mtr-git
        - xf86miscproto
        - softethervpn
        - switchboard-plug-sharing-bzr
        - mod_itk
        - oleo
        - cook
        - networkmanager-wireguard
        - tinycmmc-git
        - fluidsynth-dssi
        - ros-kinetic-rosbridge-suite
        - mingw-w64-waffle
        - gnun
        - xdg-utils-patched
        - vdr-dbus2vdr
        - ros-melodic-test-diagnostic-aggregator
        - mingw-w64-libusb
        - libgee-git-alt
        - bear
        - kdisplay-kwinft
        - android-aarch64-speex
        - wsjtx-superbuild-git
        - mmsap2
        - pulseaudio-pali
        - opengnb-git
        - lsmbox
        - chann-git
        - xed
        - granite-bzr
        - ros-noetic-librviz-tutorial
        - palette-git
        - imgpatchtools
        - cs-signal
        - nghttp3-git
        - mdk3
        - desktend-git
        - bluez-qt-git
        - opencascade-git
        - libosmocore-git
        - kubernetes-helm3
        - glib2-quiet
        - paperwork
        - bemenu
        - snowman-git
        - konfyt-git
        - ffmpeg-full-extra
        - hplip-reverted-imageprocessor
        - tsclient
        - prelude-manager
        - js52
        - electron4
        - linux-up
        - vcf.lv2-git
        - gopass-git
        - zathura-git
        - rice
        - ros-kinetic-kdl-conversions
        - xde-panel
        - libretro-mesen-s-git
        - kscreenlocker-systemd-homed
        - kde-cli-tools-git
        - ems-qart-git
        - lib32-krb5-minimal-git
        - xmake-dev-git
        - freechart
        - plasma-wayland-protocols-git
        - mate-utils-xfce
        - avdl
        - libjio
        - cv
        - nicotest
        - libtsm-asciinema-git
        - sylpheed-beta-iconmod
        - lib_amxj-git
        - kpimtextedit-git
        - checkmate-git
        - fcitx-paste-primary-git
        - firebird
        - pbrt-v4-git
        - uvg266
        - lokinet
        - libnice-git
        - libtree
        - kmd-git
        - xterm-git
        - cpproj-git
        - sre-tooling-git
        - iok
        - gkrellm-fmonitor
        - h5utils
        - charmtimetracker
        - ros-noetic-perception
        - ros-lunar-unique-id
        - wayland-wall-git
        - war1gus-git
        - zlfo.lv2-git
        - massdns
        - uzbl
        - ros-noetic-rqt-graph
        - usbpicprog
        - surrealdb
        - rnamicro
        - backupninja-borg-git
        - rsfetch-git
        - libbible
        - freeling
        - pies
        - zerofree
        - ros-noetic-imu-transformer
        - libsodium-static
        - maui-manager-git
        - portspoof-git
        - googerteller-git
        - ros-indigo-rosserial
        - nginx-tcp
        - gnome-mousetrap
        - tilda-wayland-git
        - spfft-cuda-git
        - clockutils
        - t1utils-git
        - sway-im-git
        - stardust-xr-git
        - pdal-git
        - gogios
        - bbswitch-e531
        - ros-indigo-smach-ros
        - android-armv7a-eabi-libiconv
        - srilm
        - translate-shell
        - libkgeomap-git
        - beat
        - astreamfs-git
        - mingw-w64-qt5-imageformats-static
        - nasc-bzr
        - arc-icon-theme
        - mpd
        - cninja
        - kde2-kdeutils-git
        - libosip2
        - hdf5-fortran-openmpi
        - cproto
        - virtualbox51
        - unruu-git
        - doomrl-git
        - mairix-largembox
        - kproperty-git
        - geocode-glib-git
        - most-snapshot
        - libcpuid
        - bash-ctypes-git
        - xrootd-abi0
        - libcorkipset-git
        - prefixsuffix-git
        - gnome-contacts-git
        - libnsq-git
        - dsd-git
        - mrpt
        - oss-git
        - linux-lqx
        - libretro-picodrive-git
        - php-zts
        - libtgbot-cpp
        - emerald0.9
        - lib32-mozjpeg-git
        - butt
        - xdg-autostart-hg
        - libreswan
        - redshift-wlr-gamma-control-git
        - plasma5-applets-uptime-widget-git
        - jalv-select
        - libringclient
        - nautilus-folder-icons
        - docker-abuild-git
name: BUILD-116
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-115
