concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - castle-engine-git
        - php-uv-git
        - findnewest-git
        - fwup
        - zeromq-git
        - mavlink
        - plasma-pass
        - vapoursynth-plugin-ttempsmooth-git
        - pantheon-onboarding
        - jwmtools-git
        - daisync
        - kcm-imchooser-frameworks
        - libar2
        - crow-translate-git
        - weeder2
        - cef-git
        - pps-tools-git
        - pantheon-qq-default-settings-git
        - ros-melodic-tf2-py
        - dpp-git
        - qt-at-spi-git
        - ty
        - touchegg-nosystemd
        - looking-glass
        - confy
        - proton-native-git
        - polly-b-gone-git
        - ros-melodic-twist-mux
        - cbmem-git
        - ros-noetic-stage
        - cnmatrix-git
        - linux-fbcondecor
        - libsnl-svn
        - desq-apps-archiver
        - hostapd-wnm-git
        - petsc-git
        - openra-rv-git
        - fluxbox-wm
        - uvg266-git
        - gnuradio-ra-blocks-git
        - ngs-lang
        - gnome-shell-extension-gsconnect
        - ros-noetic-image-proc
        - font-tester
        - capers
        - qdre-compositor-git
        - xsnow-wv
        - icu64
        - moment-git
        - st-distrotube
        - ros-jade-genpy
        - libirecovery-git
        - ros-jade-geometry-msgs
        - ros-melodic-fake-localization
        - qv2ray-plugin-interface-git
        - mupdf-git
        - libg15-git
        - pycdc-git
        - caja-extensions-common-1.15-gtk3
        - libretro-frodo-git
        - qt6gtk2-git
        - sch_cake-lts
        - fontconfig-ubuntu
        - emacs-w3m-cvs
        - brother-mfc-420cn
        - kodi-addon-inputstream-adaptive-any
        - simbuto
        - mutter-topicons-cpu-use-fix
        - triggerhappy
        - papirus-folders-doas
        - lalinference
        - geary-git
        - play-emu-git
        - pnmixer
        - ros-kinetic-qt-gui
        - mysql56
        - ros-jade-robot-pose-ekf
        - libretro-fbneo-git
        - openrw-git
        - llvm-amdgpu
        - dataplot
        - razercfg-git
        - ros-melodic-pcl-msgs
        - ros-lunar-geometric-shapes
        - ignition-msgs
        - imagewriter
        - gifsicle-lossy
        - ros-indigo-moveit-setup-assistant
        - onboard-sdk
        - php56-apcu
        - acr-git
        - thunar-dropbox
        - libmatekbd-gtk2
        - ttf-iosevka-dotted-zero-open-g-hooky-i-italic-l-short-m
        - mbt-git
        - firejail-git
        - stalld-git
        - libx32-tcl
        - zograscope-git
        - lib32-libunwind-git
        - libva-utils-headless
        - vtrunkd-git
        - gdmap
        - cups-cloud-print
        - soldat-git
        - frivpn-git
        - cherry-font-git
        - kopano-webapp-files-owncloud-backend
        - nvidia-vaapi-driver-git
        - linux-manjaro-xanmod-uksm
        - muttonchop
        - f28-backgrounds
        - ros-noetic-moveit-fake-controller-manager
        - postgresql-10
        - timecamp
        - cursynth-git
        - vapoursynth-plugin-ocr-git
        - lantern
        - libcoopgamma
        - rz-jsdec-git
        - jxrlib-git
        - sqlcheck
        - vimb
        - todoist-git
        - conspy
        - fsharp
        - can-utils
        - sudo-hg
        - matrix-3ds-sdk-git
        - gtk-communitheme-git
        - opus-git
        - wmdia
        - libmaus
        - tksystray
        - marble-marcher-ce
        - scrabble-1d
        - narg-git
        - ros-indigo-roslint
        - ros-lunar-hardware-interface
        - highs-git
        - gromacs-5.1-complete
        - herbstluftwm-winterbreeze-git
        - ypbind-mt
        - lib32-net-snmp
        - ros-kinetic-orocos-kdl
        - virt-viewer-git-no-header
        - beegfs-utils
        - mingw-w64-qt5-feedback
        - ssrc
        - qqc2-breeze-style
        - libparistraceroute-git
        - systemd-cron
        - dnf
        - z88dk
        - ros-jade-rqt-reconfigure
        - libx32-bzip2
        - dev-tld-resolver-git
        - jtc-git
        - hru
        - xburst-tools
        - mingw-w64-gst-plugins-base-git
        - qmlbench-git
        - xanalyser
        - thunderbird-firetray-57-git
        - linux-criu
        - ros-indigo-class-loader
        - opentxs
        - colmap
        - lib32-mesa-steamos
        - freesiege
        - gdcalc
        - ros-melodic-carrot-planner
        - libpiscesde-git
        - ros-indigo-urdfdom-py
        - ros-noetic-force-torque-sensor-controller
        - libosmo-abis
        - ros-melodic-trac-ik
        - amdctl-git
        - cherokee-git
        - libcaption-git
        - strawberry-qt6-git
        - libgccjit
        - ros-melodic-voxel-grid
        - liri-screenshot-git
        - tttermwidget
        - np2kai-libretro-git
        - criu
        - interception-dual-function-keys
        - vcsn
        - xpa
        - xsnow-legacy
        - fsatrace
        - gnome-shell-extension-bumblebee-status-git
        - pecl-database-mysql-git
        - wmacpi
        - cpuid2cpuflags-git
        - libgpg-error-git
        - msp430-elf-binutils
        - cpuface-git
        - azirevpn-git
        - raddiu-git
        - xyz-thumbnailer-kde-git
        - sunwait-git
        - ros-indigo-turtlebot-calibration
        - obs-scene-collection-manager
        - g15daemon
        - futurerestore-s0uthwest-git
        - ros-jade-kdl-parser-py
        - cppadcodegen
        - qmedbrowser-git
        - ros-kinetic-bfl
        - hashpump
        - vdr-streamdev
        - ros-indigo-rviz-fixed-view-controller
        - tkimg
        - libqofono-git
        - tcltrf
        - openssl102
        - geticons-git
        - fragments-git
        - autopackage-devel
        - mingw-w64-asio
        - maui-bonsai-git
        - vasm
        - sawfish-theming-git
        - moltengamepad
        - qgis-stable
        - xorg-xdriinfo-git
        - pdftk-gcj
        - paho-mqtt-c-git
        - gromacs-2018-complete
        - groonga-gobject
        - libcutefish-git
        - conceal-desktop
        - libccsds-git
        - lemonbar-clicks-git
        - fvwm-xdg-menu
        - linux-lts-logo
        - mumble-minimal
        - fcd
        - gcc4ti
        - rfbproxy
        - gnome-shell-extension-weather-git
        - gnome-terminal-transparency
        - gnome-radio
        - ipkg-utils
        - lib32-libosip2
        - ros-jade-rqt-moveit
        - roswell
        - fltk-xcas
        - bumblebee-forceunload
        - rsb-cpp
        - xclipd-git
        - curtail-git
        - gdb-msvc-git
        - tlsdate
name: BUILD-59
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-58
