concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - crowd-greeter
        - libperseus-sdr-git
        - mcdp
        - gtk-sharp-3-git
        - abbrase-git
        - balong-fbtools-git
        - nodejs10
        - shayla-git
        - liboil
        - gnome-shell-extension-extension-list-git
        - libdna
        - pam_geoip
        - typhon-svn
        - mmapper-git
        - evpp-git
        - jack-midi-clock-git
        - pantheon-dock-bzr
        - kodi-addon-inputstream-smoothstream-git
        - openmpi-gcc7
        - libkeepalive
        - wl-gammactl
        - mdevd
        - amoebax
        - fcitx5-lua-git
        - avanor
        - wayqt-git
        - nginx-mainline-mod-redis2
        - numad-git
        - gtkhash-thunar
        - rmotifgen
        - todour
        - winchecksec
        - whdd-git
        - indicator-application-gtk2
        - hdf5_18-openmpi
        - wit-git
        - ros-lunar-ros-core
        - kcodecs-git
        - vdr-cecremote
        - holyspirit-svn
        - checkhash
        - taler-exchange
        - firmware-mod-kit
        - inscore-git
        - snescom
        - tcpslice
        - fcdctlpp
        - scopa
        - paps
        - cramfs-tools
        - resticprofile
        - valknut
        - cef-minimal-obs-bin
        - zopfli-git
        - qtaccountsservice
        - taskwarrior-tasknc-git
        - ros-noetic-turtle-actionlib
        - ecwolf-unofficial-git
        - sxlock-git
        - kicad-library3d-git
        - uxplay
        - gkrellmd-git
        - z3
        - cm256cc-git
        - xdm-unexicon-theme
        - kplotting-git
        - tcl-nothreading
        - liri-browser
        - clevo-wmi-dmks-git
        - gnome-recipes
        - icecast-kh-git
        - projectctr-makerom
        - obs-text-pango
        - guile-lzlib
        - vapoursynth-plugin-dfttest2-git
        - cudd
        - tp_smapi-ck
        - libxdgmime-git
        - pam_radius
        - sensors-applet
        - mcl
        - flamenco-worker
        - resolvconf-override-git
        - telepathy-rakia
        - ros-jade-stereo-msgs
        - iozone
        - khronos-ocl-icd-svn
        - lmc
        - gqrx-nrsc5-git
        - batterycm-switcher-git
        - asusctl-git
        - irrdynamics
        - rtl-sdr-git
        - scangearmp-mg8100series
        - osvr-oculus-rift-git
        - fdformat
        - ldapvi
        - libqtolm
        - shadowsocksr-libev
        - hdf5_18
        - ros-lunar-roscreate
        - hpipm-git
        - purple-mattermost-spectrum2
        - rtl8812au-v5-dkms-git
        - xss-lock-session
        - audiobook
        - pluzzdl-git
        - mullvad-vpn-cli
        - h5cpp
        - liquidsoap
        - supercollider-with-plugins
        - hsetroot
        - imapfilter
        - spiceamp-git
        - spectrum2
        - libretro-scummvm-git
        - ukui-themes-git
        - ros-ardent-ament-lint-common
        - txr-git
        - liberal-crime-squad-svn
        - xbanish-timeout-git
        - qv2ray-plugin-trojan-dev-git
        - balongflash-git
        - delphes-git
        - dill-git
        - ros-noetic-urdfdom-py
        - android-aarch64-libxml2
        - bless
        - qsanguoshav2-git
        - dcmtk363
        - denemo-git
        - pcsxr-gtk2
        - libdvbcsa-git
        - silentjack
        - rude
        - morris-worm
        - ros-kinetic-ecl-type-traits
        - kochmorse
        - pumba
        - srptools
        - centroid-rna-package
        - eta-git
        - apertium-mkd-bul
        - 2048-curses
        - harbour-amazfish-git
        - obs-ghostscript
        - wine-stable
        - palaura
        - libretro-snes9x-git
        - kronometer
        - ros-noetic-ros-emacs-utils
        - rxvt-unicode-minimal
        - libxfce4ui-git
        - tribal-trouble-git
        - srsran-git
        - sgminer-gm
        - g15composer
        - dunedynasty
        - ldmtool
        - mingw-w64-xz
        - pocl-git
        - blackpenguin
        - ssvnc
        - glportal-git
        - mlapack
        - tbt
        - colortool-git
        - xwinfo-git
        - amtterm
        - esp-open-sdk-git
        - colemak-mod-dh-git
        - libuv-git
        - gdmenu
        - xawtv
        - brother-mfc-990cw
        - mako
        - ros-kinetic-eigen-conversions
        - breezemite-yakuake-git
        - libspatialindex
        - fingerprintscan
        - nethack-x11
        - re2g-git
        - pacemaker1.1
        - zbar-headless
        - infrared-git
        - openstopmotion
        - fs-uae-git
        - kodi-devel-adsp-freesurround
        - beefy-miracle-backgrounds
        - libthemis
        - plasma-desktop-git
        - cutefish-screenlocker-git
        - cryptominisat4-git
        - linux-studio-lts
        - goatattack
        - icu57
        - mpv-mpris-git
        - translator-git
        - rtsp-server
        - ros-kinetic-ackermann-msgs
        - tcl84
        - mt7601-git
        - obs-ndi-git
        - pause
        - asterisk-lts-18
        - kopano-webapp-spellchecker-languagepack-en-gb
        - spacefm-ng
        - ut4-git
        - amule-dlp-git-patch
        - mingw-w64-llvm
        - linux-ck-pax
        - wopr-git
        - snac
        - mingw-w64-clang-git
        - ros-kinetic-random-numbers
        - obs-vnc
        - felix
        - trinitrotoluol-git
        - spl-linux-hardened
        - libvirt-xen
        - mate-icon-theme-1.15-gtk3
        - openafs-modules
        - liborca-git
        - azeroth-core
        - rdio-scanner
        - uva-tool-git
        - epson-inkjet-printer-201110w
        - mcwm-git
        - lib32-serd
        - gflags-git
        - yuzu-git
        - ocemu-zenith
        - sfnettest
        - pnghide
        - afb-libcontroller-git
        - rpi-imager
        - qmarkdown
        - matita
        - mingw-w64-make
        - swet
        - lib32-nettle-git
        - nanopb
        - lib32-gtk-engine-murrine
        - nodejs-lts-argon
        - kde-thumbnailer-blender-kf5-git
        - mingw-w64-qt6-5compat
        - keyboard_latency
        - ogre-1.8-pagedgeometry
        - minecraft-overviewer
        - st-mattiadr
        - coolmail
        - linapple
        - php81-igbinary
        - nwjs
        - neopg
        - borg-backup
name: BUILD-23
'on':
  workflow_dispatch: ''
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-22
