concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - ros-lunar-transmission-interface
        - qview
        - mingw-w64-bcunit
        - varnish-vmod-dbrw
        - lib32-http-parser
        - libretro-beetle-pce-fast-git
        - flaw
        - cnijfilter-mp250
        - ros-melodic-libuvc
        - hackup
        - icecube-sprng
        - barley
        - vdr-tvscraper
        - trompeloeil-git
        - lib32-gamemode
        - asterisk
        - dict-freedict-fra-deu-svn
        - shell-advancedutils
        - kiwix-tools
        - vmfs6-tools
        - ros-indigo-ecl-command-line
        - dosbox-ex-svn
        - zeroc-ice
        - libcsptr-git
        - pep-jni-adapter-hg
        - cmus-minimal-git
        - instant-meshes-git
        - libunittest
        - libev-static
        - network-ups-tools-git
        - ros-ardent-tf2-msgs
        - r3broot-git
        - gnome-shell-extension-dash-to-dock-git
        - isse
        - lig
        - metasm-hg
        - bamm
        - esearch
        - mogan
        - lib32-libva-minimal-git
        - openflap
        - ros-jade-opencv-apps
        - st-tucuxi-git
        - gawk-select
        - panda-launcher
        - minisign-git
        - libsigrokdecode4dsl-git
        - sdl-compat_image
        - gr-baz
        - qcma-appindicator
        - efitools-git
        - mame-git
        - lzfse
        - wine-rt
        - libvpx-git
        - libreoffice-slim-fixed-git
        - ghmm-svn
        - libsml-git
        - ros-kinetic-kdl-parser
        - hypatia-git
        - mujoco-git
        - amavisd-milter
        - surfer-git
        - dwz-git
        - fcronq
        - compiz-deskmenu
        - notepadqq-victorbnl-git
        - vdr-extrecmenu
        - xlennart-git
        - liri-wallpapers
        - lib32-coin-or-cgl
        - lebiniou
        - netdiscover
        - gameplay3d
        - cndrvcups-lb-cpca
        - retrosmart-icon-theme
        - epics
        - ros-noetic-libviso2
        - xf86-input-cmt-git
        - elephantdsp-roomreverb
        - tensorrt
        - frontieres-git
        - dfuse_pack
        - ros-indigo-hardware-interface
        - procps-ng-git
        - gotty-git
        - mmkeyosd-git
        - liblinear
        - filezilla-storj
        - xrn
        - bstone
        - ros-noetic-rosparam-shortcuts
        - v7
        - snapper-git
        - ros-indigo-kobuki-description
        - darkplaces
        - ros-noetic-moveit-ros-perception
        - ncbi-blast
        - iscan
        - lshwd
        - datamash-git
        - eifl-git
        - adtool
        - cgit-vcs-git
        - rush-git
        - mpd-automount-git
        - radare2-bindings-git
        - libopenshot-audio-git
        - uno
        - sxcs
        - libaom-git
        - sdl2_sound-git
        - wmfrog
        - kotatogram-desktop-beta
        - swirc-git
        - endeavour-git
        - taler-merchant
        - minidlna-video-thumb
        - lib32-nspr-hg
        - ros-melodic-rqt-plot
        - nextcloud-app-contacts-git
        - lib32-libprotobuf-git
        - merkaartor
        - ros-melodic-rosbridge-suite
        - inko
        - xmake
        - idnkit
        - gildas
        - ros-indigo-kobuki-node
        - ros-indigo-turtlebot-gazebo
        - zfs-linux
        - lcm
        - assimp-git
        - git-branch-diff-git
        - dmenu-kian-git
        - corestats
        - embree-bvh_build-git
        - ros-kinetic-realsense-camera
        - man-pages-it-git
        - ros-melodic-image-common
        - cxo
        - lxc-snapshots
        - gkrellm-gkfreq
        - ffmpeg-qsv
        - erlang-gproc
        - olive-git
        - swift-llvm-git
        - libbobcat
        - lib32-libexif
        - ipknot
        - s4-git
        - ratslap-git
        - fnlfmt-git
        - arcan
        - ros-jade-simulators
        - whizard
        - core-git
        - pilot-link
        - kwalletmanager4
        - fgrun
        - libvariant
        - xfce4-panel-hidpi
        - pantheon-mail
        - epson-inkjet-printer-artisan-725-835-series
        - linux-bridge-pl
        - compiz-core-git
        - protobuf3-git
        - ros-kinetic-capabilities
        - mozillavpn
        - steamvr-openhmd-git
        - pology-svn
        - vcvrack-sonusmodular-git
        - cssc
        - cgmnlm
        - vtk6-legacy
        - qhexedit-git
        - libarib25-git
        - irssi-python
        - mysql-workbench-git
        - courier-authlib
        - webapp-manager
        - lib32-fuse2
        - bitcoinxt
        - mingw-w64-passwordfile
        - linux-gl502vs
        - lsyncd
        - xdg-sound-git
        - genkfs
        - xtl
        - libacpi
        - linux-oled
        - np2kai-git
        - coreutils-arch
        - genn_cpu_only
        - gtk2-patched-filechooser-icon-view
        - colorhug-client
        - hepmc
        - planner9-git
        - hypervkvpd
        - carla-bridges-win32-git
        - schroot-hybris
        - tpm-quote-tools
        - xfwm4-gaps
        - postal-git
        - tee-supplicant
        - bmdc-bzr
        - guile-gnome-platform-git
        - epson-inkjet-printer-201115w
        - docker-app
        - gpicview-gimp
        - keepassxc
        - vlc-listenbrainz-git
        - toppler-git
        - kemoticons-git
        - aeskulap-dcmtkcompat
        - oath-toolkit-git
        - catbin
        - lightspp-git
        - ovenmediaengine
        - gnome-shell-extension-privacy-menu-git
        - dbf
        - gcc54
        - icu-48
        - php-solr
        - linux-fsync
        - ros-kinetic-rqt-plot
        - luxrays-hg
        - qt-inspector-git
        - wmmp3
        - qml-box2d-git
        - lingeling
        - mfgtools
        - huestacean
        - toxic-git
        - openrsync-git
        - webbench
        - torrentcheck
        - radamsa-git
        - brlaser-git
        - vislcg3-svn
        - compsize-git
        - eventstat
        - linux-cik
        - clementine-lxqt
        - lib32-libvpx
        - linux-cachyos
        - nvidia-led
        - gdal-curl
        - nginx-lazerl0rd-git
        - mod-cv-plugins-git
        - deepin-qt-dbus-factory-git
        - compton-tryone-git
        - ocp-git
        - kronosnet-git
        - ortfo-git
        - lyra
name: BUILD-140
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-139
