concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - cloudabi-binutils
        - plasma5-applets-pk-updates
        - reed-alert-git
        - otf2bdf
        - ros-lunar-rostime
        - pg_ulid
        - ros-jade-costmap-2d
        - mingw-w64-coin-or-lemon
        - libvterm-014
        - rowhammer-test-git
        - owx
        - fvwm-xdg-menu-git
        - liblsl-git
        - ros-noetic-turtlebot3-gazebo
        - uctodata-git
        - beats
        - kdebase-runtime-plasma4extras
        - passwordmanager-git
        - pipewire-media-session-git
        - waydroid-settings-git
        - pantheon-polkit-agent
        - mesa-git-rbp
        - nift
        - gnuais
        - atheros-ar3012
        - universal-ctags-git
        - umonitor-git
        - quictls-openssl
        - symengine-git
        - lem-git
        - tcg
        - ros-melodic-openni-launch
        - cytadela
        - docker-openrc-git
        - dfc
        - t2b-git
        - fdkaac-git
        - simulide-svn
        - lua-luagcrypt-git
        - remmina-git
        - xfce4-multiload-ng-plugin-gtk3
        - ros-indigo-actionlib
        - libsoup-2.2
        - ssimulacra
        - libselinux-python2
        - sos
        - gz
        - ax25-tools
        - texinfo-legacy
        - dbus-python2
        - signald-git
        - ros-lunar-gazebo-ros-control
        - comedilib
        - obs-gphoto
        - imlib2-heic-git
        - jailkit
        - crystal-icr
        - cfunge
        - beakerlib
        - zsxd
        - blockbar-constwidth-git
        - eqp
        - libsnark-git
        - waifu2x-ncnn-vulkan
        - gcc8
        - gravity-lang-git
        - libfyaml-git
        - shellex-git
        - scalc-git
        - sc3-plugins-git
        - ordered-map
        - libxpid
        - metar
        - gbar-git
        - threemaqt
        - ctpv-git
        - tpm2-abrmd
        - proj-git
        - transmission-pt-edition
        - nginx-http-auth-digest
        - gtkhash-thunar-git
        - tabbed-ashin-git
        - ros-melodic-joint-state-publisher-gui
        - h2o-git
        - workspaces-git
        - enlightenment-dr13
        - moarvm-git
        - emmcdl-git
        - ros-indigo-tf2-msgs
        - sent-git
        - sublime-text-2
        - libmesode-git
        - megaglest-data-git
        - conntrack-tools-git
        - kradio
        - uranium
        - pick
        - kovri-git
        - spice-gtk2
        - rcm
        - mingw-w64-qt5-gamepad
        - blastem-pre
        - shiromino
        - safetynets-git
        - corrupt
        - diffpdf
        - mantid-term
        - lib32-lensfun
        - tianya-git
        - ethereum-git
        - qprotractor-git
        - gnome-colors-icon-theme
        - jdatestamp
        - paperkey
        - plasma-wallpaper-himawari-git
        - slippi-online-git
        - qastrocam-g2
        - midori-passwordmanager
        - gittyup-git
        - bittwist
        - hptools-git
        - keepassxc-client-library
        - openalpr-git
        - ros-kinetic-bond-core
        - scrounge-ntfs
        - emacs-pretest
        - knot-git
        - qt5-graphicaleffects-git
        - ghemical
        - odin2-synthesizer
        - nginx-mainline-addon-redis2
        - dhcpcd-trunk
        - nl-filter
        - dcled
        - violet
        - vo-aacenc
        - redis-graph-git
        - java11-jetbrains-imfix
        - libraqm
        - slowhttptest
        - leafpad-noheader
        - gnome-system-monitor-gtk2
        - mkcl-git
        - reco
        - flux-go
        - pike
        - ssvnc-nojava
        - workrave-next-gtk3-git
        - dhcpcd-git
        - tvtime_patched
        - gnu-apl-svn
        - mcabber-module-external-editor
        - android-x86-boost
        - goclockify
        - qbittorrent-nogui-git
        - android-x86-speexdsp
        - spice-streaming-agent-git
        - compiz-fusion-plugins-extra
        - pygobject-tutorial-git
        - aleeplayer
        - mplayer2-build-git
        - linux-lts-userns
        - mingw-w64-marisa
        - libhomegear-node
        - ps2-libtiff
        - remmina-plugin-webkit
        - nordugrid-arc
        - epson-inkjet-printer-201401w
        - mt7601u-git
        - ocropy-git
        - mqtt-sm-git
        - menu-cache-git
        - arx-liberalis-git
        - biogeme
        - ros-kinetic-eigen-stl-containers
        - tmate-ssh-server-git
        - lib32-glpk
        - libsixel
        - openssl098
        - ocaml-otk
        - calendarsupport-git
        - clipnotify
        - openicc
        - brother-dcp-j752dw
        - ros-noetic-rqt-action
        - eovpn
        - libbpf
        - nvidia-rt
        - cockatrice-client
        - camlp4-git
        - barva-git
        - avisynth-plugin-vscnr2-git
        - polipo-git
        - sheerdns-ng
        - powerupp-git
        - gofish
        - corepaint
        - libfm-qt-git
        - emacs-swiper-git
        - appnotex
        - kcrash-git
        - spectacle-no-purpose
        - frame
        - scd-git
        - passwordfile-git
        - mingw-w64-openssl
        - shiki-colors-revival-git
        - vcvrack-computerscare
        - appcsxcad
        - emacs-swiper
        - lld7
        - geeqie-git
        - pidgin-hide-chat
        - calcurse-git
        - cutter-git
        - yuzu-canary-git
        - ros-indigo-kdl-conversions
        - proton-experimental
        - flmsg
        - libjpeg9
        - ocaml-mysql
        - mingw-w64-zlib
        - kiwix-desktop
        - gspdf.app
        - dino-git
        - google-breakpad-svn
        - tty-solitaire
        - milena
        - mingw-w64-kconfig
        - slimit-git
        - qmic-git
        - abgx360gui
        - kpack-git
        - gplates
        - ros-noetic-four-wheel-steering-msgs
        - preserve-git
        - libardiscovery-git
        - opie
        - solarmeter
        - tcl86
        - tardis
        - klee
        - konstruktor-git
        - libretro-pcem-git
        - blang-git
        - pass-audit-git
        - c2f
        - mod_auth_cas-git
        - gucharmap-gtk2
        - mupen64plus-gui-git
        - frog
        - lib32-harfbuzz-git
        - shipments
        - compton-no-blur-limit-git
        - deutex-devel
        - osvr-display-git
name: BUILD-75
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-74
