concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - pluma-1.15-gtk3
        - medit-full
        - mongo-cxx-driver
        - librsvg-og
        - libdsk
        - harfbuzz-bin-2.9.1
        - mp_doccer
        - dune-grid-glue
        - masskulator
        - pgagroal
        - wingpanel-indicator-network
        - rsaturation-lv2-git
        - als-controller
        - gsignond-plugin-sasl-git
        - kitemmodels-git
        - gnupg-nouid-patch
        - man-pages-el-git
        - legendofedgar
        - gconf-nopolkit
        - pgtcl-ng
        - mir-bzr
        - ros-indigo-rospy
        - ledmonutils
        - stardict-reduced
        - usokoban
        - photoqt
        - kde4-ftps-kio
        - airdcpp-webclient-develop-git
        - clearlooks-phenix-darkpurpy-gtk-theme
        - libretro-mrboom-git
        - fanficfare-git
        - opentracker-ipv6
        - scanbd
        - erlang-nox-r17
        - st-solarized-scrollback
        - saga-gis
        - ros-kinetic-moveit-core
        - feedreader-bzr
        - gimp-voronoi
        - amule-dlp
        - squawk
        - qsolocards
        - vapoursynth-plugin-imagine-git
        - howm-x11-git
        - retroarch-git
        - bcg729-git
        - cvechecker-git
        - dash
        - dhcp-helper
        - dietlibc-cvs
        - linrad-svn
        - fossil-tip
        - libvorbis-aotuv-lancer
        - emacs-helm-git
        - kio-admin-git
        - howl-editor
        - neptune-git
        - ghdl-llvm-git
        - seisan2mseed
        - cryptmount
        - freerouting-zh-cn-git
        - dyndhcpd-git
        - qgroundcontrol
        - metronomek
        - kyua
        - journal-triggerd
        - pa-applet-git
        - c-pluff
        - five-or-more-git
        - ktsuss
        - ros-melodic-rqt-console
        - asix-ax99100
        - ogmrip-shrip
        - aarch64-linux-gnu-wayland
        - tigervnc-viewer
        - sope2
        - one-click-bing-wallpaper-git
        - vieter
        - chronojump-git
        - ros-kinetic-voxel-grid
        - libspng
        - mingw-w64-kauth
        - ortle-git
        - php-parle-git
        - pegasus-frontend-git
        - kodi-devel-audioencoder-lame
        - svt-hevc
        - shenidam-git
        - ktikz
        - arpack++
        - vit
        - libwebsockets-patched
        - soapyrtlsdr-git
        - epkill
        - zhparser
        - budgie-weather-applet
        - firewalk
        - libksi
        - ros-kinetic-roslang
        - terminalpp
        - ryzenadj-git
        - script-communicator
        - opensta-git
        - tse3
        - xtensa-esp32-elf-binutils
        - tempus-framework
        - mosquitto-hg
        - mingw-w64-cairo-bootstrap
        - lutris-git
        - koi-git
        - htslib-git
        - php-scrypt
        - flare-game
        - qllauncher-git
        - pcc-cvs
        - libbox0-git
        - audex-git
        - oxygen-git
        - lanshare
        - tavor-git
        - jmeters
        - celt
        - pantheon-default-settings-git
        - templight-tools-git
        - xrestop
        - cotton-git
        - bcachefs-tools-git
        - switchboard-plug-notifications
        - freedict-tools-svn
        - libsrs_alt
        - toppler-levels-git
        - opensnap
        - multiload-ng-systray-gtk3
        - mingw-w64-leveldb
        - intel-ipsec-mb
        - libcredid
        - clawsker
        - mindi-busybox
        - libfprint-elantech
        - unqlite-unofficial
        - netlink-notify
        - breathing-git
        - coolkey
        - pash-mapper
        - lib32-libtheora
        - brpc-git
        - ros-melodic-industrial-robot-status-interface
        - tagparser-git
        - motion
        - mu-conference
        - bchwallet
        - opencv-java
        - dolphin-git
        - precomp-git
        - psp-oslib-git
        - huaweicalc-git
        - webvirtd-git
        - citations
        - ros-indigo-qt-gui
        - ros-noetic-rosbag-migration-rule
        - ros-melodic-laser-pipeline
        - sdl2pp-git
        - ros-melodic-usb-cam
        - zathura-ypb
        - multimc5
        - okay
        - switchboard-plug-mouse-touchpad
        - cctv-viewer-git
        - joyce
        - icestorm-nightly
        - ton-lite-client
        - digiham-git
        - gnusim8085
        - mumps4
        - mingw-w64-qt6-lottie
        - ckb-next-latest-git
        - z88dk-splib2
        - ros-melodic-pr2-description
        - scim-anthy
        - openboard-develop
        - dieharder-git
        - btogre
        - g2
        - andi
        - apertium-nno
        - gmsynth-modcc
        - rom-properties-all
        - gpw
        - mocu-xcursor
        - easystroke
        - libkdcraw-frameworks-git
        - gmt4
        - ukui-menus
        - sga
        - fortune-mod-willandgrace
        - nuvola-app-soundcloud
        - aarchup-git
        - gnonlin-git
        - bitchx12-git
        - darkice
        - powerdevil
        - feynhiggs
        - libxft-brga
        - stdoutisatty
        - wxqt-dev
        - web-media-controller-mpris
        - texlive-mtheme
        - dipha-git
        - ros-noetic-rqt-service-caller
        - doom-retro-git
        - fortune-mod-dharmaandgreg
        - opencascade-rc
        - dropwatch
        - ilisp
        - telegreat-git
        - ppub
        - gconf-gtk2
        - terminus-font-ll2-td1
        - pianobar-git
        - zimlib-git
        - wmx-svn
        - plasma5-applets-folderlist
        - shinonome-git
        - multimon-ng-git
        - syncthingtray-qt6
        - plasma5-wallpapers-wallpaper-engine-without-mpv-git
        - lemonbar-ucs4-git
        - chaosvpn
        - orbitfight
        - grabc-git
        - dspatch
        - libretro-ppsspp-rbp
        - ocaml-archive
        - kong-community-edition
        - acsccid
        - odt2tex
        - rerun
        - id3tool
        - anjuta-extras
        - theos-cctools-aarch64-git
        - yakuake-sessions
        - ustr-selinux
        - lib32-lapack
        - ros-kinetic-message-runtime
        - pinedio-lora-driver-git
        - epson-inkjet-printer-ep-902a-series
        - libx32-icu
        - mpich
        - kamailio
        - namhyung-global-git
        - edgar-git
        - supermin
        - swath
        - pstack
        - tome2
        - msi-ec-git
name: BUILD-96
'on':
  workflow_dispatch: ''
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-95
