concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - raze-git
        - vlfrx-tools
        - dsh
        - picotool
        - libxspf
        - accel-ppp-git
        - miktex
        - wxgtk-3.1.5
        - wm2-svn
        - colm-git
        - libuiohook
        - fcitx5-pinyin-zhwiki-rime
        - libx32-libssh2
        - nvlax-git
        - datasploit
        - ros-ardent-rviz2
        - threshy
        - touchegg-git
        - mingw-w64-qt5-datavis3d-static
        - vim-minimal-git
        - deadbeef-qt
        - nvidia-system-monitor-qt
        - mesos
        - e4rat
        - gmp-mpbsd
        - mapcrafter-git
        - pam-afs-session
        - magnum-extras-git
        - libaudclient
        - xproperty
        - earlyoom
        - terminol-git
        - notifyconf
        - mpfr-svn
        - openssl-gost
        - bcn3dcura-git
        - htscodecs
        - pamac-classic
        - freerdp-git
        - terpod
        - ros-lunar-urdfdom-py
        - v8-static-gyp
        - libeweather-git
        - ros-melodic-compressed-image-transport
        - ros-jade-gazebo-msgs
        - mingw-w64-jasper
        - linuxdeployqt
        - cuberite-bin
        - xorg-server-dev
        - libx32-libxau
        - yajl-git
        - omnetpp-qt
        - qpi2
        - plymouth-sigfile
        - ros-lunar-eigen-stl-containers
        - cowdancer
        - ahab-git
        - ocrfeeder
        - libgoldilocks-git
        - fzy-git
        - anno-git
        - vapoursynth-plugin-ccd-git
        - aomp
        - qpii
        - i8kutils-smm
        - soapy-uhd-git
        - qm-dsp
        - ros-kinetic-kalman-filter
        - rocm-gdb
        - sentencepiece-git
        - recpt1-stz-git
        - tl
        - 4th
        - piscope
        - aenker
        - qnap-qdk-git
        - pllua-ng
        - iproute2-cake
        - less-osc8-git
        - vim-light
        - dwb-git
        - openss7-modules-lts49-git
        - shiftos-git
        - xtables-addons-dkms
        - freelib
        - tallyard-git
        - cloudcompare
        - crowbook-git
        - r8168-pf
        - xss-lock-locked-hint
        - pantheon-session-git
        - tagutil
        - deutex-git
        - writefreely-git
        - qinfo
        - cellframe-dashboard
        - dragon-drop
        - toga2
        - openboard-git
        - xvkbd
        - go1.13
        - gabtag
        - aspell-da
        - libsubhook
        - tinywl-git
        - freetuxtv-git
        - isic
        - jsoncpp-git
        - motogt
        - fakeuser-git
        - binutils-powerpc-wrs-vxworks
        - libtcod-151
        - cpp-httplib
        - mingw-w64-opencc
        - mkinitcpio-ykfde-git
        - avxsynth-plugin-masktools2-git
        - dave_gnukem
        - keepassx2-twofish
        - linux-rock-kernel-driver
        - ros-kinetic-laser-geometry
        - linux-xanmod-anbox
        - ros-noetic-rosbaglive
        - modsecurity2
        - ros-indigo-opencv-apps
        - ros-noetic-urdf-geometry-parser
        - unzip-iconv
        - coreutils-progress-git
        - kirigami2-git
        - heyu
        - hdepanel-git
        - dibuja
        - libsepol
        - ros-ardent-class-loader
        - playmymusic-git
        - psp-libpng
        - hotpatch
        - multimc5-offline
        - qtcreator-markview-plugin
        - ch552isptool-git
        - ros-jade-orocos-kdl
        - uade
        - wmamixer
        - ros-indigo-turtlebot-navigation
        - wpantund-git
        - roctracer
        - ramscrgen
        - fmipp
        - thttpd
        - libkvkontakte-git
        - ulogd-git
        - netsniff-ng-git
        - ros-melodic-rqt-robot-steering
        - asio-patched
        - mhwaveedit
        - usbguard-git
        - dracut-git
        - jumpnbump
        - omp-git
        - tufao0
        - eboard
        - dotto-git
        - libbinio
        - firejail-no-apparmor
        - kmod-roccat
        - linux-mainline-bcachefs
        - lgogdownloader
        - yay-gccgo-git
        - mate-applet-dock-gtk3-git
        - worker
        - wine-starcraft-git
        - xorgxrdp-git
        - lib32-nettle4
        - vendace-git
        - ffmpeg-mpv-full-git
        - libunac
        - ircc
        - amxb-inspect-git
        - ecap-adapter-sample
        - vim3d-git
        - red_lenlab
        - libpam_pwdfile
        - dwarftherapist-hg
        - httpfs2-2gbplus
        - ungoogled-chromium-ozone
        - evid
        - reprotest
        - swfdec
        - pm-utils-debian
        - cubiomes-viewer
        - lib32-lzlib
        - retroshare-v0.6-svn-beta-without-sqlcipher
        - solunar-git
        - ros-kinetic-controller-interface
        - spacenavd-svn
        - shark-ml-svn
        - blender-2.7
        - serial-io
        - schismtracker
        - xxhash-git
        - cairo-static
        - go-tuner-git
        - freerdp-guacamole
        - ros-lunar-rosmaster
        - rippled-git
        - libcint-cint3
        - mmsap
        - scdoc
        - ferdium-git
        - dvb-usb-rtl2832u-openpli
        - spnego-http-auth-nginx-module-git
        - ros-jade-visualization-msgs
        - libsoxrate-git
        - sprycloud-client-git
        - aylinux-plymouth-tema-ayar
        - reaktoro-git
        - awesome-telegramfix
        - erlang-serial-git
        - vimprobable2
        - php-suhosin7-git
        - pgadmin4
        - raja
        - linux-ryzen-git
        - chapel
        - melonds-git-jit
        - flasm
        - nomarch
        - qt-flif-plugin
        - sispread
        - xfce4-statusnotifier-plugin
        - flexisip
        - yaourtix-git
        - wmifs
        - kodi-devel-pvr-vbox
        - otmorris
        - concorde
        - candle-git
        - yacreader-poppler
        - nginx-mainline-mod-redis
        - libgabe
        - matwm2
        - shxkd
        - ttos
        - marst
        - moltengamepad-git
        - aquaria-ose-git
        - apostrophe
        - libwnck-git
        - timbl
        - pacmarge
        - kde-baseapps-git
        - cvodes
        - ros-melodic-moveit-ros-planning
        - budgie-network-applet
        - geany-plugin-markdown-gtk3
        - libzip-git
        - kube
name: BUILD-36
'on':
  workflow_dispatch: ''
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-35
