concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - festival-ims
        - mmh-git
        - pcb-bus-git
        - lib32-dietlibc
        - nash
        - gcrontab
        - lib32-tcl84
        - converter-git
        - mt-st-git
        - ros-kinetic-pr2-description
        - holo-run-scripts
        - gtkmm3-plplot
        - git-pair
        - dynamixel-sdk
        - libinput-hith
        - sysrss
        - kdecoration-kwinft
        - charmtimetracker-git
        - linux-rpi
        - ffmpeg-amd-full-git
        - qt5-translations-git
        - kparts-git
        - lib32-sandbox
        - fortune-mod-homeland
        - boom
        - gr-cc1111-git
        - nist-sts
        - ros-melodic-mavros
        - mesa-llvm
        - v8-5.2
        - ack-git
        - irssi-naughty-bugs
        - gates-of-tartaros
        - redis-testing
        - icglue
        - libconic
        - plasma5-applets-uswitch-git
        - lib32-allegro
        - midijoystick-git
        - xkb-switch
        - zff
        - d-spy-git
        - ros-kinetic-dwa-local-planner
        - multiload-ng-indicator-gtk2-git
        - kwin-standalone-git
        - desq-utils-powermanager
        - libretro-fmsx-git
        - iccxml
        - systemd-lock-handler
        - unixcw
        - jackbeat
        - liri-terminal-git
        - mysql-connector-odbc
        - gmusicbrowser-shimmer-git
        - wlroots-nox11-git
        - mingw-w64-sdl2_image
        - joycond-nicman23-git
        - gst123-git
        - tomo-el-fuego-git
        - nsfminer-git
        - usbtop
        - vv
        - qucsator-git
        - ros-indigo-hector-compressed-map-transport
        - shadermaker
        - pluma-plugins
        - monero-core-git
        - fbpdf-poppler-git
        - aether.lv2
        - karlyriceditor
        - android-x86-64-libunistring
        - kuiserver-standalone-git
        - zbar-git
        - libusbmuxd-rr-compatible
        - mpqc-shared
        - libretro-bsnes-hd-git
        - pigpio
        - singularity-ce
        - sagemath-python3-git
        - parzip
        - libmega-git
        - kjieba
        - mcabber-crew-hg
        - ros-ardent-test-msgs
        - whdd
        - steam-screensaver-fix
        - symboleditor
        - ros-indigo-warehouse-ros
        - librepfunc
        - uswsusp-git
        - boatswain
        - vapoursynth-plugin-vsimagereader-git
        - kover
        - keyman
        - ros-noetic-moveit-core
        - droidbattles-git
        - tbclock
        - cyanrip
        - ros-melodic-webkit-dependency
        - libjaylink
        - fontmatrix
        - ros-jade-pcl-msgs
        - kguiaddons-git
        - zzuf
        - libopencm3-git
        - wsjtx-bin
        - vala-panel
        - smooth-git
        - kaudiocreator-git
        - pam_pkcs11
        - poac
        - libluv
        - leds-apu2-dkms
        - ros-lunar-rosout
        - lib32-gnu-efi-libs
        - zps-git
        - transmission-csd
        - lib32-gupnp
        - lib32-libsigc++
        - libretro-easyrpg-player
        - members
        - numix-gtk-theme
        - libtelnet
        - digitemp
        - gr-fosphor
        - ccdebug
        - hawaii-icon-themes
        - macfand-git
        - fuel
        - dconf-editor-3.20
        - uctodata
        - salome-smesh
        - guile1.8
        - xfce4-whiskermenu-plugin-gtk2
        - nxlib-git
        - skaffold-git
        - fvwm
        - mummer64
        - openconnect4x
        - twitch-dl-git
        - qt5-base-dev-git
        - ssockets
        - indicator-kdeconnect-git
        - mesen-x-git
        - bassmod-xmms
        - libc++-rc
        - mingw-w64-zimg
        - glfw-git
        - leveldb-mcpe
        - wave-git
        - aegisub-arch1t3cht-git
        - langkit
        - f90cache
        - libvdpau-git
        - qtutilities-git
        - neo
        - fltk-editor
        - task-spooler
        - libretro-freechaf-git
        - ros-noetic-rqt-moveit
        - bspwm-rounded-corners
        - mingw-w64-carla
        - wlrctl-git
        - felinks-python
        - partio-git
        - sunshine-nox
        - dcadec
        - justbuild
        - qt5-style-plugins-git
        - iodine-frekky
        - xjump
        - zathura-seccomp
        - vangers-git
        - dvb-usb-af9035-lts
        - kopano-webapp-filepreview
        - minizip-git
        - cpplog-git
        - gool-git
        - executor
        - mingw-w64-kglobalaccel
        - rush
        - libmypaint
        - smartmeter
        - libsds-git
        - luajack
        - ros-indigo-imu-tools
        - upscaler-git
        - osmo-iuh-git
        - ros-melodic-diagnostic-common-diagnostics
        - gmsynth-vsc55
        - devismaker
        - boswars
        - diffn
        - ada_language_server-git
        - alsa-tools-emu10k1-gui
        - pep-engine-git
        - libsolv
        - taiwins-git
        - ros-melodic-urdfdom-py
        - haguichi-git
        - utf8cpp
        - lapack-static
        - kaar-git
        - i2c-tools-git
        - gnome-text-editor-dev
        - bitcoin-headless-addrindex
        - dazzlie-git
        - gatotray
        - ros-indigo-geometry
        - php-wasm
        - docker-registry
        - fcitx-qimpanel
        - crossc
        - edit-git
        - binclock
        - vcvrack-freesurface
        - kde2-kdelibs-git
        - salome-kernel
        - lib32-osl
        - kopano-webapp-files-smb-backend-git
        - handbrake-llvm-optimized
        - rxvt-unicode-pixbuf
        - apertium-oc-es
        - tempo-git
        - adcli
        - qkismet-svn
        - spl-linux-git
        - teamspeak3-plugin-love-svn
        - clang-trunk
        - libwb-git
        - slingshot-launcher-standalone-bzr
        - policycoreutils
        - corepdf
        - intel-svt-hevc
        - charls-git
        - scream-git
        - eigen2
        - gif2apng
        - groot
        - pusher
        - the24
        - triton-git
        - kstart
        - bigloo-devel
        - glass-wm-git
        - gimp-plugin-resynthesizer
        - votca-csg
        - steghide
        - lowpan-tools
        - openpht-git
        - nvidia-grsec
        - tnef
        - qt5.6-webkit
        - m68k-elf-binutils
        - hiredis0.14
        - arm-android-eabi-glibc
name: BUILD-161
'on':
  workflow_dispatch: ''
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-160
