concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - icu58
        - unfs3
        - spl-lts
        - php82-openswoole
        - android-x86-libogg
        - grcompiler
        - dbus-cxx
        - blosc-git
        - ros-kinetic-visualization-tutorials
        - lib32-sdl2-minimal-x11-git
        - libclc-rc
        - l-band-decoders-git
        - mingw-w64-atk
        - libx32-jemalloc
        - mingw-w64-openexr
        - hardcode-tray
        - aespipe
        - snapraid
        - fantascene-dynamic-wallpaper-git
        - stagit-git
        - sierrabreeze-aurorae-theme-git
        - raxml-standard-git
        - lib32-ffmpeg-compat-57
        - ramsmp
        - desq-utils-sni
        - socketcand-git
        - roguesynth-git
        - gst-python2-git
        - fswebcam
        - jami-qt-git
        - elisa-git
        - openwsman
        - nymphcast-player-git
        - squidguard
        - jitsi-meet-stable
        - music-file-organizer-git
        - thunar-thumbnailers
        - darling
        - prismatik
        - quickfm
        - pglogical
        - wdiff
        - qhuaweiflash-git
        - qsiapi
        - musique
        - tab-git
        - lib32-opencv
        - go-ipfs-git
        - afew
        - wlc-wall-injector-git
        - openl2tp
        - lib32-xcb-util-wm
        - zfs-utils-linux-git
        - pekka-kana-2
        - astrometrynet
        - torrent-file-editor-qt5-git
        - breezeway-mod-git
        - msntp
        - abiocard
        - flannel
        - aleph-git
        - sv2v-git
        - fingerprint-qt5
        - htslib
        - gtkterm_jeija-git
        - mariadb-connector-c
        - firefox-pass-manager
        - vtk-nowraps
        - ilbc
        - ros-noetic-bondpy
        - deepin-tweak-git
        - mediawiki-math-git
        - lib3ds
        - aarch64-linux-gnu-pcre
        - cppmake
        - openocd-esp32
        - bcc-git
        - crack-attack
        - ros-jade-kdl-conversions
        - sjaakii
        - m68k-elf-gcc
        - kovri
        - replicode-git
        - psp-sdl_ttf
        - wecase
        - mblaze-git
        - android-armv7a-eabi-libssh
        - bochs-svn
        - arqiver-git
        - dgtal
        - libzc
        - teensy-loader-cli-git
        - siesta
        - labplot-git
        - kreogist-mu
        - modglue
        - net-tools-debian-ifconfig
        - php-pcov
        - unsimgcr
        - taskd
        - tpm2-tss
        - dfmt
        - clonekeen
        - horizon-launcher
        - intang
        - ros-noetic-rosservice
        - php72-apcu-bc
        - ibus-chewing-git
        - libretro-atari800
        - lib32-qt-at-spi-git
        - libyang-devel-git
        - lib32-vkbasalt
        - stumpwm-git
        - antigravitaattori
        - mangonel
        - cpufetch-git
        - ros-indigo-rqt-gui
        - dcpu-16
        - lis
        - qusb2snes-git
        - musescore-dev
        - pixiewps-git
        - bwbar
        - qml-xwayland
        - gmock
        - openjardin-git
        - blanket
        - libtgvoip
        - openiked
        - vdr-vompserver
        - qdigidoc4
        - xcb-util-cursor-git
        - i3-cinnamon-git
        - m4acut-git
        - cyrus-imapd-new
        - budgie-calendar-applet-git
        - seahorse-nautilus-ext
        - acct
        - instantlock
        - w_scan
        - libsteel
        - uap-cpp-git
        - eql5-git
        - touchpad-disabler
        - gdm-git
        - cardpeek
        - beebem
        - devilspie2-git
        - openvizsla-host-git
        - xtruss-git
        - atcore-git
        - libretro-tgbdual-git
        - asterisk-cisco-gvsip
        - cutefish-terminal-git
        - fof++-git
        - plasma-runners-tmux
        - vapoursynth-plugin-degrainmedian-git
        - libosmo-dsp
        - rxvt-unicode-pixbuf-patched
        - gexif
        - apache-mod_proxy_msrpc
        - libktorrent-frameworks-git
        - gimagereader-beta
        - orage
        - ros-indigo-laser-assembler
        - vokey-git
        - osa
        - aspell-nn
        - libraw16
        - spirv-tools
        - bazel4
        - desq-apps-term
        - diction
        - mingw-w64-sparsehash
        - ukui-panel
        - mdloader-git
        - wmappl
        - ykush
        - ffmpeg-nvenc
        - lcr-git
        - lxqt-openssh-askpass-git
        - netevent-git
        - libinput-complyue
        - todome-git
        - bubble-chains
        - libisl19
        - cloudprint-cups-git
        - ipmiutil
        - wiznote-qt4
        - mint-themes-legacy
        - gmchess
        - libuhd3
        - gnome-shell-extension-jiggle
        - qtikz-git
        - chrome-gnome-shell
        - vala0.26
        - openra-yr-git
        - pdf2laser
        - numix-frost-themes
        - ros-jade-diagnostic-analysis
        - linux-zest-git
        - dv-runtime-git
        - gr-lte-git
        - libretro-meowpc98-git
        - smu
        - lugaru-git
        - libva-intel-driver-hybrid
        - q2vkpt-git
        - shaperprobe
        - wayland-git
        - openafs
        - ncurses-full-git
        - openarena-git
        - vtuner-module-lts
        - chromium-no-extras
        - lib32-librtmp0
        - freerouting
        - nextpnr-gowin-git
        - avrm-max7221-git
        - ctris
        - tunics
        - spl-linux-lts
        - hashlink-git
        - sldr
        - yamc-git
        - popstation_md
        - ccl-git
        - rancher-cli-git
        - ikiwiki
        - cppi
        - magnum-examples
        - pamac-tray-appindicator
        - openboardview-git
        - android-x86-64-expat
        - libabigail
        - psi-plus-plugins-qt5-git
        - icedove-enigmail-git
        - telescope-git
        - kde1-kdegraphics-git
        - chrome-pak-customizer-git
        - cx-latest
        - xfce4-docklike-plugin-ng-git
        - libx32-libdbus
        - buici-clock
        - cdf-nasa
        - libquotient
        - xcsyncd
        - fontship
        - libuinputplus-git
        - php55-xdebug
        - linux-steam-integration-git
        - mahimahi-git
        - fakeroute
        - muchsync
        - intlfonts
        - 0verkill-git
name: BUILD-160
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-159
