concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - java-gcj-compat
        - torrent7z
        - alternatives
        - libsysconfcpus-git
        - sqlite-replication
        - blobby-volley-svn
        - libcommuni-git
        - libfat-nds
        - snapper-tools
        - staden-io_lib
        - dwm-xft
        - xfig
        - aqarahub
        - safir-sdk-core
        - lib32-fstrm
        - cmb
        - snooze-git
        - gmult
        - chromium-vaapi
        - nspr-hg
        - polyseed
        - uhub-git
        - ipmt-git
        - dune-subgrid
        - mingw-w64-med
        - directfb2-gles2-git
        - nss-upwork
        - guitar-git
        - dgedit-git
        - fin
        - piscesde-calculator-git
        - lean-community
        - od-simulation-git
        - qflow-git
        - gcolor2
        - qtcreator36
        - xml2
        - vapoursynth-plugin-rgsf-git
        - bmfdec-git
        - parrillada
        - macaon-git
        - pifs-git
        - lammps-beta
        - ros-noetic-polled-camera
        - sys161
        - neochat
        - ros-ardent-ament-cmake-target-dependencies
        - dynamic-wallpaper-importer
        - rdarktable-git
        - qbittorrent-enhanced-qt5-git
        - fbxkb
        - pop-gtk-theme
        - clutter-git
        - highly-theoretical-git
        - lfhex
        - openfoam-com-git
        - hexcompare
        - telegram-desktop-patched
        - treeviewx
        - sf100linux-git
        - gwyddion
        - xmmplayer
        - arm-compiler-rt-git
        - httpdiff-git
        - epson-inkjet-printer-201115j
        - libcmdlinecpp
        - mastorss-git
        - env-modules
        - amarok-ffmpeg4-git
        - vita3k-emu-fresh
        - actiona
        - pamac-pacaur
        - liferea-unstable
        - cli11
        - spotify-adkiller-dns-block-git
        - pd-faustgen-git
        - kwakd-git
        - ros-jade-rqt-gui-cpp
        - adwaita-qt4
        - openmittsu-git
        - plasma-sdk-tools-git
        - tageditor-git
        - dxpc
        - greenisland
        - jx2
        - dvdisaster-alpha
        - phonon-git
        - randompd
        - slim-unicode
        - netease-cloud-music-gtk4-git
        - ukwm
        - plumed-vmd-plugins
        - tym
        - freefem
        - pymacs
        - hashcat-utils-git
        - ulex
        - zerotier-one
        - balance
        - waffles
        - piscesys-wallpapers-git
        - iwlwifi
        - vpsplayer
        - powerpc64le-linux-gnu-binutils
        - crawl-tiles
        - lib32-primus-vk-git
        - b-step-git
        - claws-mail-gtk2-git
        - nxbgs-git
        - ros-jade-controller-manager
        - gogglesmm-develop-git
        - ros-indigo-mavros-msgs
        - palmkit
        - dsview-git
        - emscripten-git
        - otb-tewi-git
        - libdragon-opengl-git
        - sane-networking
        - nvidia-430xx-settings
        - adljack
        - falcoctl
        - qv2ray-plugin-command-git
        - heimdallr
        - crusta
        - ros-melodic-easy-markers
        - pamac-aur-git
        - linux-ck-reiser4
        - pcre-svn
        - timescaledb
        - kodi-addon-game-libretro-melonds
        - indicator-sound
        - mediahandling
        - fortune-mod-darkangel
        - wallch
        - filetea-git
        - isync-config-patched
        - ros-indigo-turtlesim
        - snappy-static
        - bitcoin-core-git
        - ros-melodic-novatel-gps-driver
        - opensnitch-git
        - ros-jade-rosbag
        - libviface-git
        - ros-ardent-robot-state-publisher
        - avr-libc-debian-git
        - block
        - pop-shell-theme-git
        - ejabberd-git
        - gnome-obfuscate-git
        - hostapd-rtl
        - gnumeric-pure-hg
        - x2godesktopsharing
        - stanford-wbc
        - mingw-w64-sdl2_ttf
        - obexftp
        - logc-git
        - popt-deb
        - ta-lib
        - tippecanoe
        - vcf-validator
        - libao-git
        - psi-git
        - newton-dynamics
        - ros-indigo-laptop-battery-monitor
        - fxprog-git
        - dyninst
        - znc-otr-git
        - iptables-nftables
        - bonzomatic-git
        - threemawebqt-git
        - liquid-dsp-git
        - blockling
        - obfuscate-git
        - brotli-git
        - pqp
        - libechonest-qt5-git
        - sugar-datastore-git
        - remotedesk.app
        - smodels
        - rrootage
        - cmind
        - ts-bt
        - phyml-mpi-git
        - lkl-git
        - pdfpc-notimer
        - mingw-w64-opencv
        - jose
        - coreboot-configurator-git
        - lzlib
        - ephemeral
        - gnome-shell-screencast-vaapi
        - rcswitch-pi
        - ppconsul
        - gnupg-largekeys
        - nsudoku
        - interception-tools
        - kooha
        - icu51
        - lib32-metis
        - android-x86-libtiff
        - ttf2eot
        - nextpnr-git
        - lzdoom-git
        - ufoai-git
        - stund
        - hmmer3-2
        - avxsynth-git
        - slim-git
        - xrestop-git
        - tzclock
        - webdav-daemon
        - libopenglrecorder-git
        - virtualpg-devel
        - pcompiler-git
        - ndpi
        - cdlabelgen
        - ros-kinetic-cpp-common
        - gmnitohtml
        - ros-melodic-rviz-visual-tools
        - meep-git
        - cerberus-securetty
        - ntrack
        - jack_capture
        - arbie-git
        - nemo-chdir
        - lattice
        - jitterentropy-rngd-git
        - swisseph
        - lz4json
        - curv-git
        - geany-highlightselectedword
        - rvvm-git
        - wallchanger
        - vivado-lab-edition
        - sound-theme-elementary-git
        - carbonapi
        - tsc-git
        - extension-manager-git
        - emacs-gnus-git
        - ros-kinetic-moveit-plugins
        - libibcm
        - pnm2ppa
        - krita-plus-git
        - htp
        - esteidpkcs11loader
        - eolie-stable
        - r8168-ck
        - rxvt-unicode-enhanced
        - network-manager-applet-gtk2-jlindgren90-git
        - mimms
        - plasma5-applets-places-widget
        - kodi-addon-pvr-hdhomerun
        - libsoundio
        - grandorgue-svn
        - xgboost-git
        - linux-odroid
name: BUILD-9
'on':
  workflow_dispatch: ''
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-8
