concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - libquicknes-dll
        - avisynth-plugin-vstedgemask-git
        - bencodetools-git
        - kindletool-git
        - minesweeper-terminal
        - utfcpp-git
        - analyse-gamma
        - xtrace-git
        - mpd_notifyd
        - ros-noetic-image-common
        - gaeul-git
        - gnome-pie-git
        - lua-penlight-git
        - tmux-true_colors
        - scangearmp2
        - cage
        - vibrantlinux
        - mingw-w64-libmodbus-dev
        - babeltrace-git
        - ros-melodic-tuw-multi-robot-msgs
        - xse
        - appmenu-qt5-git
        - ocaml-archive-yypkg
        - libdasm
        - lua52-lgi
        - kgocode-git
        - litecoin-git
        - lxqt-themes-git
        - xkblayout-remember-git
        - cdargs
        - mullerfoto-fotostar_sk
        - xmr-stak-git
        - tytools
        - xd-torrent-git
        - libopenrct2
        - pgdbf
        - qxmpp-qt5
        - termcolor-git
        - ros-kinetic-rqt-tf-tree
        - wd-git
        - udevnotifier-git
        - dvdisaster-dev
        - lib32-glfw-git
        - dmenu2
        - lib32-x264
        - pyqt6
        - qtcreator-cmakeprojectmanager2-plugin-opt-git
        - cmdpack
        - rdup
        - i2pd-tools-git
        - busybox-norootreboot
        - docopt.cpp-static-git
        - mgridgen
        - luaradio
        - glasscoder
        - vapoursynth-plugin-tcolormask-git
        - pcc-libs
        - obs-websocket
        - backscrub-git
        - miopengemm
        - deepin-log-viewer-git
        - libinput-three-finger-drag
        - macports-base
        - mingw-w64-opusfile
        - fractal-git
        - itcl3
        - ros-indigo-std-msgs
        - qt5-sparql-git
        - lugaruhd-hg
        - xombrero
        - libretro-jumpnbump-git
        - diamond-editor-git
        - apertium-es-ca
        - dejsonlz4-git
        - fwknop-git
        - kmscube-git
        - linux-ath-dfs
        - inotify-info-git
        - audio_async_loopback-git
        - dnsflood
        - murmur-ice
        - libfprint-1
        - zen-gtk-themes
        - level-zero
        - gprbuild-git
        - shroud
        - kde1-kdewizard-git
        - ros-melodic-twist-mux-msgs
        - terminatorx
        - sed-git
        - faba-icon-theme-git
        - overgod
        - file2key
        - xpdf-motif
        - gnome-shell-extension-hide-activities-git
        - citra-valentin-git
        - xfce4-settings-blank-screen-fix
        - di
        - fcitx-rime-config-git
        - ros-noetic-laser-assembler
        - libreelec-usb-sd-creator-git
        - libphidget
        - xnp2-svn
        - analitza-git
        - sjtu-dnscrypt-accel
        - mig-console-git
        - librnd3
        - webstuff
        - ocaml-objsize
        - dfl-applications
        - billy-frontier
        - paperde
        - lib32-colord
        - kde-thumbnailer-fb2
        - cairo-infinality-ultimate
        - ntfsfixboot
        - snap-confine-apparmor
        - lib32-freetype2-old-hinting
        - apertium
        - tkdnd
        - sopwith
        - gcr-nogtk
        - uhubctl-arm
        - ibus-lite
        - subtitleeditor-svn
        - mdbus2
        - qtcam-git
        - gst-plugins-good-oleavr
        - zxing-cpp-git
        - libcouchbase
        - retropong
        - xfce4-indicator-plugin-git
        - lib32-oxygen-gtk2
        - lpcli
        - chromeos-gsctool-git
        - xar-tpoechtrage-git
        - tilibs-git
        - pppd-ldap
        - qt5ct-svn
        - llvm39
        - systemd-kdbus
        - prismlauncher-cracked
        - fusionclient-git
        - csync2
        - superblt-git
        - pen
        - clasp-cl
        - libkipi-frameworks-git
        - graudit-git
        - gnome-getting-started-docs-git
        - stormchecker-git
        - vala-panel-appmenu-common
        - glogic
        - xorg-server-xwayland-standalone-git
        - scsi_debug
        - backintime-git
        - libgtextutils
        - plasma-workspace-wallpapers-git
        - gnome-twitch-mpv
        - gkrellaclock
        - rng-tools-git
        - ros-jade-message-generation
        - ros-indigo-rotate-recovery
        - libxlsxwriter
        - vdr-skinflatplus
        - gtk-engine-aurora
        - lsuio
        - nginx-mainline-addon-naxsi
        - armory
        - obfuscate
        - virglrenderer
        - hearse
        - mingw-w64-liblo
        - purple-teams-git
        - kaidan
        - libubox-lua-git
        - sumwars
        - mingw-w64-pegtl2
        - system76-oled
        - ttf-dejavu-sans-code-git
        - tuf-manager
        - qliquidsfz-git
        - fatelf-utils
        - breath-gtk-theme
        - deepin-terminal-git
        - slock-solarized-dark
        - geocam-v4l2
        - mingw-w64-tinyxml2
        - bluez-hciconfig
        - shiboken2-git
        - obconf_eui
        - mingw-w64-libva
        - libnfc
        - xmrig-mo
        - ros-indigo-moveit-ros-move-group
        - guile-ncurses
        - enlightenment-wayland-git
        - tsduck
        - bist-svn
        - php-xhprof
        - bcbasic
        - imagemagick-svn
        - gtk2-maemo
        - xdg-launch-git
        - plus42
        - xcb-imdkit-git
        - android-armv7a-eabi-speex
        - gnome-session-git
        - toit
        - ios-webkit-debug-proxy-git
        - fluidplug-git
        - git-cola-git
        - pkgconf
        - cqrlogo-git
        - nuc970-nuwriter-git
        - vfc
        - flite-fpic
        - djgpp-djcrx
        - jansson-git
        - ecflow
        - gnutls-guile
        - papu-vst-git
        - libchloride-git
        - mudita24-svn
        - mingw-w64-z3
        - vcvrack-sonusmodular
        - valentina-git
        - seeks-git
        - ros-melodic-python-orocos-kdl
        - pg_show_plans
        - superderpy
        - xvidcore-svn
        - settings-shim-git
        - vrpn-oculus-git
        - gromit-mpx
        - ignition-rendering
        - tmfs
        - gnucash
        - elementary-iridium
        - lib32-libdv
        - brother-mfc-j875dw
        - gtk1
        - mdtohtml
        - heroes
        - tofrodos
        - ros-kinetic-geographic-msgs
        - samba-mounter-git
        - fortune-mod-zh-git
        - mingw-w64-fftw
        - audi-git
        - unbound-dnstap
        - wmnetload
        - hev-dns-forwarder
        - dfl-config-parser
        - awwan-git
        - commit
name: BUILD-156
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-155
