concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - itpp
        - qt5-avif-image-plugin-git
        - ros-melodic-roslisp-repl
        - ncmpcpp-git
        - dashcore
        - olivia
        - nfacct-git
        - inform7
        - cs-string-git
        - tomahawk-git
        - psad
        - tcc-git
        - spirv-cross
        - silence
        - prometheus-git
        - stormlib-git
        - kindd
        - sfxr-qt-git
        - callaudiod
        - ros-noetic-kinect2-calibration
        - android-armv7a-eabi-libtiff
        - gpupad-git
        - openjk-git
        - ogdf
        - plasma-virtual-desktop-bar-git
        - tdl
        - graphite-git
        - udevil
        - pidgin-tlen-git
        - dcd
        - dsrpdb
        - xfce4-taskbar-plugin
        - xmrig-proxy
        - wtype-git
        - pidgin-musictracker
        - coin-or-coinglpk
        - elog
        - kweathercore-git
        - tn5250
        - lua-luafilesystem
        - ros-noetic-tracetools
        - gtkatlantic
        - docky
        - owrx_connector-git
        - libkomparediff2-git
        - guile-curl
        - i3-easyfocus-git
        - wcp
        - c-mnalib
        - townsemu-git
        - libregexp-git
        - genpo
        - opensgx-git
        - thinkalert
        - torch7-git
        - freeswitch-core
        - linux-baytrail49
        - oidc-agent
        - limoo-git
        - obs-websocket-git
        - xfce4-places-plugin
        - bookmanager
        - dolphin-seafile-plugin
        - musikernel-git
        - cplay
        - uroboros-mon-git
        - ptlib
        - glabels-light
        - gnurl-git
        - yayim
        - libdsp-git
        - ros-lunar-image-pipeline
        - wine-unity3d-git
        - advancemenu
        - datovka-git
        - hdf5-1.8
        - nawk-git
        - ros-indigo-moveit-fake-controller-manager
        - mswatch
        - ros-indigo-zeroconf-avahi
        - libzypp-bindings-git
        - qantenna
        - lib32-libprotobuf
        - g2clib
        - gmic-no-opencv
        - kodi-addon-game-libretro-desmume
        - lief-git
        - libwebsockets-static
        - minetestmapper-git
        - bim-git
        - mingw-w64-libsquish
        - ingen-git
        - vcvrack-amalgamated-harmonics
        - winusb-git
        - dpf-plugins-git
        - ros-jade-image-rotate
        - tango-icon-theme-extras
        - picoc-git
        - ooc
        - algol68genie
        - mingw-w64-physfs-hg
        - dict-freedict-swe-eng
        - uts-server-git
        - rtf2latex2e
        - vanitygen-plusplus-git
        - monetdb
        - gecode
        - libpafe
        - xtrace
        - qlaunchfs-git
        - libidn-133-compat
        - ros-indigo-ecl-time
        - ccrypt
        - simple-stocks
        - linux-nvme
        - qtcreator-freebox-plugin-git
        - ros-kinetic-openni2-camera
        - virtualgl-git
        - apidb-gtk
        - linux-samus4
        - vdr-systeminfo
        - libwdm
        - pylibgamma
        - kindletool
        - n-ndp
        - airdcnano
        - ascii-rain-git
        - makoureactor-git
        - adplay-git
        - protobuf3
        - nvidia-utils-nvlax
        - digikey-kicad-library-git
        - pianobarfly-git
        - envelope
        - apparix
        - asmotor
        - cnijfilter-mg6100
        - dnssec-trigger
        - r-go-tools-led-git
        - grasp-pose-generator
        - dump978-fa-git
        - mingw-w64-syncthingtray
        - gsignond-plugin-oauth-git
        - lib32-tcp_wrappers-lib
        - dfl-settings
        - vapoursynth-miscfilters-obsolete-git
        - boxbackup-server
        - gnome-console-git
        - polkit-qt5-git
        - konbucase
        - gconf-editor
        - cmdiag
        - cado-git
        - qubes-db-vm
        - zsh-theme-powerlevel10k-bin-git
        - lib32-x265
        - cudaminer-git-patch
        - urbackup-server-git
        - ros-melodic-novatel-gps-msgs
        - macopix-cloudef
        - visicut-git
        - homegear-nodes-core
        - open-fcoe
        - linux-prjc
        - liblastfm-qt5
        - linect-git
        - waybar-experimental-git
        - netlistviewer-svn
        - android-armv7a-eabi-boost
        - cef-minimal-3770
        - ros-jade-executive-smach
        - gxplugins-lv2
        - imvirt-git
        - kodi-addon-pvr-vdr-vnsi
        - gnustep-base
        - shiny-server-git
        - openmalaria
        - apertium-bel
        - ros-melodic-lms1xx
        - librime-sbxlm-git
        - mtn
        - openvfd
        - avisynth-plugin-bwdif-git
        - powerkit-git
        - worldpossible-scriptlauncher-git
        - bomi
        - redis-timeseries
        - tklib
        - compiz-git
        - mptcpd
        - netdata-cloud
        - kopano-webapp-spellchecker-languagepack-nl
        - pidgin-latex
        - gdk-pixbuf2-git
        - secnote
        - libwacom1
        - qwt61-multiaxes-svn
        - ros-lunar-qt-dotgraph
        - ros-indigo-genmsg
        - libinput-swap-two-and-three-finger-tap
        - netmon
        - viper4linux-gui
        - ledger-git
        - coreinfo
        - gtkplatform-git
        - mingw-w64-qt6-quick3d-static
        - mingw-w64-qt5-base-opengl
        - android-aarch64-boost
        - mingw-w64-gcc-base
        - qlcplus-git
        - ipt_netflow
        - ros-kinetic-catkin
        - qgis-git
        - nginx-mod-accesskey
        - practice-timer
        - ros-lunar-rqt-robot-plugins
        - lib32-slang
        - php-stat-git
        - waf-git
        - mingw-w64-pcre2-static
        - ros-ardent-poco-vendor
        - ctrl2esc-git
        - immix
        - giza-pp-git
        - multiload-ng-indicator-gtk3
        - gpujpeg-git
        - cpuid2cpuflags
        - mm-common-git
        - gnome-shell-perf
        - lenticular.lv2
        - ros-melodic-qt-gui
        - sxiv-grfreire
        - mkspiffs-git
        - ros-ardent-dummy-sensors
        - gnuclad
        - kxmlrpcclient
        - terra-git
        - php-oci8
        - fontsproto-git
        - nds-banner-editor
        - chromium-gtk3
        - cura-beta-git
        - linux-lts312-ck
        - notify-sharp
        - shortsync
        - skywire
        - mve-git
        - sugar-runner
        - levd-git
        - arm-linux-gnueabihf-binutils-working
        - lightscreen
        - sng
        - ros-noetic-unique-identifier
        - nng-git
        - rocheplot
        - slic3r-prusa3d-git
name: BUILD-112
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-111
