concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - fim
        - mozplugger-aur
        - cubicsdr
        - nautilus-admin-git
        - crocoddyl
        - gcfuse-git
        - uftrace
        - xf86-input-libinput-git
        - sugar3
        - libxtrap
        - kdeclarative-git
        - kimera-vio
        - tclvfs-cvs
        - pantheon-print-bzr
        - kde1-amor-git
        - scrollz
        - discwrapper
        - ssed
        - ott
        - ros-lunar-collada-urdf
        - kfilebox-qt5-git
        - makemetapkg
        - dargite3d
        - vcvrack-eseries-git
        - qv2ray-git
        - pantheon-monitor-git
        - nap
        - snes-asar
        - nginx-mainline-mod-auth-ldap-git
        - cnpy-git
        - commander-zod
        - smplayer-git
        - wannier90
        - knem
        - lastools-git
        - chmsee-git
        - xprintidle
        - ros-ardent-lifecycle-msgs
        - futhark-git
        - openbr
        - metag
        - numdiff
        - cross-mips-elf-gcc
        - linux-mainline-anbox-git
        - sip4
        - sim
        - uberwriter-git
        - swcdb-thriftbroker
        - systemd-bootchart-git
        - kodi-matrix-mpp-git
        - nmh
        - g_lomepro
        - jerry-git
        - ros-indigo-ecl-converters
        - ros-jade-actionlib-tutorials
        - backblaze-b2sync
        - ultrastardx-git
        - ros-noetic-openni-launch
        - sway-asan-git
        - moonfltk-git
        - lib32-gamemode-git
        - ros-indigo-ecl-linear-algebra
        - keepassx
        - lib32-lz4-git
        - dmenu-height
        - libvirt-sandbox
        - adriconf
        - ros-indigo-kobuki-keyop
        - qstat
        - game-speak
        - pyqt4-qtwebkit
        - wyrd
        - blin-git
        - lib32-libvpx1.3
        - convpot
        - toad
        - dolvim
        - openvswitch-git
        - cmyacc
        - procps-ng-static
        - sensei-raw-ctl-git
        - ros-kinetic-transmission-interface
        - irssi-passwd
        - aspcud-svn
        - caffe
        - broadcom-wl-grsec
        - brainfuck
        - kerneloops-git
        - mingw-w64-arpack
        - my_basic-git
        - fcitx5-chinese-addons-git
        - bcn3duranium-git
        - ndpi-svn
        - nvidia-340xx-settings
        - ricochet-refresh
        - banshee-lite-git
        - polkit-elogind
        - softsusy
        - goldendict-git
        - libmowgli
        - wine-staging-git
        - telegram-desktop-git
        - ynot-fossil
        - haveclip-core-git
        - chibi-scheme
        - bitcoinxt-git
        - pacminder-git
        - qtscrcpy
        - tblock-gui
        - gtk4-telegrand
        - ros-jade-shape-msgs
        - kio-admin
        - craftos-pc-accelerated-ccemux
        - tiempo
        - camlistore
        - fetlang-git
        - hardcode-tray-git
        - libretro-crocods-git
        - lua-luv-luajit
        - ros-melodic-roscreate
        - recutils-git
        - clips
        - notcurses-nodocs-git
        - zita-lrx
        - terri-fried-git
        - librsvg-stable
        - kompare-git
        - clash-subscription-updater-git
        - tecoc
        - kwindowsystem-git
        - falco-ebpf
        - ros-melodic-hector-gazebo-plugins
        - postgresql-93-upgrade
        - zanshin-git
        - copyq-plugin-itemweb
        - lanshare-git
        - ghmm
        - librsvg-minimal-git
        - rsfont
        - pacman4console
        - php7-imagick-git
        - astc-encoder-git
        - qmodmaster
        - ros-kinetic-robotnik-msgs
        - swtpm
        - linux-rt
        - fileshelter
        - msim-git
        - grass6
        - ros-noetic-moveit
        - mailnag-gnome-shell
        - salome-gui
        - nginx-mod-form-input
        - photobroom-git
        - vocal-bzr
        - cheesetracker
        - mingw-w64-libbaseencode
        - infgen-git
        - android-x86-64-speex
        - wingpanel-indicator-ayatana-bzr
        - netboot
        - gtk3-mushrooms
        - ocaml-libocaml_ipv4_address
        - gnome-shell-extension-material-shell
        - libuninum
        - c-lightning
        - hardinfo-git
        - assaultcube
        - distro
        - gifpaper
        - cryptsetup-sigfile
        - ros-indigo-kobuki-ftdi
        - php-beast-git
        - kodi-devel-screensaver-pingpong
        - k8vavoom-git
        - rofi-0.15.12
        - ncbi-vdb
        - pollymc-qt5
        - beanstalkd-git
        - mqmgateway-git
        - libnx-git
        - huekeys
        - deadbeef-plugin-customizabletb-git
        - scribes
        - lemon-lime-git
        - ros-kinetic-rviz-python-tutorial
        - tomoyo-tools-25
        - sudoku-savant
        - libalkimia
        - ros-lunar-pluginlib
        - orage-4.10
        - gnome-calendar-linuxmint
        - strace-with-colors
        - lescienze500
        - xdg-utils-lxqt-issue1298
        - kodi-devel-audiodecoder-sidplay
        - lib32-krb5-git
        - linux-userns
        - vdr-plugin-upnp-git
        - ros-melodic-moveit-ros-occupancy-map-monitor
        - keyboard-backlightd
        - openvpn-dco
        - dbus-elogind
        - quickstack-git
        - gtk-arc-flatabulous-theme
        - cura
        - kio-light
        - mingw-w64-dlib
        - lib32-wxgtk3
        - xf86-video-siliconmotion
        - kuesa
        - joy
        - focalboard-server-git
        - jlibgamma
        - ydotool
        - appleseed-git
        - ovras
        - minilibx-git
        - libtensorflow-lite
        - petri-foo-git
        - libpng14
        - matcha-terminal-git
        - arduide-git
        - cdcd
        - mt7601u-ap-dkms
        - ada-web-server
        - libminigbm-git
        - ros-noetic-mk
        - libvarnam
        - catchme-git
        - japa
        - imx-code-signing-tool
        - imdb-rename
        - gnome-initial-setup-git
        - moksha-module-mem-git
        - rasdaemon
        - f3-git
        - nemo-megasync
        - octopi
        - serialtest-git
        - gnome-news-git
        - samhain-server
        - libfxqmlhelpers
        - glade-3.18
        - openbox-menu
        - ros-noetic-moveit-ros-planning
        - avvie
        - fluidkeys
        - ddumbfs
        - libretro-glupen64-git
        - osvr-steamvr-git
        - st-aloussase-git
        - sdvt-git
        - mingw-w64-kdreports-git
        - rnm
        - wxsvg
name: BUILD-106
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-105
