concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - flatbuffers-static
        - rexima
        - cnijfilter-mg5100
        - process-cpp
        - imageplay-git
        - librnnoise-ladspa
        - opentaxsolver-2018-svn
        - libreoffice-style-breeze-git
        - dfmt-git
        - epson-inkjet-printer-stylus-photo-px810fw-series
        - typioca
        - pegtl
        - libc++-msan
        - spectrum3d
        - regextester-git
        - termitegame
        - aarch64-linux-gnu-gcc-stage1
        - libipt-git
        - ros-indigo-rqt-srv
        - simplenote-electron
        - nostalgia-git
        - ukui-desktop
        - wwwidgets
        - devkitppc-portlibs-mxml
        - xfce4-dev-tools-git
        - gxml-git
        - kxmlgui-git
        - polygen
        - ktechlab-qt5-git
        - fpart
        - gcompmgr
        - ft32-elf-gcc
        - glorytun
        - lib32-libdaemon
        - guile-config-git
        - pam_csync
        - soup-sharp-git
        - go1.13-gen
        - vncsnapshot-png
        - qtel
        - ros-noetic-imu-filter-madgwick
        - gammastep-git
        - crystal-icr-git
        - somafm-qt-git
        - ebadoo-shell-extensions
        - ogmrip-oggz
        - srt-live-server
        - rmlui
        - thecalculator
        - light
        - photofiltrelx-git
        - luajit-lanes
        - espeak-ng-extended-git
        - chronograf
        - clipbored-git
        - ros-indigo-gripper-action-controller
        - heekscnc-git
        - zbackup-git
        - ros-ardent-dummy-robot-bringup
        - hamster-shell-extension-git
        - tea-qt
        - appstreamrunner-git
        - kdelibs
        - regina-rexx-das
        - ppsspp-git
        - databaseanime-git
        - qprint
        - kremlin
        - ivona
        - greitukas
        - ros-ardent-rosidl-typesupport-interface
        - cro-mag-rally
        - agentsmith
        - divine2-ltsmin
        - hdf5_18-cpp-fortran
        - pacapt
        - mingw-w64-libgeoip
        - cli-visualizer-git
        - vulkan-kompute-git
        - ocrfeeder-git
        - lib32-python2
        - alarm-clock-applet-git
        - snestracker
        - metaio
        - gnome-bluetooth-git
        - dd4hep
        - navit
        - libsioclient-git
        - lackey-git
        - click4ever
        - qchat
        - cfrds
        - mingw-w64-nfft
        - cppcheck-nogui
        - ncinvaders-git
        - ats2-postiats
        - lib32-libtirpc-minimal-git
        - gimp-plugin-fourier-git
        - umtp-responder-gui
        - oxygen-kde4-git
        - q5go
        - tilp-git
        - gradio-git
        - ros-noetic-rqt-gui
        - toost
        - smb4k-kf5
        - ncp
        - qt5-pim-git
        - sslproxy-git
        - mpd-sacd
        - android-qt5-armeabi
        - diffimg
        - krunner-pass
        - kvazaar
        - keepassx-http
        - backupninja-git
        - telegram-git
        - neard
        - heirloom-ex-vi-cvs
        - linux-cdown
        - barnowl
        - mauikit-documents-git
        - freeciv-sdl2
        - fgsl-git
        - ros-ardent-ament-cmake-export-libraries
        - packageprovides
        - lua-ossl-git
        - qcsxcad
        - auto-07p
        - flaxpdf-git
        - qpsnr
        - ncid
        - qt5-gstreamer
        - sidplay2-alsa
        - pokoy
        - veracrypt
        - morgenlichtctl
        - libvdwxc
        - icsiboost
        - vala0.12
        - vmir
        - showcase-git
        - librdkafka-git
        - kalk-git
        - shape
        - qnetwalk
        - geosteiner
        - netsurf-git
        - twelf-git
        - mariadb-connector-odbc
        - grit
        - ros-melodic-octomap-server
        - detex-convert-git
        - plank-minimal
        - fence-virt-git
        - ros-kinetic-executive-smach
        - admesh
        - network-manager-wireguard-git
        - texinfo-js
        - dunan
        - foo-wm-git
        - libretro-dosbox-svn
        - chromeos-ecutil-git
        - xfce4-sntray-plugin
        - opendds-git
        - olivetin
        - vattery
        - ros-lunar-python-orocos-kdl
        - libquotient-encryption
        - torsocks-git
        - flucoma-cli-git
        - makeheaders
        - esperanza-git
        - amsynth-git
        - epson-inkjet-printer-l800
        - wterm-git
        - segfault
        - nginx-openssl-1.1
        - fatattr
        - network-manager-applet-passwordstore
        - libtecla
        - lib32-gd
        - dtkwidget-git
        - lib32-poppler
        - ros-lunar-rosbag
        - alevt
        - barriers
        - rralle
        - ros-lunar-rqt-py-common
        - ros-ardent-ament-cmake-cppcheck
        - dapl
        - okcashd-git
        - playgsf
        - spotifile
        - carla-bridges-linux32
        - monopd
        - passcheck-data
        - chicken-marks-git
        - gomd-git
        - sdl12-compat-git
        - opensnap-quicktile
        - polymc
        - numix-themes-electric
        - cmpfit
        - mips64-newlib-n64
        - mips64-elf-gcc
        - linsmith
        - cgit-pink
        - jed
        - ps2-sdk
        - mingw-w64-qscintilla-qt5
        - ifrextractor-ls
        - mod_scgi
        - openframeworks
        - pdl2ork-lv2plugin-git
        - sbackup
        - xtinyterror.lv2-git
        - powerpc64-linux-gnu-linux-api-headers
        - fuse3-p7zip-git
        - dnsmasq-china-list-git
        - foo-yc20-git
        - gawk-gd
        - dtn-tools
        - xcftools
        - libajantv2
        - devkitppc-portlibs-freetype2
        - php-svn
        - ocarina
        - sedutil-cli
        - dapnetgateway-git
        - lemonldap-ng
        - apt-move
        - lima-gui
        - ocaml-process-git
        - hypnotix-git
        - libnymphcast-git
        - mpdevil
        - lsiutil
        - minizip2-2.3.3
        - wpa_supplicant-wep
        - marco-1.15-gtk3
        - kidletime-git
        - aur-hiawatha
        - yamagi-quake2-ctf-git
        - minijail-git
        - spl-lts318-ck-git
        - cryptol-git
        - openssl-3.0
        - done
        - gst-plugins-base-git
        - ipx
        - hlsdl
        - audacious-imms-svn
        - tvheadend
        - libnfd
        - ctk
name: BUILD-15
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-14
