jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - muse
        - mqtt-system-monitor
        - particle-life-git
        - eifl-dev-git
        - gsignond-plugin-lastfm-git
        - libcec3
        - leocad
        - vapoursynth-plugin-damb-git
        - vbam-svn
        - flv2mpeg4-svn
        - vulkan-caps-viewer-x11
        - tpgt
        - moarvm
        - lxpanel-multiload-ng-plugin-gtk2
        - nkf-git
        - librlib
        - libinih-git
        - unity-gtk-module-standalone-bzr
        - blackchocobo
        - uboot-tools-rc
        - ticcltools
        - ufsutils
        - murmur-snapshot-noice
        - cicpoffs-git
        - bakelite
        - superiotool-git
        - sway-im
        - corefm-git
        - xfce4-xkb-plugin-git
        - vde2-static
        - gstreamer-properties
        - arm-linux-gnueabihf-android-linux-api-headers
        - njam
        - wabt
        - libx32-harfbuzz
        - aptman-git
        - fql
        - adapta-backgrounds
        - rl78-elf-gcc-stage1
        - cling
        - hfp
        - mingw-w64-qt6-declarative-static
        - wjelement-git
        - gittyup
        - vice-gnomeui-devel
        - libhtp
        - apertium-arg-cat
        - prismatik-psieg
        - ros-noetic-moveit-planners-ompl
        - intelmetool-git
        - tpm2-abrmd-git
        - gr-hpsdr
        - glslang-git
        - libnet-git
        - wolfssl-git
        - gkraken
        - alexandra
        - soapysdrplay3-git
        - gaeguli-git
        - lib32-sni-qt-patched-git
        - gnutls-openssl
        - libindi-qsi
        - smb4k-git
        - ay-gaste
        - excalibar-git
        - mingw-w64-harfbuzz-static
        - rednukem-git
        - libusb3380-git
        - pev
        - wasm3
        - java-atk-wrapper-openjdk-ea
        - vo-amrwbenc
        - lib32-libstdc++5
        - ykchalresp-nfc
        - ros-noetic-class-loader
        - vegastrike-engine
        - phaethon
        - conway-git
        - zfs-utils-lts318-ck-git
        - ros-melodic-gazebo-msgs
        - lv2lint-git
        - qdmenu
        - arm-frc-linux-gnueabi-gcc
        - scrollz-git
        - dict-freedict-deu-eng
        - android-aarch64-qt6-networkauth
        - libkate-python3-git
        - wlr-randr-git
        - friidump
        - st-dchaovii-git
        - gnome-shell-extension-panel-osd-git
        - lib32-libappindicator
        - gdb11
        - spookyghost-git
        - ros-kinetic-roscpp-serialization
        - nvi-multibyte-git
        - liblouis-git
        - nase
        - mapbox-gl-native
        - lib32-mesa-libgl
        - ruijieclient-git
        - sam7utils
        - cen64-qt-git
        - audacious2-plugins
        - unbuffered
        - cathook-git
        - wake-git
        - graceful-udisks
        - dejagnu-git
        - indicator-session
        - vaults
        - rezound-git
        - noisetorch-git
        - ros-noetic-teb-local-planner
        - dbus-x11-nosystemd
        - auralux-visualizer-git
        - fotowall-git
        - gst-plugin-libde265
        - vapoursynth-plugin-fft3dfilter-git
        - lib32-faad2
        - vddiff-git
        - yaft
        - snorenotify
        - libindi_3rdparty
        - mono-basic
        - zfs-linux-ck-zen
        - musique-git
        - ros-noetic-cartographer-ros-msgs-git
        - netrek-client-cow-git
        - libtexprintf
        - links1
        - core-lightning
        - keepassx-zero-git
        - plasma5-applets-weather-widget-git
        - general-tools
        - glog-squash-git
        - bandwidth
        - fenics-basix-git
        - mod_sass-git
        - ros-indigo-tf2-eigen
        - desq-utils-volume
        - mathcomp
        - ros-melodic-rosbridge-server
        - libgmxfort
        - gensort
        - kodi-devel-audioencoder-flac
        - ffmpeg-intel-full-git
        - torcs
        - mcproxy
        - ecap_clamav-adapter
        - mozart2-git
        - jacklistener-git
        - lighter
        - wiiuse
        - bacula-client
        - kyverno-git
        - libva-git
        - nicstat
        - himitsu-git
        - pasystray-gtk2
        - minbar
        - dotto
        - mingw-w64-ois
        - bctoolbox
        - t38modem
        - flatseal
        - oilshell
        - jumanji-git
        - ros-indigo-stdr-parser
        - nfs4-acl-tools
        - gytparse
        - postgis-svn
        - swayfx
        - qgo-git
        - evolution-mapi
        - ibus-git
        - jpeg-recompress-git
        - ibus-hangul-3beol
        - avrdude-svn
        - mbtserver-git
        - cdi
        - ros-kinetic-moveit-msgs
        - blackbox-tools-inav
        - zeroc-icee
        - sblim-sfcc
        - sphvr-git
        - ultimate-doom-builder-git
        - ectool-git
        - tsocks-ipv6
        - qlandkartegt
        - femtolisp-git
        - sisctrl
        - pantheon-dock-git
        - opensnitch
        - eschalot-git
        - xtide
        - libpurple-carbons-git
        - cutefish-qt-plugins-git
        - pkgrepo
        - anopa
        - opentracker
        - apertium-swe
        - linuxkit-git
        - rocclr
        - ros-noetic-rosmake
        - pure-pcre
        - ros-kinetic-rqt-dep
        - sailautossh
        - mingw-w64-mono
        - mp4v2
        - polygnome
        - cockroach
        - contrast-git
        - mmfm
        - digikam-git
        - sunwait
        - wirouterkeyrec
        - apertium-fr-es
        - ros-kinetic-turtlesim
        - ros-lunar-controller-manager-msgs
        - coot
        - bitlbee-facebook
        - lib32-libopenssl-1.0-compat
        - desq-apps-docs
        - lavalauncher
        - oclhashcat-cuda-git
        - ros-melodic-ros
        - ros-indigo-rosserial-python
        - lotr
        - ecl-unicode
        - mbox2eml
        - guvcview-git
        - qgo2-git
        - ros-melodic-move-base-msgs
        - lib32-imlib2
        - easyrpg-rtp
        - systemd-boot-password
        - dvbstreamer
        - verilator-git
        - text2pdf
        - stratisd
        - cppqc-git
        - open-phd-guiding-git
        - qtftp-qt5
        - greenbone-security-assistant-alternative
        - crossc-git
        - vapoursynth-plugin-miscfilters-git
        - dark-podval-demo-git
        - usbguard-applet-qt
        - instawm
        - gnome-mines-git
        - man-pages-sv-git
        - wesnoth-1.10
        - ros-noetic-pointcloud-to-laserscan
        - krita-next-git
        - mayo-git
name: BUILD-124
'on':
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-123
