concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - openssl-pkcs11-export
        - bumblebee-picasso-git
        - libcmatrix
        - wev
        - clanlib10
        - ros-melodic-audio-common
        - iup-gtk
        - ros-jade-image-common
        - switchboard-plug-bluetooth
        - lossywav-git
        - xdebug-zts
        - kongress-git
        - hunspell14
        - libnotifymm
        - double-conversion
        - ros-noetic-ecl-time
        - origin-client
        - nginx-mainline-mod-ipscrub
        - xplayer-git
        - bitcoin-abc
        - power-profiles-daemon
        - bumprace
        - woodpecker-agent
        - nginx-quic-mod-brotli
        - gr-nrsc5-rx-git
        - mingw-w64-gnu-efi
        - kodi-addon-pvr-vuplus-git
        - dmenu-randoragon-git
        - droidstar-git
        - kwalletcli-git
        - libmirisdr-git
        - harfbuzz-git
        - cryptcat
        - ros-noetic-laser-geometry
        - qmc2-git
        - mingw-w64-sdl_mixer
        - mrsh-git
        - archimedes
        - uvm-systemc
        - ros-melodic-urdf-tutorial
        - stardict-tools-git
        - ros-indigo-hector-imu-attitude-to-tf
        - caffe-opencl-slim-git
        - qt5-serialbus-595
        - git-sh-git
        - modmanager-git
        - deepin-grand-search-git
        - lib32-ldb
        - gitin
        - ros-noetic-moveit-planners
        - jabberd14-git
        - trojita
        - ros-noetic-moveit-resources-fanuc-moveit-config
        - cinelerra-cv
        - liri-session-git
        - minised
        - upset_cli
        - ldid2
        - efivar-static
        - retrosmart-x11-cursors
        - abyss
        - sdrpp-git
        - lib32-raptor
        - virt-viewer-light
        - glimpse-editor-git
        - ros-indigo-ros-core
        - rmg
        - dwmblocks-ekollof-git
        - elektroid-git
        - cargs
        - enemylines7
        - linux-x205ta
        - ros-lunar-robot
        - proftpd
        - borgbackup-git
        - charge-guru
        - textosaurus
        - wsjtx
        - libarmavlink-git
        - pam-python-git
        - ros-lunar-tf2-eigen
        - libdlna
        - lib_amxb-git
        - ocaml-libocaml_option
        - ros-indigo-imu-filter-madgwick
        - libsyncdir
        - urweb
        - bubbles-git
        - ch341eeprom-git
        - compiz-gtk-standalone
        - libclc-minimal-git
        - relion-git
        - libosc++
        - astroid
        - flashmap-git
        - plasma5-applets-resources-monitor
        - ros-jade-desktop
        - hdf5_18-mpich
        - cjose
        - android-aarch64-qt6-quickcontrols2
        - nuvola-app-youtube
        - qelly-git
        - mbrola
        - root
        - xsimd
        - libcpufeatures
        - gtk-led-askpass
        - shengbte
        - sh3eb-elf-binutils
        - xastir-cvs
        - sssd-git
        - ros-lunar-bondcpp
        - freeoffice
        - wiznote-git
        - poppler-lcd
        - gnome-fuzzy-app-search-git
        - robocut
        - fortune-mod-warehouse13
        - arch
        - libaec-static
        - iucode-tool
        - gkrellm-volume
        - telepathy-logger-qt-git
        - tensor-git
        - patchelfmod
        - ros-melodic-tuw-airskin-msgs
        - evolvotron
        - linux-serial-test-git
        - openorienteering-mapper
        - i3lock-spy
        - rhyme
        - fetchutils-git
        - ffmpeg-full-server
        - amalthea-gdc
        - hipfort
        - contemporary-widgets
        - alot-git
        - banner-viewer-git
        - tuxcmd-modules
        - ros-noetic-mavlink
        - snd-gtk-alsa-cvs
        - qcalcfilehash
        - mingw-w64-pango-static
        - nvidia-ck-fbcondecor
        - eternity-engine-git
        - rtpengine
        - an9wer-dwm
        - ros-noetic-rotors-gazebo-plugins
        - tengine-extra
        - zorp
        - imlib2-jxl-git
        - tsgl-git
        - cutefish-wallpapers-git
        - opensmtpd-table-sqlite
        - complx-git
        - taisei-git
        - hydra-git
        - noise-bzr
        - mbs-git
        - pgsphere
        - ink
        - emas-git
        - libcurl3-gnutls
        - wxgtk-dev-opt
        - fasttuna
        - nanox
        - gimp-dbp
        - cisco-git
        - lib32-glew-git
        - apparmor
        - luxcorerender
        - libenglab
        - pybitmessage
        - afl-qemu
        - elf2hex
        - waypoint-git
        - crosswords-puzzle-sets-nienteperniente
        - ros-melodic-rqt-shell
        - libccmio
        - openmsx
        - remacs-git
        - mingw-w64-hexer-hobu
        - gfsm
        - fred
        - sortpuz
        - e_cho-git
        - podman-tui-git
        - sgi-fonts
        - dbus-selinux
        - tftp-hpa-destruct
        - voidcsfml
        - kahip
        - fortune-mod-theshield
        - gpshell
        - gnucap-make-git
        - brunsli
        - zarafa-libvmime
        - cnijfilter-mx880
        - heirloom-sh
        - tidyp
        - yamagi-quake2-rogue-git
        - gahshomar
        - oggvideotools
        - asusctl
        - topbeat
        - gatotray-git
        - nvidia-zen
        - kclock-git
        - vim9-git
        - morris
        - smart-kobold
        - lswt-git
        - backup-conf
        - linux-xanmod-rt-mnative
        - telepathy-gabble-cisco
        - stratagus-bzr
        - linphone
        - italc
        - java8-openjdk
        - purple-vk-plugin
        - vct
        - flvmeta
        - android-aarch64-qt6-lottie
        - sov-git
        - rumor
        - qtermwidget-q4
        - fcitx5-sayura-git
        - llvm90
        - compiz-fusion-plugins-extra-git
        - flux-scm
        - sway-audio-idle-inhibit-git
        - fungw
        - nftlb-git
        - hexchat-indicator
        - libxls
        - doxygen-git
        - gcc-git
        - popt-git
        - minetest4
        - bloomrpc
        - ve
        - imewlconverter
        - openfreebuds
        - ros-noetic-rqt-robot-dashboard
        - chatterino2-dankerino-git
        - ros-kinetic-tf2-kdl
        - qt5-pmp-webchannel
        - ctypes-sh
        - gtk-engine-unico
        - reciteword
        - pixbufloader-qoi-git
        - ps2-sdl_ttf
        - ros-noetic-joint-state-publisher-gui
        - ros-jade-roscpp-serialization
        - zfs-utils-archiso-linux
        - goaccess-systemd
name: BUILD-163
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-162
