jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - tenace
        - offrss
        - abduco-git
        - vulkan-memory-allocator-git
        - hpklinux
        - graphui
        - vdr-svdrposd
        - vkbasalt-git
        - libmediawiki
        - monodevelop-beta
        - libfann
        - ros-indigo-move-base-msgs
        - nsntrace
        - mingw-w64-raytracinginvulkan
        - deepin-icon-theme-git
        - guile-todo-git
        - pinapp
        - libadwaita-health
        - wine-valve-git
        - lmms-git
        - swaylockd
        - uutils-coreutils-git
        - yrmcds
        - ode-011
        - qt5-wayland-compositor
        - molsketch
        - ros-melodic-convex-decomposition
        - sfntly-git
        - git-credential-kwallet
        - libst2205-git
        - sasmodels
        - nodejs-async
        - ros-jade-rosgraph-msgs
        - memcached-git
        - osec
        - nanosaur2
        - android-aarch64-libtiff
        - wut-git
        - kdevelop-python
        - rgss_script_editor-git
        - dxcompress-git
        - php81-openswoole
        - ktechlab
        - libotr-ng-git
        - palanteer
        - spitbol-git
        - latchbox-git
        - mingw-w64-libodbc++
        - iptux
        - nss-myhostname-separate
        - dovecot-libsodium-plugin
        - man-pages-ro-git
        - volume_key
        - mingw-w64-pteros
        - ros-indigo-camera1394
        - texmacs-svn
        - qtmobility
        - jellyfin-ffmpeg
        - tspc
        - hashrat
        - libvisual-plugins
        - psp-freetype2
        - orocos-rtt-omniorb
        - sh2_mp_ai_enabler
        - yaf
        - pan
        - fontdownloader
        - mingw-w64-unifdef
        - bluelog
        - hawktracer-git
        - newsbeuter2.8
        - cyclonedds
        - mips-harvard-os161-gdb
        - vul-git
        - android-aarch64-qt6-tools
        - qjson
        - simutrans-svn
        - stm32flash-git
        - xr-hardware-git
        - stepseq-lv2-git
        - pcrio-git
        - horseshoes-git
        - ezxml
        - randomgtk
        - arm-none-eabi-gcc53-linaro-alternative
        - indicator-keylock
        - ros-kinetic-kobuki-msgs
        - pg_icu_ext-git
        - vim-command-t
        - fbcat
        - usermount-git
        - cquery
        - digidoc4-client
        - ctwm
        - gpsim-svn
        - rofi-wayland-git
        - sinit
        - arch-diff
        - postgresql-semver
        - monero-git
        - ros-jade-actionlib-msgs
        - mongo_fdw
        - cef-minimal-obs-studio-browser
        - odb
        - php7
        - sirius-git
        - wlsunset
        - libosmo-sccp
        - multipass
        - climm
        - mono5
        - ignsdk-iot
        - packit
        - powerpc64le-linux-gnu-glibc-headers
        - rime-data
        - qfits
        - librsync-git
        - mingw-w64-opencolorio
        - rocsparse
        - cosmic-applet-host-git
        - pfrng-feeder
        - gtk-smooth-engine
        - arm-frc-linux-gnueabi-eglibc-headers
        - openav-sorcer-git
        - gnuit
        - st-syaoran-git
        - dsvpn
        - gerbil-git
        - libnpupnp
        - asus-nb-ctrl-git
        - multiload-ng-indicator-gtk3-git
        - gnonlin
        - xf86-video-glint
        - arma3-linux-launcher-git
        - automake-1.15
        - lovelock-backgrounds
        - pkg-config-git
        - resource-retriever
        - ros-ardent-ament-cmake-export-interfaces
        - ros-kinetic-laser-assembler
        - minase-git
        - kdsoap-qt4
        - distrho-extra-lv2-git
        - libmemcached-old
        - upower-silent-mouse
        - afb-client-git
        - reflac
        - nodejs-ipv6
        - openslp
        - xen-igvtg
        - man-pages-da-git
        - light-locker-settings
        - tuxpaint-cvs
        - ros-noetic-tf2-py
        - slang-verilog
        - nautilus-ext-git-git
        - aoetools
        - qgit-git
        - cockroachdb
        - edi-git
        - ros-kinetic-roslib
        - mesmer
        - gnome-2048-git
        - aspell-bg
        - evas_generic_loaders-fresh
        - pk-update-icon
        - brickstore
        - stsoundlibrary-git
        - cataclysm-dda-ncurses
        - spirv-llvm-translator
        - pcg-c-git
        - chromebook_keyboard_backlight_driver
        - bcwipe
        - dragonflydb
        - whatsappqt
        - bitfighter
        - pop-metacity-theme
        - evdev-right-click-emulation
        - samba-heimdal
        - sooperlooper.lv2-git
        - skewer
        - xe-guest-utilities
        - belr
        - lib32-gmp4
        - linux-mt
        - budgie-desktop-view
        - hyprland-autoname-workspaces-git
        - raxml
        - remindme
        - kicad-templates-git
        - erlang_ls-git
        - hdf5-java
        - kdeplasma-applets-playbar
        - pokemini
        - httpflow-git
        - k9copy
        - ecbuild-git
        - libhanjp-git
        - pjproject-git
        - qv2ray-plugin-ssr-dev-git
        - qobbar-git
        - ros-indigo-pluginlib
        - ignition-cmake-2
        - rock
        - bgs-kian-git
        - latin-words
        - libsonic-git
        - wargus-git
        - mummer
        - ansible-git
        - cvs2svn
        - raknet
        - ffmpeg-vaapi
        - cc-shim-git
        - scrot-slabua-git
        - mingw-w64-ptex
        - gdm-wayland-nvidia
        - ne-git
        - mutter-dynamic-buffering
        - smtpping
        - cmlex
        - hless-git
        - polychromatic-git
        - xpuz-arch
        - piglit-git
        - synfigstudio-dev
        - gens-gs-ii-git
        - redict-git
        - gtkada
        - libyder
        - ros-indigo-rocon-uri
        - gnome-shell-pomodoro
        - waybox-git
        - xfce4-panel-git
        - gnuradio-scopy-git
        - nextpnr-ice40-nightly
        - ros-melodic-pr2-msgs
        - failsafewm
        - sshexport
        - zzzfm-git
        - ibus-array
        - sft
        - openbox-patched
        - cpp-httplib-compiled
        - vosk-api
        - butter-git
        - pg2plplot
        - verynice
        - kfilebox
        - cue2pops-git
        - slideextract
        - snam
        - stunnel-systemd-git
        - allacrost-svn
        - superlu_mt
        - meshboard
name: BUILD-16
'on':
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-15
