jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - ps2-lua
        - gawk-abort
        - pango-anydesk
        - password-for-gnome-vala
        - fftw-quad
        - wmifinfo
        - nvhda-dkms-git
        - aggregate
        - openbor-git
        - lxpolkit-git
        - irstlm-git
        - xxoff-phonepi
        - mcg
        - st-jfchevrette
        - proton-ge-custom-native
        - crispy-doom-git
        - wlstream-git
        - libblocksruntime
        - sassafras-git
        - bpir64-mkimage
        - intel-media-driver-git
        - minder
        - ros-kinetic-clear-costmap-recovery
        - odr-audioenc-git
        - dosbox-gcc
        - guitar
        - lib32-libfluidsynth
        - xwxapt
        - openocd-riot-git
        - pam_abl-git
        - somoclu-git
        - kbtin
        - guitarix.vst-git
        - kgpg-git
        - ros-lunar-rostest
        - kmscon-patched-git
        - linux-ryzen-amd-staging-drm-next-git
        - kodi-devel-visualization-vsxu
        - drawxtl
        - florb-git
        - correcthorse
        - input-redirection-client-qt-git
        - mrg-git
        - crow-git
        - php73-apcu-bc
        - inviwo
        - gypsy
        - uefitool-git
        - kopano-webapp-fetchmail
        - bonanza
        - barnyard2-git
        - tilem
        - piscesde-wallpapers-git
        - moonwm-git
        - ros-kinetic-hardware-interface
        - coz
        - instead-git
        - ltrace-git
        - fortune-mod-newgirl
        - mysterium-node
        - gcc49-alternative
        - vcash
        - noaftodo-git
        - snapback
        - pacman-contrib-git
        - geekcode
        - rapidobj
        - igsc
        - libdbh2
        - torch7-dok-git
        - or-tools-java
        - gmat
        - gnome-control-center-noflatpak
        - polkit-qt4
        - nyu-hpc-opencl-demo-git
        - gzip-git
        - bashdb
        - htk
        - fishui-git
        - lilium-voyager-git
        - async_comm-git
        - shortcut-mapper-git
        - gosmore-svn
        - prboom-plus-um
        - nvidia-container-runtime
        - tiemu
        - menuconfig-git
        - libmimick-git
        - vstream-client
        - pdpmake-git
        - mingw-w64-qscintilla
        - luaexif
        - ros-noetic-bond-core
        - apparmor.d-git
        - lego
        - satyr
        - mingw-w64-zziplib
        - icu44
        - ros-jade-amcl
        - g4music-git
        - gcc49-multilib
        - fcitx5-git
        - xseticon
        - adw-gtk3
        - qtperf-git
        - ros-jade-xmlrpcpp
        - shader-slang
        - git-secret
        - protobuf-c-rpc-git
        - breeze-blurred-git
        - mingw-w64-ffcall
        - soks-git
        - grub2-git
        - zfs-linux-rt
        - crates
        - dhcpcd-ui-patched
        - cowberry-boot
        - intel-media-sdk
        - tuxpuck
        - emacs27-git
        - libretro-xrick-git
        - clan-git
        - gtest1.12
        - enigma-dev-git
        - lib32-freetds
        - smuxi-git
        - vdr-zaphistory
        - renderdoc
        - oss
        - hackup-git
        - quesoglc
        - libtomcrypt
        - stage-git
        - darkplaces-git
        - libreoffice-style-elementary-git
        - apertium-regtest
        - darkaudacity-git
        - linux-baby-vrt
        - ros-melodic-moveit-plugins
        - lib32-libpng12-git
        - ctags_as3_haxe
        - abiword-gtk2
        - liquid-dsp
        - colorpicker-keshavbhatt
        - sophia
        - rapidyaml-git
        - torque
        - yet-another-spotify-tray-git
        - wxlauncher
        - p2pool-git
        - librime-octagram
        - xplayer-plparser
        - mono-alt-csc
        - ossec-local
        - ros-kinetic-joy
        - spamassassin-spamc
        - wxgtk-git
        - ntbtls-git
        - thundersvm-git
        - mingw-w64-lilv
        - log4cxx-svn
        - umenu
        - knightos-kcc
        - nemo-ubuntu
        - materialx
        - spl-linux
        - redasm
        - go-for-it
        - zycore-c
        - forgottenserver-git
        - neateqn-git
        - azure-storage-cpp
        - gxneur-fresh
        - gladstone-drizztbsd-git
        - sticky
        - genchemlab
        - tundra2-git
        - cinelerra-cv-git
        - mingw-w64-solid
        - mipsel-ps2-elf-binutils
        - vdfuse
        - s-nail-git
        - xdg-utils-symlink-fix
        - ghc8.2
        - cairo-msg
        - tcpser
        - apertium-es-ast
        - cambalache
        - liblnk-git
        - sendxmpp-git
        - atlas-lapack
        - vche
        - kelbt
        - kronos-git
        - svt-vp9
        - ros-indigo-rosserial-server
        - xsatcom
        - retroshare-git-qt4
        - radv-git
        - plasma5-applets-mycroft-git
        - lxrad
        - libzorpll
        - getxbook
        - yarp
        - zebra
        - fix8-git
        - slurm-llnl-dev
        - pwsafe
        - chromium-dev
        - ignsdk
        - qxmpp
        - pamac-flatpak
        - mbusd
        - ros-indigo-rosgraph
        - vcflib-git
        - mgmt
        - dftbplus
        - php-inotify
        - kopano-webapp-webmeetings-git
        - lib32-json-glib
        - lame-svn
        - cubegui
        - floatybox
        - mp3fs-git
        - rezerwar
        - lib32-libpng12-minimal
        - ipt2socks
        - mapjson
        - qmqtt-git
        - mingw-w64-gst-plugins-ugly-git
        - mcabber-module-pep-hg
        - atoms-git
        - preserve
        - volnoti
        - ros-noetic-swri-console
        - mingw-w64-wxmsw
        - osux
        - ibam
        - wrt2pdf
        - hipfft
        - rankwidth
        - postgresql-src-beta
        - wlroots-full-git
        - ros-kinetic-slam-gmapping
        - mrifk-git
        - pam_u2f-git
        - mingw-w64-taglib
        - yasp-git
        - sslscan
        - clr-power-tweaks
        - lib32-pw-capture-git
        - energygraph
        - ginh
        - wargus-bzr
        - diet-ng
        - gr-ieee802-11-git
name: BUILD-65
'on':
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-64
