jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - chiaki-git
        - lib32-sdl-hg
        - mygestures-git
        - elements-git
        - padthv1
        - fvwm3
        - st-syntax-git
        - lusernet.app
        - wldbg-git
        - onscripter-jh-hg
        - touche
        - kcyberfoxhelper
        - lxmenu-data-git
        - ros-noetic-ecl-license
        - clt13-git
        - bootterm
        - wsjtx-svn
        - ros-melodic-summit-xl-localization
        - libfido2-full
        - ntop
        - mp
        - auto-st
        - qbittorrent-nogui
        - ewebkit
        - neoleo-git
        - lpc21isp
        - libmirisdr4-git
        - dslogic
        - carve
        - trash
        - mgetty-vgetty-git
        - mips64-linux-gnu-binutils
        - owo-git
        - ulex-git
        - dynamite
        - pure-stldict
        - josl
        - xss-lock
        - rttr
        - clang-prefixed-release
        - xneur-fresh
        - wingpanel-indicator-a11y-bzr
        - glsl-language-server
        - rt-tests
        - ros-indigo-ecl-devices
        - pseint
        - libappindicator-sharp
        - lib32-sdl2
        - x86_64-pc-freebsd13-binutils
        - ros-noetic-geometry2
        - shit-git
        - courier-imap
        - numactl-git
        - k8s-ldap-auth-git
        - libcamera-git
        - domoticz-git
        - gimp-light
        - rofi-blocks-git
        - ros-kinetic-ecl-eigen
        - collision-git
        - domterm-git
        - php71-igbinary
        - ros-melodic-franka-msgs
        - gromacs-2020-complete
        - zfs-utils-openrc
        - libblkio
        - rawhide
        - ros-kinetic-twist-mux
        - rrep
        - swea-git
        - pure-readline
        - kodi-devel-pvr-filmon
        - libssh-git
        - re2-hg
        - gnuradio-gsm-git
        - fuego-svn
        - center
        - autosshfs-git
        - bforartists
        - earthworm-svn
        - android-aarch64-kirigami2
        - ros-melodic-rosserial-python
        - linux-lts316
        - pulseaudio-dmitryvk-bluetooth-lag
        - vdr-neutrinoepg
        - sepolgen
        - aufs-with-headers
        - libopenrazer-git
        - pacredir
        - kdemultimedia-kmix-git
        - gloo-git
        - hhvm-git
        - pngrim-git
        - apngasm
        - netcfg-git
        - gvim-python3-noconflict
        - step-git
        - nvme-cli-git
        - busybox-static
        - atril-gtk2
        - msquic-release-git
        - budgie-desktop-git
        - lib32-libmd
        - grrlib-git
        - osquery-git
        - ros-melodic-theora-image-transport
        - arm-musl
        - lily
        - lib32-gtk-engine-equinox
        - cgoban
        - grv-git
        - ros-melodic-costmap-2d
        - ros-lunar-rosnode
        - libretro-fuse-git
        - knossos-git
        - esound
        - volk-git
        - hexchat-git
        - gradience-git
        - libiriverdb
        - switch-lan-play-git
        - hurrican-git
        - toxext
        - colord-kde
        - libreport-git
        - cry
        - wireplumber-git
        - vimpal
        - libtiff-git
        - protonhax-git
        - mailcrypt
        - hole2-git
        - hydrapaper-git
        - ponscripter-sekaiproject
        - avisynthplus
        - ccdille-git
        - valabind
        - caja-dropbox
        - qmmp-qsmmp-git
        - exabayes-mpi
        - vapoursynth-plugin-focus-git
        - gcompris-qt-git
        - vicare-scheme-git
        - gbalzss
        - banner-viewer
        - hdr-plus-git
        - lsl-registration
        - tahoma2d
        - fortune-mod-torchwood
        - libfm-gtk-git
        - bootchart2
        - nn
        - wayfire-git
        - fondo-git
        - tig-git
        - amdctl
        - graceful-platform-theme
        - libav-no-libs-git
        - emacs-pdf-tools-git
        - zenith
        - ros-melodic-roslint
        - patchrom
        - 2048-qt
        - ros-melodic-mk
        - sgp4-git
        - pgpointcloud
        - neix-git
        - astromatic-swarp
        - ptex
        - scram
        - php72-igbinary
        - apricots
        - fabariagest
        - flameshot-git
        - myrrdin-mc-git
        - shadowsocks-libev
        - cntk
        - ambertools
        - sqlitecpp
        - numlockl
        - lib32-libgnome-keyring
        - minnow-git
        - firebird-superserver
        - hasher-priv
        - gdcc-git
        - elementary-wallpapers-git
        - purple-oicq
        - lib32-intel-tbb
        - salome-medcoupling
        - iortcw
        - mpd-light-pulse
        - md4c-git
        - pnmixer-git
        - postgresql-zson-git
        - webkitfltk
        - rshell-git
        - mingw-w64-cgns
        - libarsal-git
        - android-aarch64-x264
        - nginx-quic
        - mingw-w64-gst-editing-services-git
        - scim-pinyin
        - zmqpp-git
        - qsubber-git
        - uuterm-svn
        - ps2-libpng
        - minimap2-git
        - rsync-reflink-git
        - ros-kinetic-rqt-srv
        - budgie-mailnag-applet
        - xnec2c
        - fcitx5-pinyin-zhwiki
        - infineon-firmware-updater
        - curecoind-git
        - maui-strike-git
        - mate-indicator-applet
        - ros-jade-move-base
        - gloom
        - qpitch
        - containerd-git
        - harminv
        - qcad-git
        - zsdx
        - shtool
        - feedreader-beta
        - beegfs-common
        - php56-kolabformat
        - babeld
        - zelda-xd2
        - hcc
        - pyopencl-headers-git
        - cockpit
        - ros-melodic-nodelet
        - woodpecker-cli
        - mingw-w64-qt5-sensors
        - nwg-launchers-git
        - dlt-viewer
        - vapoursynth-plugin-msmoosh-git
        - ocaml-extlib
        - sqlite2
        - ezquake-git
        - ms-sys
        - tuxpaint-stamps-cvs
        - apertium-zlm
        - emacs-evil-surround-git
        - m68k-elf-toolchain
        - tinywm-git
        - pmemd
        - fwupd-git
        - libunity-misc
        - ssr
        - yubikey_switch
        - nginx-mod-ct
        - vobsub2srt-git
        - mingw-w64-kvazaar
        - directfb2-eglgbm-git
name: BUILD-137
'on':
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-136
