concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - qmlkonsole-git
        - nautilus-folder-cleaner-extension-git
        - coreshot
        - wordplay
        - a7xpg
        - ifetch-git
        - qlcplus-qt5
        - coil64
        - emilua
        - arcint-gtk-theme-git
        - orthanc-plugin-dicomweb
        - ros-noetic-nodelet-tutorial-math
        - lib32-glib2-git
        - opencpn-plugin-weatherrouting
        - ocamlbricks-trunk
        - razer_chroma_drivers-git
        - grip-eject
        - libopenaptx-git
        - postgresql16
        - mingw-w64-protobuf
        - xow-git
        - coreuniverse-git
        - npth-git
        - sex
        - ros-lunar-pcl-conversions
        - kdevelop-go
        - skopeo-git
        - simlib
        - rr
        - cups-nosystemd
        - truecrypt
        - albert
        - lxdm-consolekit
        - labplot-kf5
        - piscesde-settings-git
        - ibus-bamboo
        - qjoypad-panzi-git
        - libgaiagraphics
        - lib32-libttf2
        - gensystray-git
        - cortex
        - playmyvideos-git
        - odin-src
        - soundpipe-dev
        - linux-rc
        - doomseeker-hg
        - ocaml-psmt2-frontend-git
        - aurutils
        - osvr-tracker-viewer-git
        - bootableusb
        - azmq-git
        - xde-helpers
        - linux-air-combat
        - cxxtools-git
        - bluedevil-git
        - scopy-git
        - setcolors-git
        - os-251
        - musescore3
        - highwayhash
        - 3dslicer
        - fortune-mod-arresteddevelopment
        - f32-backgrounds-fedoradesign
        - openfwwf
        - mplayer-vaapi
        - avarice-git
        - chkservice-git
        - doomrunner
        - libusb-nosystemd
        - tpm2-totp
        - mingw-w64-libuecc
        - irker
        - memleax
        - antimicro-qt4
        - hex-git
        - spark-rc
        - plata-theme
        - xed-git
        - cpptoml
        - amule-remote-git
        - gnaural
        - ros-melodic-ur-msgs
        - nitroshare
        - fna3d-git
        - tbe
        - kaption
        - hws-git
        - sandbox
        - glade-gtk2
        - randomgtk-git
        - qtscrob
        - venom-git
        - mosml
        - kubectl-trace-git
        - kdeplasma-applets-plasma-crystal-git
        - libasr-git
        - lib32-nocache
        - libpurple-carbon-git
        - ugtrain-git
        - qt5-styleplugins-nogconf-git
        - funyahoo-plusplus-git
        - findfileconflicts
        - php74-oci8
        - referencer
        - imgbrd-grabber-git
        - midori-gtk2
        - lib32-llvm-stable
        - goverlay
        - termkeyboard-git
        - ros-noetic-bond
        - fdmf
        - mingw-w64-icu5x
        - goldendict-qt5-git
        - artha
        - graywolf
        - rl78-elf-newlib
        - xxiivv-orca-git
        - pantheon-gala-git
        - arm-none-eabi-gcc64-linaro-alternative
        - redshift-qt
        - lib32-libtiff3
        - lib32-oxygen-gtk3-git
        - dispmanx_vnc
        - trigger
        - chromeos-vboot-reference-git
        - pugixml-shared
        - lockjaw
        - citus
        - jack-xruntotal-git
        - tinyfecvpn
        - cluttermm
        - ros-indigo-rocon-service-pair-msgs
        - nbwmon
        - repman-git
        - delaycut
        - obs-linuxbrowser-git
        - paleta
        - terminalgraphics
        - backintime-bzr
        - qabc
        - fstar-ulib
        - ros-melodic-ivcon
        - ffmpeg063-static
        - mpd-m4afix
        - raceintospace
        - xfwm4-gtk2
        - vcsh-git
        - dwl-git
        - feedgnuplot
        - gcc-x32-seed
        - meep
        - mod_gnutls
        - chigraph
        - cpuminer-opt
        - sdformat
        - linux-xanmod-cacule-uksm
        - openvas-cli
        - zplugins.lv2-git
        - cnoor-git
        - mumps
        - aseprite
        - cdate
        - gnash-git
        - mcwm
        - qmapshack-hg
        - lxqt-runner-git
        - tdesktop-x64
        - hrpsys-base
        - lxappearance-gtk3
        - hobbits
        - cs-signal-git
        - tau-editor
        - lalsuite-git
        - icu59
        - gtk-bluecurve-engine
        - moc-pulse
        - librenms
        - xash3d-hlsdk
        - gpxviewer-bzr
        - xr-video-player-git
        - protobuf3-coex
        - libevbuffsock-git
        - goocanvas3
        - lxrandr-gtk3
        - rftg-keldon
        - fabtests
        - mingw-w64-gdcc
        - xkeyboard-config-git
        - qt5-wayland-hybris
        - just-js
        - swcdb-lib-thrift
        - fastbuild
        - emacs-speechd-el-git
        - cutefish-calculator-git
        - mingw-w64-pixman
        - scsi2sd-v6-git
        - ros-melodic-rostime
        - multimc5-git
        - fortune-mod-darkwingduck
        - singular4
        - downgrader-git
        - qmmp-1
        - hitch
        - stdin-to-modbus-shm
        - htcondor
        - apk-editor-studio
        - systempreferences
        - feelpp
        - libroxml
        - gstm-gtk2
        - cawbird-12
        - unp64
        - gtirb-git
        - fcitx5-pinyin-zhwiktionary-git
        - unity-test-git
        - fastrandom
        - liblinear-multicore
        - valhalla-tmp-patch
        - beegfs-storage
        - ts-bugreport
        - easy-rsa-old
        - mingw-w64-openh264
        - plasma5-applets-feedreader
        - onewireviewer
        - deepin-pygtk
        - movit-git
        - mingw-w64-qt5-base-nostatx
        - arcus-beta-git
        - f3-test
        - cpp-jwt-git
        - dee
        - sysfsutils-git
        - vigra-git
        - npiano-git
        - ros-jade-move-slow-and-clear
        - avrm-ds1307-git
        - cronie-selinux
        - csync
        - iwd
        - ros-jade-roslz4
        - libpeas-git
        - vicare-scheme
        - abtransfers
        - xsnap
        - trickle-pipe
        - eprosima-fast-dds-statistics-backend
        - nheko
        - kodi-addon-game-libretro-fbneo
        - friking-shark-git
        - epson-inkjet-printer-201106j
        - vhdtool-git
        - php56-ssh
        - kdeplasma-applets-gmailfeed
        - synce-rra
        - aarch64-linux-gnu-pkg-config
        - ignition-fuel_tools-4
name: BUILD-92
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-91
