jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - libschrift
        - postgresql-uint
        - tatham-utils
        - qtox-git
        - vramsteg-git
        - terrafs-git
        - memo-git
        - kcm_webcam
        - ros-jade-image-transport-plugins
        - boost-di-git
        - meld-dev
        - taipan
        - libdri2-git
        - sres-git
        - geany-plugins-git
        - lib32-popt
        - jj
        - audacious-usf-plugin-git
        - o20-git
        - pekwm-menu
        - reredirect-git
        - davfs2
        - monopticon
        - halibut
        - most-git
        - iboview
        - ros-jade-tf2-msgs
        - aspell5-ro
        - tiobench
        - soil2-git
        - ros-kinetic-roslaunch
        - scnlib
        - heekscad-git
        - qirssi
        - gala-layoutpw-plugin
        - tinyfugue-git
        - pencil2d-git
        - nanotts
        - tupitube.desk
        - sccs
        - kcm-lookandfeel-standalone-git
        - posterazor-qt5
        - certmonger
        - fanficfare
        - aarch64-linux-gnu-ncurses
        - libluasandbox
        - nsfminer-cuda
        - libgpiod-git
        - duff
        - pgpdump
        - opencv-cuda
        - hip-hcc
        - wmsm.app
        - libcurl-compat-fix
        - plymouth-git
        - uboot-odroid-c4
        - qt5-udev-git
        - ent
        - intertext-editor
        - structured-haskell-mode-git
        - scrm
        - kunitconversion-git
        - mueller-dict
        - xorg-xdbedizzy
        - gxi-git
        - ros-kinetic-camera-info-manager
        - xli
        - quickdocs
        - polished-map-git
        - goqat
        - gnome-klotski-git
        - tcpkali
        - xf86-video-trident
        - linux-cdown-mmots-git
        - hydrogen-theme
        - atom-bleeding
        - lib32-libbs2b
        - libptmalloc3
        - xsnow-comp-patch-git
        - p3wm-git
        - lib32-libnotify
        - ros-indigo-robot-state-publisher
        - harfbuzz-minimal-git
        - fsearch-git
        - bdinfo-git
        - armagetronad-snapshot
        - etrophy
        - app-icon-preview
        - esptool2-git
        - mosh-sshagent-git
        - netgen-git
        - rtrlib
        - kodi-devel-screensaver-pyro
        - scythe-git
        - bicon-git
        - i4oled-gui-git
        - cpuminer-multi-allium-git
        - glrpt
        - ima-inspect
        - courier-unicode
        - openuru-moss
        - mate-icon-theme-faenza-1.15-gtk3
        - thunar-gtk2
        - jobqueue
        - cockatrice-server-git
        - libxml2-linenum
        - loki-core-git
        - libgnome
        - theft
        - yakuake-git
        - minissdpd
        - dab-scanner
        - dwarfs-git
        - japokwm-git
        - cloud-utils-git
        - libhydrogen-git
        - sdlmame-0137
        - picom-ibhagwan-git
        - xfce4-sensors-plugin-nvidia-hddtemp_through_netcat-current
        - imagemagick-full-git
        - llvm39-provides
        - onehouronelife-latest
        - fgx-qt5
        - evince-git
        - bastet
        - evdi-pre-release
        - argonone-c-git
        - ladish
        - spark-store
        - rectify-jpg
        - fldiff
        - filet-git
        - wlrobs
        - lib32-sdl12-compat-git
        - guile-2.2
        - writer-git
        - flowee-git
        - quickbms
        - calcelestial
        - libx32-libgpg-error
        - openra-wts-git
        - snoopy-logger
        - macutils-git
        - opencv3-opt
        - libretro-nestopia-git
        - mingw-w64-poppler
        - opencpn-plugin-celestial-navigation
        - libpassphrase
        - postgresql13
        - xdg-utils-no-open
        - mingw-w64-kiconthemes
        - nemesyst-git
        - opm-upscaling
        - yad
        - slim-defaultsession
        - lhapdf
        - rocfft
        - qdolist
        - rc-duff-git
        - libplatform-git
        - pacman-ezamlinsky-git
        - libwnck+-git
        - ros-noetic-hardware-interface
        - njl.lv2-git
        - video_entropyd
        - vkquake
        - rice3d
        - libcurve
        - libxfce4ui-gtk2
        - chromium-beta
        - libabigail-git
        - mptp
        - arm-linux-gnueabihf-glibc
        - gcc-xtensa-esp32-elf-git
        - jfbpdf
        - spl-git
        - mseed2ascii
        - croco-welcome-git
        - dune-functions
        - icebreaker
        - gromacs-5.0-complete
        - my-spl-linux
        - gtkhash
        - openmrac
        - golly
        - pidgin-nudge-svn
        - mphidflash
        - hheretic
        - ros-kinetic-control-msgs
        - zyn-ext-gui-lv2
        - ros-kinetic-bond
        - arm-none-eabi-newlib-linaro-git
        - metadata-cleaner1
        - gklib
        - sbpl
        - vdr-remoteosd
        - krb5-minimal-git
        - xmltv
        - gnome-shell-extension-alphabetical-grid-extension-git
        - vdr-softhdcuvid
        - scrub
        - linux-vanilla-selinux-mainline
        - gnomint
        - mingw-w64-qtkeychain-qt5
        - ros-kinetic-graph-msgs
        - libx32-libxdmcp
        - instamenu-schemas
        - mkbootimg-git
        - netctl-gui
        - dcc
        - mtafsir
        - nsbox-edge-git
        - fractorium-git
        - offlineimap-git
        - libbsd-git
        - eom-dev
        - telegram-desktop9
        - featherpad
        - gr-adapt-git
        - libviper
        - paintball-party-2
        - croco-settings-manager-git
        - opentaxsolver-2020-svn
        - linux-lts49
        - linux-nitrous-fire-git
        - alex4
        - hyp2mat-git
        - ativayeban-git
        - libhaiku
        - gridmgr-git
        - or1k-elf-gcc
        - lua-mpack-git
        - gawk-timex
        - arm-linux-gnueabihf-glibc-headers
        - nginx-mainline
        - xpacman
        - wmpower
        - snowcrash
        - qt5-webchannel-595
        - pacman-src-git
        - xf86bigfontproto
        - ndefpack
        - vapoursynth-plugin-matchhistogram-git
        - gnome-shell-extension-panel-corners-git
        - ros-indigo-srdfdom
        - jesus-git
        - llvm37-split
        - upnp-player-qt
        - sam
        - plctool-plugins-git
        - plasma5-applets-nx-audio
        - libpamac-full
        - gnome-shell-extension-topicons-redux
        - libmupdf-pymupdf
        - solbuild-git
        - minipro-logictest-git
name: BUILD-52
'on':
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-51
