concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - redkite
        - armory-goatpig-git
        - mingw-w64-gperftools
        - ros-indigo-urdf-tutorial
        - xsystem35
        - ros-indigo-turtlebot-capabilities
        - mlpack
        - ocaml-javalib
        - chromecast-tools-git
        - i3lock-fancier-rapid
        - libgnomeuimm
        - ggmud
        - asymmetricfs-git
        - meteodata-git
        - ntp-refclock
        - mingw-w64-sdl2
        - libquicktime-git
        - mod_fcgid
        - battmon
        - xf86-video-dummy-with-vt
        - sharexin
        - gnome-shell-extension-bluetooth-quick-connect-git
        - mazemaze-git
        - ros-ardent-ament-cmake-pep257
        - spl-utils-linux-lts
        - okular-frameworks-git
        - insight-toolkit4
        - socat2
        - waimea-git
        - ros-melodic-ecl-console
        - declarative-plasmoids
        - alpine-apk-tools
        - curl-http2-git
        - mod-midi-merger-git
        - astromatic-scamp
        - emacs-editorconfig-git
        - libjpeg6
        - libibverbs
        - myhtml-git
        - crun-python-bindings
        - qpress
        - marco-gtk2
        - ros-ardent-image-geometry
        - zopflipng-git
        - ghdlsynth-beta-git
        - ros-indigo-rocon-app-manager
        - crash-git
        - textosaurus-git
        - checkpolicy
        - asap
        - intel-caffe-git
        - libksysguard-git
        - yoda-git
        - sfizz
        - mitsuba2-git
        - bmon-git
        - openchange-git
        - graftcp
        - ignition-fuel_tools-1
        - zfs-utils-git
        - libpamac-full-dev
        - audacity-wxgtk2
        - gereqi-git
        - kde-thumbnailer-odf
        - qprompt
        - xfce4-datetime-plugin-git
        - gst-plugins-rs-git
        - psp-pthreads-emb
        - ogmrip-flac
        - freesynd-svn
        - mom
        - nettle7
        - deepin-pw-check-git
        - megaglest-git
        - azpainter
        - guile2.0
        - freeserf
        - libretro-pcsx-rearmed-git
        - compiz
        - opensnitch-ebpf-module
        - ros-jade-stage
        - kde-thumbnailer-gimpresources
        - hpp-fcl-git
        - kactivities4
        - hyprland-nvidia-screenshare-git
        - pplatex-git
        - gn-m87
        - benelib
        - raine
        - cpp-taskflow-git
        - govpn
        - flvlc
        - networkmanager-fortisslvpn-peerdns
        - libcrossguid-git
        - resvg-qt
        - bsf-git
        - cs-string
        - php73
        - aftp-server-git
        - libretro-beetle-saturn-git
        - mimic-git
        - libcontacts
        - subberthehut
        - gnome-shell-extension-do-not-disturb
        - lynx-current
        - polyvox-git
        - joy2key
        - astc-codec-git
        - tango-idl
        - cubway-git
        - ru-tts-git
        - l-smash
        - reqrypt-client-git
        - denarius-git
        - ros-kinetic-ros-comm
        - gtm
        - eliot
        - gnome-zoomer-git
        - minitimer
        - deepin-launcher-git
        - glew1.6
        - ros-indigo-rosbash
        - gnupg-clavator
        - xgetres
        - plasma5-applets-playbar2
        - obs-vkcapture
        - liri-qtintegration-git
        - mingw-w64-libwebsockets
        - nccmp
        - java8-openjdk-shenandoah
        - fvwm-patched
        - warp-share-files
        - ros-lunar-kdl-parser
        - include-what-you-use-clang13-git
        - openssl-git
        - ros-melodic-variant-msgs
        - dwm-supermario9590-git
        - brutalchess
        - quteqoin-git
        - sdl2_image-minimal-git
        - pantheon-notifications-git
        - notekit-clatexmath-git
        - libpamac-flatpak
        - pstotext
        - ros-jade-pointcloud-to-laserscan
        - tinyfugue-patched
        - vmaf
        - oggfwd-bzr
        - makedepf90
        - libstorj
        - od-automotive-miniature-git
        - ros-ardent-rosidl-cmake
        - lxterminal-gtk2
        - krita-next
        - ksvnupdater
        - dmsdos-git
        - switchboard-plug-notifications-git
        - libcd
        - crrcsim-hg
        - curl-minimal-git
        - ipband
        - pcsx2
        - pdl2ork-touchosc-git
        - mingw-w64-gdb
        - libtiff4-git
        - mecab-ipadic-git
        - taucs
        - qwt5
        - mips64-elf-gdb
        - broadcom-wl
        - mingw-w64-luajit-2.1
        - qmasterpassword
        - omniorb
        - linux-mini
        - pamixer
        - c-capnproto-git
        - mandelbulber2-git
        - linux-pds
        - nihdb
        - ros-noetic-rqt-py-common
        - photorecover
        - jhbuild-git
        - choria
        - zabbix-proxy-sqlite-lts
        - next-prayer
        - qt-solutions-git
        - man-pages-uk-git
        - boxfs2-static-git
        - ax25-apps
        - rocket-git
        - vvenc-git
        - libgee-git
        - cppfs-git
        - android-aarch64-qt6-multimedia
        - libshm_arena
        - gdmap-gtk3-git
        - modemmanager-git
        - odr-dabmux-git
        - xscreensaver-arch-logo
        - android-aarch64-qt6-serialbus
        - ros-noetic-ecl-concepts
        - esev-git
        - expac-git
        - trustedgrub2-git
        - armv8l-linux-gnueabihf-gcc-stage1
        - sleuthkit-java
        - gnome-keyring-wo-gpg
        - mid2agb
        - gr-ieee802-11
        - revbayes-git
        - vkcpp
        - wine-vulkan-git
        - sdl2-git
        - hyprpicker-git
        - proxmark3gui-git
        - icu71
        - mmsd-git
        - bayescan
        - lxc-templates
        - lunar-calendar
        - libpseudo
        - xaxaxa-vna-git
        - jsonc
        - jellyfin-ffmpeg5
        - wyrd-git
        - ocaml-fileutils-yypkg
        - ros-jade-rqt-service-caller
        - telegram-desktop-dev
        - urlview-xdg-git
        - amalthea-dmd
        - phyml-beagle
        - account-plugins
        - polymc-qt6-git
        - feather
        - kasumi-cvs
        - domjura-git
        - hhexen
        - wayland-info-git
        - taglib-sharp-git
        - ros-indigo-octomap-msgs
        - ros-kinetic-base-local-planner
        - libva-vdpau-driver-shadow-nvidia
        - sqlite-fts3-parenthesis
        - ros-noetic-trajectory-msgs
        - suphp
        - ide65xx
        - fortune-mod-2brokegirls
        - amb
        - nbtool-git
        - vocoder-jack
        - gmrender-resurrect-git
        - sir
        - tanka-git
        - babl-git
        - libmpris2client
        - powerpc64le-linux-gnu-glibc
name: BUILD-19
'on':
  workflow_dispatch: ''
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-18
