concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - mpd-sidplay
        - wxwidgets-dev-light
        - gmqcc-git
        - clight
        - vcvrack
        - linux-odroid-c4
        - mamepgui
        - lm4flash
        - aarch64-linux-gnu-glib2
        - libutf8proc-git
        - ros-melodic-mbf-utility
        - tic-80-git
        - lib32-libvisual
        - pkcs11-helper-1.11
        - guile4emacs-git
        - qdldl
        - thrift-0.9
        - apidb-postgresql
        - retrosmart-kvantum-theme
        - lcms2-git
        - cubew
        - ros-kinetic-robot-localization
        - gopherus-svn
        - plasma5-applets-kargos-git
        - bitcoin-taproot-lot-true-uasf
        - heifthumbnailer
        - compiler-rt-stable
        - libbitcoin-server-git
        - psani-profi
        - libroboint
        - gnome-shell-extensions-wifiqrcode-git
        - apg
        - solanum-ircd
        - scrollback-git
        - csnobol4
        - ros-noetic-roscpp-serialization
        - ypbind-mt-git
        - ifmetric
        - coventry
        - redditgtk-git
        - monkeysphere-git
        - postgresql-ip4r
        - ros-melodic-viz
        - openmodelica-omnotebook
        - argparser-python
        - ignition-math
        - mingw-w64-libcuckoo-git
        - ros-noetic-mbf-utility
        - redis-desktop-manager
        - libx32-libgcrypt
        - retrosmart-aurorae-themes
        - homegear-enocean-git
        - ctpp2
        - grail
        - linux-pf-nodocs-git
        - bitlbee
        - telepathy-qt5-git
        - asymptote-git
        - talkatu-hg
        - btop-git
        - cyrus-imapd-ldap
        - ibus-bamboo-git
        - amarok-git-ffmpeg4
        - libtcod-hg
        - ros-noetic-diagnostic-analysis
        - sidplay2-libs
        - fcitx5-bamboo-git
        - hdf5-openmpi-java
        - glbinding-git
        - mycroft-gui-git
        - redi-search
        - xembed-sni-proxy-white-git
        - reed
        - vncproto
        - phpredis-git
        - lib32-luajit
        - mdbtools
        - mingw-w64-xlnt-git
        - ros-noetic-laser-filters
        - datadraw-git
        - ukey2-git
        - roger-wallet-git
        - clightd-no-ddc
        - tpm-tools
        - e2guardian
        - php-ds-git
        - ros-noetic-ros-base
        - radare2-bindings
        - openfst-kaldi
        - pokerth
        - photoflare
        - trnascanse
        - topmenu-gtk
        - geany-modeline-git
        - somoclu
        - xfvnc-git
        - lib32-libomxil-bellagio
        - skroll
        - openmsx-git
        - sni-qt-patched-git
        - ros-melodic-franka-example-controllers
        - oras
        - heimdal
        - comgt
        - gnome-firmware-updater-git
        - duo-unix
        - slock-abh15h3k
        - epstool
        - price.app
        - raxml-light
        - icinga
        - aerc-rjarry-git
        - supercollider-vstplugin-git
        - fortune-mod-thenewsroom
        - qmail-qfilter
        - immudb
        - pygobject37
        - mod_fcgid-legacy
        - solanum
        - freedv-gui
        - midisharelight-git
        - petsc-maint
        - pinentry-rofi
        - valsort
        - libcdio-git
        - exaile
        - lesstif
        - libvmi-git
        - zelvici-git
        - nuvola-app-yandex-music-git
        - epson-inkjet-printer-k100-k200-series
        - liblcfg-git
        - blackbox-tools-git
        - sst
        - distrho-lv2-git
        - libtiff-lerc
        - kscreen-git
        - gtkparasite-gtk2
        - jdupes
        - ola
        - ros-melodic-openslam-gmapping
        - libdecaf
        - ros-noetic-ecl-time-lite
        - ros-noetic-turtlebot3-slam
        - ros-lunar-desktop
        - xgrep
        - pacdep
        - nvidia-vulkan-developer-beta
        - ros-indigo-rocon-bubble-icons
        - mingw-w64-qt5-quick1
        - atf
        - angband-ncurses
        - unnethack-git
        - respeqt-git
        - fd
        - lib32-apitrace-git
        - ros-noetic-roscpp-tutorials
        - ros-noetic-hector-gazebo-plugins
        - pgjwt-git
        - nx-kwin-decoration-git
        - srmd-ncnn-vulkan-git
        - vegastrike-engine-git
        - ros-ardent-sensor-msgs
        - estd
        - mingw-w64-wineditline
        - spacecadetpinball-git
        - libqb-git
        - lib32-proxychains-ng
        - i686-elf-binutils-git
        - thiefmd
        - lm32-elf-gcc
        - ros-kinetic-costmap-2d
        - xbae
        - audio-sharing
        - vcvrack-vult-git
        - endeavour
        - aarch64-linux-gnu-libffi
        - webcit
        - msoffice-crypt-git
        - tfmigrate
        - ncdu2
        - pfsshell-git
        - ros-indigo-kobuki-rapps
        - libidn11
        - openssl-tpm-engine
        - gnotepad
        - cwebx
        - avs-alexa-sampleapp
        - kopano-webapp-files
        - mu
        - geomview
        - array-hash
        - j4status-git
        - vmp
        - libretro-mame2015-git
        - telepathy-hanging-git
        - tuhi-git
        - lib32-dumb
        - nginx-libressl
        - libindi-eqmod
        - opencolorio1
        - gnupg-git
        - obs-studio-vaapi
        - openimagedenoise-git
        - poedit-git
        - fi
        - nvidia-bridge-pl
        - git-git
        - setserial
        - obs-studio-git-with-browser
        - glee
        - co2mon-git
        - s6-portable-utils
        - tome4-beta
        - instantbird
        - mash-sh
        - txt2epub
        - deepin-control-center-git
        - mingw-w64-gfsm
        - ros-indigo-joint-state-controller
        - xorg-server1.12
        - pro-bitcoin-git
        - kodi-devel-libplatform
        - socket-relay
        - bitcoin-cash-node-qt
        - open-adventure
        - libcello
        - mudmagic
        - vibrantx-git
        - netkit-telnet-ssl
        - opentimer
        - nsf
        - ecdsatool-git
        - strawberry-full-git
        - ros-melodic-navigation
        - libdispatch-git
        - acarsdec
        - dsview
        - hciattach-rpi3
        - plzip
        - pzxtools
        - libkolab-frameworks-git
        - dtc-git
        - lib32-csfml
        - xdg-utils-mimeo
        - lib32-gst-plugins-base
        - linux-enablezfsbuild
        - highmoon
        - xware-desktop-git
        - qoi-git
        - yetris
        - ttm
        - wla_dx
        - mate-desktop-gtk2
        - megatools-dev-git
        - ros-indigo-rqt-gui-cpp
name: BUILD-22
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-21
