concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - ros-lunar-std-msgs
        - chewing-editor-git
        - aarch64-linux-gnu-readline
        - datamaps-git
        - pep-jni-adapter-git
        - caffe-cudnn-slim-git
        - drafting-git
        - pyflame-git
        - ttf2png
        - xevdevserver
        - today
        - pure-pandoc
        - cgal-headers
        - lsi-openpegasus
        - firefox-esr-ublock-origin
        - pulseaudio-module-xrdp-git
        - tntdb-git
        - qt5-base-git
        - cairo-minimal
        - libcap-ng-minimal-git
        - tellus-git
        - cs-paint-git
        - netsoul-purple-git
        - nginx-rtmp
        - ros-lunar-std-srvs
        - vtm-git
        - dune-istl
        - kvirc4-git-nokde
        - jacal
        - mucharmap-git
        - imlib2-webp-git
        - gmmlib-git
        - emacs-native-comp-git-enhanced
        - lwtools
        - ros-melodic-executive-smach
        - rem
        - nyancoin-daemon
        - osux-tools
        - ros-indigo-bondcpp
        - torchat2-libpurple-git
        - ros-melodic-moveit-ros-manipulation
        - libpam-x2go
        - flyby-git
        - devlauncher-git
        - firenzina
        - gudev-sharp
        - android-aarch64-qt6-quick3d
        - lib32-sdl-openglhq
        - gnucap-models
        - corefreq
        - libclsp
        - ros-indigo-resource-retriever
        - silentarmy-git
        - gpsshogi-svn
        - ros-noetic-cpp-common
        - go4
        - libadios-git
        - libusbpp-hg
        - kernel-headers-musl-aarch64
        - avldrums.lv2
        - rclone-browser
        - invedit-git
        - mate-terminal-dev
        - lib32-libelf-minimal-git
        - sugar-toolkit
        - libgcrypt15-minimal-git
        - parcittox-svn
        - ipad_charge-git
        - highs
        - neomutt-backends
        - gnome-shell-pomodoro-git
        - scrcpy
        - ros-kinetic-robot-state-publisher
        - nvidia-340xx-lts
        - httrack
        - lib32-mesa-noglvnd
        - avldrums-lv2-git
        - gnome-shell-extension-dash-to-dock-gnome41-git
        - unison-240-compat
        - gnome-shell-extension-sound-output-device-chooser-git
        - fair-coin
        - ros-kinetic-rosbag-migration-rule
        - naxalnet
        - libretro-uae-git
        - android-x86-x264
        - gkrellmpager
        - ecrire-git
        - qt58
        - gpick-git
        - raiblocks-git
        - pgtap-git
        - tde-tqt3
        - denise
        - usbutils-git
        - i4oled-gui
        - haxima-git
        - ros-kinetic-camera-calibration-parsers
        - xnafiledialog-git
        - rnaz
        - akira
        - mingw-w64-paraview56
        - ostree
        - spreed-webrtc-server
        - cloudabi-utils
        - paraview-salome
        - mrouted
        - cutepeaks
        - kbdd-git
        - amusiz
        - bonita-bpm-community-bin
        - sway-no-strip-override-git
        - pmars
        - onscripter-en
        - libx32-yajl
        - adanaxis-gpl
        - clasp-cl-git
        - android-armv7a-eabi-xz
        - rftg
        - batmon.app
        - tangram
        - mailfromd
        - soprano-qt5-git
        - gamemode
        - gnome-flashback-compiz
        - qimgv
        - mips64el-linux-gnu-gdb
        - ros-indigo-teleop-twist-keyboard
        - yaml-cpp-git
        - automoc4
        - vnstatui
        - luacheck-git
        - d9vk-winelib-git
        - opencryptoki-git
        - hockeypuck-git
        - userbindmount-git
        - html2text-with-utf8
        - gtk-vnc-gtk2
        - physlock-git
        - ros-noetic-image-transport
        - ros-noetic-hdl-graph-slam-git
        - brainparty
        - kdialog-git
        - relabsd-git
        - glslc-git
        - vkvg
        - mesa-aco
        - wingpanel-git
        - xorgxrdp
        - qpwgraph
        - kdeplasma-applets-gmailfeed-git
        - mldonkey-ed2kad-daemon-git
        - eagle-git
        - coreshot-git
        - johnny-git
        - lib32-gstreamer0.10-base
        - adplug-git
        - blender-2.82-git
        - powerpc64-linux-gnu-glibc-headers
        - qmpdclient-qt5
        - mingw-w64-freetype2-static
        - fabricversions
        - messenger-gtk
        - lunchbox
        - mfoc-hardnested-git
        - vcsn-git
        - fbpanel-svn
        - libao-jack
        - mingw-w64-libsass
        - seexpr-qt5
        - glitchlock
        - soundkonverter-dark-theme-git
        - ros-melodic-roslang
        - kismet-plugins-restricted
        - koio
        - ros-indigo-rocon-app-utilities
        - ros-jade-mavros
        - upwork-latest
        - scraw
        - catimg
        - evolution-rss-git
        - st-jellybeans
        - libtheora-ptalarbvorm
        - morituri-git
        - bake-sl-git
        - mange
        - snmp_exporter
        - mathcomp-git
        - libovr_nsb-git
        - ksnip-git
        - evince-browser-plugin
        - yaneuraou-nnue-avx2
        - sis
        - etlegacy-git
        - pcc-git
        - cava
        - lib32-lilv
        - linux-identd
        - capnproto-java
        - tapclean-cvs
        - spacevecalg-git
        - clockd
        - dhtest-git
        - djgpp-djcrx-cvs
        - vim-gdbmgr
        - isync-git
        - ros-lunar-genmsg
        - poppler-git
        - kweather
        - rdis-git
        - gnome-cosmic-desktop-widget-git
        - perwindowlayoutd
        - torch7-xlua-git
        - yaplog-git
        - wmfs2-git
        - cmkr-git
        - amgx
        - mingw-w64-kitemviews
        - maxmod
        - faustlive
        - gmenu-dbusmenu-proxy-git
        - smplayer-qt5-svn
        - clp-git
        - ros-melodic-tf2-geometry-msgs
        - trickle-git
        - naikari-git
        - yuview-git
        - toit-git
        - jellyfin
        - ros-indigo-eigen-conversions
        - nblood-git
        - touchegg-svn
        - csdr-jketterl-git
        - goaljobs
        - peertube-viewer
        - xfconf4.12
        - mingw-w64-glib2
        - elastix-git
        - ispc_texcomp
        - heirloom-devtools-cvs
        - libuinputplus
        - yacreader
        - webapp-manager-git
        - linux-203617-fix
        - cloog
        - drone-monitor-git
        - ocaml-efl
        - ipmctl-git
        - sm64ex-redrawn-git
        - wayfetch-git
        - paraview-qt5
        - prmon
        - linux-rpi2-default-git
        - diacstuff
        - man-pages-nl-git
        - vapoursynth-plugin-hqdn3d-git
        - scdoc-git
name: BUILD-95
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-94
