concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - libvlc-qt
        - pantheon-agent-polkit-bzr
        - singularity-container
        - i3-gaps-git
        - cantor-git
        - heimdall-git
        - bklk-git
        - dvdrtools
        - wpa_supplicant-git
        - lxqt-l10n-git
        - vim-color_coded-git
        - expat-git
        - s2png-git
        - hdctools-git
        - networkmanager-l2tp
        - icmpush
        - cutepeaks-git
        - kona-git
        - linux-surface-pro-4-git
        - calligra-git
        - icu55
        - xrootd
        - swarm
        - qloud-qtcharts
        - liblas-git
        - php-legacy-xdebug
        - z-stack-gateway
        - ignition-sensors
        - folly
        - fbreader-qt5
        - st-monosans-git
        - pcmanx-gtk2-git
        - guile-lib
        - wine64-git
        - evhz-git
        - tpmmanager
        - fplll
        - lib32-libffi5
        - glibc-wsl
        - webalizer-xtended
        - dragon-git
        - cerbere-bzr
        - timeit-git
        - bolt-git
        - gnome-shell-extension-clipboard-history
        - clawspeek-git
        - qtextpad
        - vpnc-gui
        - panda-statusbar-git
        - fmit
        - quadcastrgb
        - ubus-lua-git
        - sx-git
        - gnome-shell-extension-topicons-plus-git
        - naviserver-postgres-connector
        - libexif-gtk
        - lambdacommon
        - pmount-safe-removal
        - telepathy-kde-integration-module-git
        - licensecheck
        - gtk-theme-solarc-git
        - tpm2-tools
        - ripperx
        - mavsdk
        - partialzipbrowser-git
        - yeahconsole
        - screen-message
        - indent
        - grume-git
        - arc-firefox-theme-git
        - hnb
        - infiniband-diags
        - audio_spectrum_oled
        - me176c-factory
        - hex2bin
        - io-git
        - ros-melodic-ecl-config
        - xroar
        - duckstation-git
        - openxr-loader-git
        - gimmage
        - lhs2tex
        - emotion_generic_players-git
        - wine-staging
        - libcue-git
        - done-git
        - ros-melodic-perception
        - cglm
        - antimicro
        - mp-5
        - mate-topmenu-applet-git
        - instead
        - libfprint-acer-swift-1-git
        - bootimgtool-git
        - highway
        - etwm
        - afutrainer
        - mjwm
        - linux-baytrail
        - svgcleaner-gui-git
        - alpine-fancythreading
        - espeak
        - monero
        - simplyfile-git
        - pitrery
        - tulip
        - ros-jade-test-diagnostic-aggregator
        - httpdiff
        - libdv-gtk2
        - bs
        - sublime-text-dev-imfix
        - vapoursynth-plugin-vsmxnet-git
        - php-pcov-git
        - vala0.52
        - reiser4progs
        - boron
        - libhandy-glade-catalog-disabled-git
        - worldpossible-scriptlauncher
        - udpcast
        - rv8-git
        - asciinema-server-git
        - paswitch
        - st-duncan-git
        - dlauncher-git
        - muon-git
        - nkf
        - med3
        - nginx-mainline-addons
        - apertium-crh
        - ros-lunar-geographic-msgs
        - angrydd
        - firenzina-git
        - navidrome
        - openfoam-com
        - autozen
        - waypipe
        - stereophotoview
        - switchboard-plug-gcc-bzr
        - gedit-latex-git
        - tyton-dkms-git
        - freeipa
        - libassuan-git
        - openrave-git
        - lapack-git
        - varnish-modules
        - oatpp-swagger-git
        - libpgf
        - libkomparediff2-kde4
        - ros-melodic-summit-xl-gazebo
        - jm2cv-git
        - php-lua
        - proxy-ns
        - master_me
        - metis4
        - xorg-lbxproxy
        - qpwgraph-qt5
        - kio-fuse-git
        - t-lasku
        - xdg-su
        - ht
        - micronucleus
        - libretro-atari800-git
        - screens-git
        - xbl
        - colutius-desktop-git
        - fabric-server
        - urn-git
        - par2cmdline-git
        - ros-noetic-moveit-simple-controller-manager
        - dcap
        - nextcloud-app-files-external-dropbox-git
        - vala-bootstrap
        - ros-lunar-rqt-gui-py
        - midi-trigger.lv2-git
        - mingw-w64-jansson
        - bottles-fixed
        - ros-noetic-rqt-bag
        - entropy-piano-tuner
        - qt5-wayland-git
        - libmediaart1
        - metis-64
        - navitconfigurator-git
        - omplapp
        - concordance-cli
        - highscore-git
        - larswm
        - new-session-manager-git
        - ros-ardent-rosidl-parser
        - cando-git
        - gophrier
        - fig2dev-git
        - libjwt
        - emcrk-git
        - qmdnsengine
        - mellowplayer
        - unity-greeter
        - grace-openmotif
        - postal
        - hd2u
        - aura-browser-git
        - dotnet-runtime-1.1
        - qemacs
        - linux-xanmod-rt
        - halide-git
        - livi-git
        - ricochet-git
        - xboxdrv-rbp-git
        - qtemu-git
        - ogrebullet-git
        - antpatt
        - cdogs
        - kr
        - ustr
        - fb-folly
        - libgraph
        - enlightenment-arc-theme
        - hottub-git
        - plptools-git
        - ros-melodic-laser-geometry
        - hiredis-git
        - gnat-gps
        - php70-noconflict
        - xtermwm-git
        - dynomite-git
        - linux-nitrous-fire
        - linux-ck-uksm-cjktty
        - iridium
        - avisynth-plugin-addgrainc-git
        - broadcom-wl-lts
        - gtkmagnetic
        - terminus-cyrillic
        - dmenu-gregdan3
        - gazebo-hg
        - php-phalcon
        - vorbis-tools-svn
        - ls-icons
        - swcdb-lib
        - libpasastro
        - atomicparsley-largefile-hg
        - gdal-libkml
        - php56-memcached
        - journal-watch-git
        - libxext-git
        - icu60
        - smcroute-git
        - vte3-selectall
        - chkascii
        - boomaga
        - cage-scenegraph
        - lib_mysqludf_sys
        - opl3bankeditor-git
        - ggoban
        - pcmanfm-gtk3-git
        - homegear
        - prismlauncher-qt5
        - conky19
name: BUILD-83
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-82
