jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - ros-melodic-trac-ik-python
        - udprelay
        - rinetd
        - nextcloud-desktop
        - openca-tools
        - xf86-input-synaptics-gesturesonly
        - android-aarch64-qt6-webchannel
        - heirloom-mailx-cvs
        - gameoftrees-git
        - fforth-git
        - rabbitsign
        - ros-indigo-roscpp-tutorials
        - ros-noetic-rostime
        - lib32-exiv2
        - aisleriot-git
        - vis-git
        - nx-common
        - ros-indigo-rqt-topic
        - ros-jade-ros-tutorials
        - havm-git
        - pmdk
        - mawk-git
        - dpkg-git
        - zdoom-git
        - nginx-mainline-boringssl-google_fliter
        - echo-icon-theme-git
        - icedtea-web-jre32
        - plustache-git
        - plasma-integration-light
        - ros-indigo-create-driver
        - ivpn
        - solar_capture
        - newflasher-git
        - asma-git
        - unadf
        - micro_httpd
        - livekeys
        - bibtex2html-git
        - stc-git
        - postgresql-musicbrainz-collate
        - php74-memcached
        - shadow-libpassphrase
        - linux-sbz
        - libhubbub-git
        - lightdm-pantheon-greeter
        - mpz
        - pebl2-svn
        - interception-space2meta
        - ntpclient
        - linux-xanmod-uksm
        - throttle
        - mandelbrot-gtk-git
        - yoshimi
        - piimg-git
        - katahdin
        - android-armv7a-eabi-pcre
        - graftcp-git
        - pgquarrel-git
        - unnamed-sdvx-clone-git
        - eccodes-git
        - sensible-utils
        - libindi-asi
        - liri-shell-git
        - ros-melodic-trac-ik-kinematics-plugin
        - ps2-ode
        - ros-noetic-rosconsole
        - stormkit-git
        - drafter
        - kopano-webapp-meet-git
        - x2goserver
        - lib32-opusfile
        - ocaml-shine
        - secure-delete
        - xgcom
        - tranqil
        - libzorpll-git
        - ros-melodic-openni2-camera
        - lua-zlib
        - litecoin-qt
        - belr-git
        - virtualbox-headless
        - arpoison
        - windowmaker-extra
        - pecl-raphf
        - die-plugins
        - ocaml-schroedinger
        - nxprayer
        - lib32-allegro4
        - libguestfs-bin
        - chirurgien
        - astra-launcher-git
        - mingw-w64-jxrlib
        - kodi-platform-git
        - obs-gradient-source
        - qaccordion
        - syncthingtray-git
        - foosynth-plugin-neo_fft3dfilter-git
        - wmclockmon
        - ros-kinetic-libuvc
        - eradio-git
        - pgformatter-git
        - picom-git-transparent-clipping-ignore
        - transmission-noxunlei
        - telepathy-poison-git
        - disque-git
        - byzanz-git
        - deadbeef-bs2b
        - clang-ocl
        - spectmorph
        - termbox2-git
        - gitmaster
        - hiprompt-gtk-py-git
        - slingshot-launcher-bzr
        - linux-zen-vfio
        - luastatus-luajit
        - lyricsx
        - bcunit-git
        - soundux-git
        - bib2ref
        - crustris
        - armake-git
        - kscreenlocker-git
        - simcraft
        - kdevelop-clang-tidy-git
        - ripser
        - vbam-git
        - manaplus-git
        - kronometer-frameworks-git
        - mingw-w64-c++utilities
        - ifodump
        - gsignond-plugin-lastfm-bzr
        - daphne-git
        - mkp224o
        - haxe
        - love09
        - yt-dlp
        - quad
        - ros-melodic-octomap-msgs
        - todoist
        - khronos
        - qarv
        - pony.computer
        - wingpanel-monitor-git
        - gimp-plugin-lqr-git
        - at-spi2-atk-git
        - hal-git
        - giara-git
        - simple-scan-trunk
        - zdoom
        - protobuf-ultimaker
        - ros-noetic-roslint
        - android-unpackbootimg
        - linphone-plugin-mssilk
        - tau
        - mingw-w64-netcdf
        - linux-vanilla-selinux-59
        - vdeplug4-git
        - mkxp-git
        - eidete-bzr
        - gpaste-upd
        - textpieces-git
        - scribus-git
        - bibata-extra-cursor-theme
        - mingw-w64-nss
        - ppp-debian
        - mcabber-module-cmd-hg
        - gpr
        - mutrace
        - eggwm
        - catch2
        - cpy
        - ros-melodic-rosout
        - c-icap-modules
        - extra
        - ros-lunar-camera-info-manager
        - folderkit-git
        - libicns
        - php71-apcu-bc
        - pacom
        - gx52
        - ccleste
        - ros-lunar-gencpp
        - blat
        - canorus-git
        - ffmpeg-nvenc-manjaro
        - xprobe2
        - editorconfig-checker-git
        - qdocumentview
        - sfcgal-git
        - buho-git
        - superslicer-prerelease
        - defragall-git
        - gr-limesdr-3.9-git
        - ykpers
        - openxr-explorer-git
        - nvidia-lts-ck
        - libosmium-git
        - cozy-audiobooks-git
        - xenia-linux-fixes-git
        - mandos-server
        - lxc-anbox
        - dosbox-binutils
        - coolprop-git
        - linapple-git
        - tidyview
        - gtkhtml3
        - setbfree
        - overwitch-git
        - libwsclient-git
        - hexedit0r
        - ascii-fluid-dynamics-git
        - fake86
        - acousticbrainz-gui-git
        - darktable-rc
        - makedev
        - tenacity-git
        - lib32-libffi-minimal-git
        - php73-memcache
        - range-v3-git
        - pdisk
        - lib32-libvdpau-git
        - cantata-qt4
        - liblo-git
        - sdbus-cpp-git
        - spectrwm-git
        - naaman
        - nss-tls-git
        - ewe
        - xviewer-plugins-git
        - aur-search
        - efibooteditor-git
        - mingw-w64-libpng
        - ros-kinetic-amcl
        - plasma5-applets-fanspeed-monitor-git
        - shepherd
        - seafile-client
        - liboping
        - libinput-accel-profile-git
        - osmo-bts-git
        - ros-jade-kinect2-viewer-oculus
        - sidplayfp
        - savvycan
        - lxqt-appswitcher
        - hwloc1
        - ebook-viewer-git
        - qtscriptbindings
        - qtraw
        - cbm-git
        - bzrtp-git
        - libkipi
        - enlightenment-git
        - supertux-old
        - cuishark
        - ebpfsnitch-git
        - bomberclone
        - anvill
name: BUILD-81
'on':
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-80
