jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - xdgmenumaker-git
        - mingw-w64-mpv
        - gtk3-cloudproviders
        - uuid
        - symbolic-preview
        - ifrextractor-ls-git
        - freediameter-hg
        - openra-ca-git
        - grotz
        - epson-inkjet-printer-ep-302
        - dbus-git
        - goomwwm-git
        - switchboard-plug-locale-bzr
        - nginx-mainline-mod-brotli-git
        - kpmcore-git
        - ros-jade-rqt-gui
        - mfem
        - asn1c-git
        - ros-ardent-resource-retriever
        - linux-amd-raven
        - vibe-d
        - mingw-w64-sqlcipher
        - pyqt3
        - flightgear
        - sndpeek-jack
        - qimageblitz-svn
        - zbar-comp
        - kopano-webapp-files-owncloud-backend-git
        - alligator-git
        - leela-zero
        - lib32-libogg-git
        - ekho
        - ksysguard-git
        - oxdna-cuda-git
        - php81-imagick
        - gr-hrpt
        - muserv-git
        - 8play
        - expertguide-git
        - plasma5-applets-caffeine-plus
        - ros-jade-gazebo-ros
        - linux-luca020400
        - ros-ardent-ament-cmake-python
        - microcom
        - urfkill-git
        - gnu-efi-libs-git
        - openanno-archive
        - ros-indigo-ecl-containers
        - otca-git
        - ayatana-indicator-session
        - usbview2
        - mdk
        - gitqlient-git
        - sigdigger-git
        - libxmp-git
        - fox-devel
        - neovim-telescope-fzf-native-git
        - transcend
        - omnispeak
        - swisswatch
        - uefi-shell
        - mozilla-firefox-sync-server-hg
        - vncterm-git
        - qbittorrent-enhanced-ua
        - sdl-nokbgrab
        - astromatic-psfex
        - freediag
        - ros-indigo-urdf-parser-plugin
        - php81-mcrypt
        - ros-jade-tf-conversions
        - spl
        - lua-format-ext
        - tea
        - konoha
        - libecpint-git
        - xf86-input-synaptics-git
        - gargoyle-git
        - jamulus-headless
        - ayatana-indicator-messages
        - libretro-bluemsx-git
        - beef
        - linux-libre-hardened
        - tictactoe-git
        - foosynth-plugin-neo_vague_denoiser-git
        - mutter-auto-rotation
        - php-cairo-git
        - virtualbox-i3
        - opencu
        - libsocketpp
        - b25
        - mingw-w64-sonnet
        - vapoursynth-plugin-tedgemask-git
        - ephemeral-git
        - lfo-blender.lv2-git
        - sendmidi
        - kanttiinit-git
        - mingw-w64-mcfgthread-git
        - wfslib-git
        - hypseus-singe
        - kodi-devel-pvr-nextpvr
        - virt-manager-qt
        - stressapptest
        - gnome-shell-extension-clock-override-git
        - mutter-wine-fullscreen
        - ros-noetic-audio-common
        - tinycamd-svn
        - ros-noetic-theora-image-transport
        - slock-blurscreen
        - dmenu-edersonferreira
        - fontbuilder
        - poldi
        - dict-freedict-spa-eng
        - redkite-git
        - ros-noetic-teleop-twist-keyboard
        - vbextreme-bar-git
        - zathura-epub-git
        - vexcl-git
        - fish-irssi-git
        - mediastreamer
        - bedtools
        - lola1
        - potatopresenter
        - kcompletion-git
        - idutils
        - sdrplusplus-git
        - minivmac-beta
        - suricata-nfqueue
        - rdma-core
        - linux-clear-current
        - nsnake-git
        - qvplugins-git
        - openocd-mips-git
        - k9copy-kde4
        - cainteoir-engine
        - ltfs
        - ujson-git
        - glxosd-fix-git
        - video-compare
        - k9copy-frameworks
        - smarthhc
        - libnsbmp-git
        - serialtool
        - cow
        - mingw-w64-levmar
        - nemo-engrampa
        - syncevolution-nogui
        - v8-6.7-static
        - librnd4
        - ros-noetic-nav-msgs
        - desq-session
        - num
        - mirtk
        - tacacs-plus
        - structuresynth
        - coin-or-alps
        - od-tools-git
        - libisofs-git
        - tfel
        - digital-bitbox-app
        - dwgsim-git
        - switchboard-plug-security-privacy-git
        - edcltool-git
        - dxvk-nvapi-mingw
        - fftw2
        - ros-noetic-image-geometry
        - lib32-libvdpau-va-gl
        - 3dstool-git
        - objcryst-fox
        - obs-nvfbc-high-fps-git
        - libitl
        - pioneer
        - ospkit-git
        - anastasis-git
        - chemical-mime-data
        - v4l2ucp-qt5
        - stratisd-git
        - basket
        - librtmp0
        - mingw-w64-lpsolve
        - epiphany-elf-gcc
        - zzuf-git
        - attica-qt4
        - ffmpeg-svt-av1-git
        - blueshift-tray
        - s3backer-git
        - grig-git
        - opencoarrays
        - qucs-s-git
        - gr-air-modes-git
        - odin
        - nanocurrency-git
        - ros-kinetic-rosbridge-server
        - tempered-git
        - quick-lint-js
        - joyosc-git
        - ros-indigo-nav-msgs
        - cin
        - mcpelauncher-linux
        - crackpkcs12
        - qtutilities
        - nam
        - botan-git
        - instr2raw
        - irony-mode
        - comby
        - lsyncd-git
        - libdeflate
        - mda-lv2-git
        - xfsdump
        - granite-git
        - mingw-w64-openmesh
        - kimap2-git
        - modemmanager-qt6
        - mangl-git
        - havoc
        - osdlyrics-git
        - libvdpau-sunxi-git
        - vlc-bittorrent-git
        - neovim-youcompleteme-core-git
        - mold-git
        - waifu2x-converter-cpp-cuda-git
        - linux-xanmod-cacule-rt
        - palaura-git
        - chromium-wayland
        - sanjuuni
        - mesh-git
        - linux-cacule-rdb-rc
        - wrk
        - coreinfo-git
        - emacs26-git
        - cie-middleware-git
        - pgadmin4-venv
        - mingw-w64-blosc
        - protonutils
        - photon-rss-git
        - vxl
        - ccache-4
        - ros-indigo-hector-nav-msgs
        - freechart-svn
        - sugar3-toolkit-gtk3
        - gtklock-playerctl-module
        - xournal
        - gtk3-patched-filechooser-icon-view
        - t2scan
        - compiz-fusion-plugins-experimental
        - irssi-otr-git
        - mod_python2-legacy
        - tclxosd
        - linux-api-headers-git
        - bitfetch-git
        - ros-noetic-smach-ros
        - alive
        - gnunet-gtk-git
        - swaylock-plugin-git
        - ros-indigo-uvc-camera
        - libscrobbler
name: BUILD-98
'on':
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-97
