jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - masari
        - p910nd
        - nidaqmx-source-support-dummy
        - maui-core-git
        - ros-indigo-image-geometry
        - lib32-openexr
        - json-tui
        - neovim-git
        - htop-vim-git
        - coin-or-coinasl
        - entr-git
        - tnt-ncurses5-compat-libs
        - gnome-shell-extension-appindicator-git
        - xplayer-plparser-git
        - spoofer
        - codelldb
        - od-libautomotivedata-git
        - tracks-player-git
        - metronome-dev
        - futhark
        - paleofetch-git
        - wiggletools
        - fmbt
        - mingw-w64-vulkan-icd-loader
        - gsignond
        - kdeplasma-applets-gx-mail-notify
        - mcpelauncher-ui-git
        - gitlab-workhorse
        - witfocus
        - qvssr
        - qsyncthingtray
        - libskk-git
        - tango-icon-theme
        - livecv
        - titan-git
        - ros-noetic-actionlib-msgs
        - crfsuite
        - libzim
        - perceptualdiff
        - etlegacy32-git
        - osmo-msc-git
        - hyprland-hidpi-xprop-git
        - wob-git
        - pgformatter
        - openexr-viewer
        - zig-git
        - ros-kinetic-moveit-ros-warehouse
        - rtools-git
        - openscad-git
        - fs-uae-arcade-devel
        - backlight_control
        - xcb-util-xrm-git
        - xfce4-composite-editor
        - dns-proxy-git
        - faust-lv2-git
        - parallel-git
        - diffimg-git
        - opendmarc
        - kraken-gsm-git
        - vtuner-module
        - rtl8192su-git
        - vim-youcompleteme-git
        - prison-light
        - theshell
        - pantheon-photos-bzr
        - nocache
        - ros-kinetic-controller-manager-msgs
        - apkstudio-git
        - gct
        - mingw-w64-libgtop
        - otrtool-git
        - utox-git
        - gnome-user-docs-git
        - dxvk-async-git
        - lkl-linux-git
        - gnochm
        - i3-plasma
        - dsmidiwifi-cli
        - notes.lv2-git
        - discover-snap
        - osmscout-server-kirigami
        - poezio-git
        - unclutter-xfixes-git
        - jpeg2png-git
        - xye
        - bitcoin-ljrp-git
        - ros-melodic-urdf
        - mingw-w64-vulkan-headers
        - kopano-webapp-spellchecker-languagepack-fr-fr-git
        - libgaminggear
        - libass-git
        - librearp-git
        - apertium-separable-svn
        - spdlog-git
        - emptyepsilon-git
        - lua-cqueues
        - libplacebo-git
        - crosswords-puzzle-sets-oedipus
        - php81
        - cower-git
        - zita-at1
        - thinglaunch-git
        - nvidia-tomoyo
        - scroll-git
        - nekoray-git
        - m210
        - apertium-pt-ca
        - chromium-ozone-wayland-git
        - avr-libc-avrxmega3-svn
        - sugar-base
        - switchboard-plug-printers-bzr
        - mingw-w64-glpk
        - rasterview-git
        - libbuddy-git
        - rar2fs
        - udis86
        - vapoursynth-plugin-cmedian-git
        - xcompmgr-git
        - bcwc_pcie-ck
        - forge-git
        - nowdock-panel
        - boomaga-git
        - lazy-git
        - postgresql-lts-old-upgrade
        - cpp-argparse-dev
        - nref
        - doxygen-clang
        - mingw-w64-graphicsmagick
        - bruteforce-luks-git
        - kwstyle-git
        - zynaddsubfx-git
        - xritty
        - cl-alexandria
        - yafaray-experimental
        - libfnr-git
        - i3-lazy
        - pdextended-touchosc-git
        - donnatella
        - colmap-git
        - paraview-git
        - gimp-plugin-astronomy
        - mygui-ogre1.9
        - android-x86-opus
        - mingw-w64-librttopo
        - liri-files-git
        - featherpad-git
        - ros-kinetic-class-loader
        - nip2
        - luajit-openresty-stable
        - kopano-webapp-spellchecker-languagepack-es-es
        - crosstool-ng
        - gperftools-aarch64-tls-fix
        - paleofetch-croco
        - kopano-webapp-spellchecker-languagepack-de-de-git
        - stuntrally
        - opendnp3-git
        - naemon-livestatus
        - obs-rendering-lag
        - opencircuitdesign-netgen-git
        - gpscorrelate-git
        - raktpdf
        - openvpn-auth-ldap
        - libuavcan
        - epeg-git
        - gpp
        - octopi-dev
        - mingw-w64-libmodplug
        - classix
        - dune-geometry
        - dream
        - kodi-addon-pvr-nextpvr
        - postgresql-libversion
        - rxvt-unicode-improve-font-rendering
        - indicators
        - vimix
        - guile-opengl-git
        - emacs-ng
        - pidgin-privacy-please-git
        - mingw-w64-libexif
        - mingw-w64-libxcb
        - chicony-ir-toggle-git
        - fprintd-libfprint2
        - timg-git
        - aspell-lt
        - somagic-easycap-smi2021-git
        - wsa-git
        - dolphin-emu-wayland
        - ros-kinetic-openni2-launch
        - neatpost-git
        - safe-git
        - ox
        - libgnomeprint
        - flint1
        - plasma5-applets-uswitch
        - vtk-raytracing-git
        - vte3-ng-fullwidth-emoji
        - snapcast-git
        - linux-phicomm-n1
        - tmux-truecolor
        - libpfring-git
        - mingw-w64-eigen
        - vtk5
        - ompl-git
        - hexen2
        - chipeight-git
        - sxiv-pango-git
        - uzbl-next-git
        - tagtool
        - amino-git
        - openvpn3-git
        - ly-git
        - gnome-settings-daemon-120dpi
        - qt6-doc
        - tines
        - sview
        - tempsense-git
        - quit-git
        - fftw-amd
        - icu62
        - wallutils
        - libgames-support-git
        - nextcloud-client
        - qgis-ltr
        - mediaconch-server
        - crctk-git
        - sums-git
        - cammill-git
        - vacuum-im
        - dionaea-git
        - erfa
        - ros-lunar-tf2-geometry-msgs
        - dwm-distrotube-git
        - wiredtiger
        - soundtank
        - cl-launch
        - kube-develop-git
        - lizard-git
        - afuse
        - xdump
        - purple-skypeweb-git
        - emerald-git
        - zabbix3
        - lv2-git
        - opencbm
        - ogre-next-git
        - weechat-discord-git
        - osdlyrics-pedrohlc
        - volnoti-brightness-git
        - navcoin
        - sherlock
        - soxt
        - mozilla-vpn-client
        - compiz-bcop
        - riscv-sifive-elf-gcc
        - gamin
        - symlinks
name: BUILD-132
'on':
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-131
