concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - julius
        - allioli
        - gnutls-git
        - rpiusbboot-git
        - symbolic-preview-git
        - xfce4-multiload-ng-plugin-gtk2-git
        - geis
        - terravox-git
        - bumblebee-git
        - ros-noetic-spacenav-node
        - usenew-git
        - ficl
        - brightnessctl
        - lib32-gtk3
        - squeezelite
        - ros-kinetic-urdf-parser-plugin
        - lib32-libdispatch-clang-git
        - paranoid-telnetd-git
        - wf-info-git
        - cask-server-git
        - gnome-shell-extension-frequency-boost-switch-git
        - ntopng-git
        - casadi
        - shadow-minimal-git
        - dvd95-git
        - brotli
        - openvas-scanner
        - penguin-subtitle-player-git
        - lib32-libdrm-minimal-git
        - ros-indigo-pluginlib-tutorials
        - fairroot
        - sanjuuni-ui-git
        - gstreamer-oleavr
        - getdns
        - cawbird-git
        - scenarist
        - vte-legacy
        - ricochet
        - stu-git
        - xglfs
        - aseqjoy-git
        - kfreestyle2d-git
        - pep-engine-hg
        - heather
        - thermald-git-gcc10
        - sshign
        - ros-jade-laser-filters
        - baamanga
        - gtkevemon-git
        - yiolibc
        - termcolor
        - ros-melodic-wiimote
        - livius-git
        - utena-launcher
        - kwin-effects-sliding-notifications-git
        - parallel-hashmap-git
        - wf-recorder
        - fbvis-git
        - lightmediascanner-git
        - sn0int
        - android-x86-speex
        - wxwidgets2.8-light
        - ros-melodic-rosdoc-lite
        - kde1-kdenetwork
        - xorg-xwayland-rootless-nosystemd-minimal-git
        - libsurvive-git
        - rtags
        - flatbuffers
        - obs-text-pthread
        - ros-kinetic-rosbridge-library
        - rtorrent-ipv6
        - eyesight-git
        - libretro-mame2010-git
        - mingw-w64-paraview59
        - apertium-hbs-mkd
        - systester
        - lib32-sratom
        - ros-noetic-libuvc
        - libselinux
        - bosce
        - hyperion.ng-git
        - fex-emu
        - gdal-hdf4
        - urlencode
        - psximager-git
        - librepcb
        - riker-git
        - pirate-qt
        - ocaml-yojson-git
        - engauge
        - ladish-git
        - zutils
        - linux-drm-intel-next-queued-git
        - spredit
        - qt5-qmllive-git
        - glnemo2
        - vdi-stream-client
        - sequoia
        - qt5-charts-git
        - mingw-w64-libkate
        - php73-memcached
        - sdrpp
        - sdltrs
        - openblack-git
        - mingw-w64-isl
        - aseba-git
        - ocaml-ocamlgraph-git
        - lib32-libcap-ng
        - ros-kinetic-mk
        - sandboxctl
        - sigviewer
        - xwinwrap-git
        - alsacap
        - freecad-python3-git
        - geoipmarker
        - fossil-fossil
        - odpi
        - intercourse
        - mpd-smbclient
        - tinyb
        - bower-mail-git
        - obs-vban
        - php-pdo-oci
        - linux-cachyos-pds
        - ros-jade-rqt-publisher
        - selene
        - logitech-g710-kmod-git
        - protracker-git
        - ros-kinetic-image-exposure-msgs
        - ncurses-git
        - ratpoison-jcs-git
        - rep-gtk
        - ros-indigo-shape-msgs
        - jfa-go-git
        - kdeedu-ktouch-patched
        - lxqt-notificationd-git
        - zff-reload
        - global
        - connman-ncurses
        - wingpanel-indicator-network-git
        - tcptrack
        - velox
        - wshowkeys-git
        - glade-sharp
        - or1k-elf-binutils
        - ssdfs-tools
        - secrets
        - ros-noetic-tf
        - mingw-w64-qt5-speech
        - psi-plus-webkit-git
        - ros-jade-rqt-launch
        - sentinelcli
        - netactview
        - astromatic-missfits
        - miniasm
        - cudaminer-git
        - blackvoxel
        - ros-kinetic-nmea-msgs
        - dolphin-duckspace
        - openbox-xdgmenu
        - cvassistant-git
        - boundary-git
        - haredo
        - dlcall-git
        - sqlpp11-connector-sqlite3
        - adcd
        - switchboard-plug-power-git
        - nvenc
        - umip
        - ros-noetic-gazebo-ros
        - flameshot-old
        - rkr-lv2-git
        - ros-kinetic-moveit-ros-manipulation
        - fluxcomp
        - catclock-git
        - craft-git
        - agbcc
        - lua52-compat53
        - boulder-git
        - ros-noetic-costmap-converter
        - beesat-sdr-git
        - qruler-git
        - hexcurse
        - lg4l
        - zelvici-svn
        - loadlibrary-git
        - cheatsheet-git
        - rofi-file_browser-git
        - rz-cutter-git
        - wren-git
        - crimson
        - ros-jade-roswtf
        - vdr-channellists
        - ogre-1.9-pagedgeometry
        - psi4
        - duffle
        - avr-libc-18
        - blender-modifier-panels-ui-git
        - landrop
        - wasm3-git
        - freetype2-git
        - libretro-scummvm-diablodiab-git
        - mate-multiload-ng-applet-gtk2
        - wds-git
        - bennugd-modules
        - laminar
        - kadnode-git
        - linux-rust
        - libdeltachat-git
        - qzdl
        - kblackbox-git
        - gauche-dbd-pg
        - xjwt
        - vnote3-git
        - guile-avahi
        - nethack-qt
        - ros-noetic-map-msgs
        - gxr
        - bitcoin-core
        - rsync-fadvise
        - gnome-screencast-git
        - sc-tool
        - lib32-libidn2-git
        - rocketlauncher2-git
        - saberlight-git
        - picojson-git
        - basiliskii-git
        - kicad-templates
        - latencyflex-git
        - msiklm-git
        - elfeed
        - krunner-translator
        - ros-lunar-executive-smach
        - libboard
        - wmapp
        - freebsd-pkg
        - qdmr
        - blktrace
        - sfarkxtc
        - qt5-qtcsv
        - gavl-svn
        - tokodon-git
        - spim
        - vdr-dvbapi
        - mingw-w64-libvorbis
        - lib32-mtdev
        - ros-ardent-ament-cmake-pep8
        - sctp-refimpl-svn
        - android-aarch64-speexdsp
        - ignition-cmake2
        - linux-vanilla-selinux-49
        - linux-cpu-optimized
        - fcitx-tsundere
        - midizap-git
        - hidattack
        - hexedit-advanced-search
name: BUILD-17
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-16
