concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - mingw-w64-crossc
        - mfoc-nonested-git
        - gnome-usage-git
        - xz-static
        - sarqx-reporter
        - yorick-ml4-git
        - imgkap
        - haguichi-bzr
        - ros-melodic-robot-state-publisher
        - gnome-calendar-git
        - rl_custom_isearch-git
        - khronos-ocl-icd-git
        - onionprobe-git
        - bzzwolfsp-svn
        - swop
        - ect
        - liblinphone
        - cairo-clock
        - dracut
        - qt-aseman
        - luced
        - htd
        - alcase
        - libp11-git
        - opensmile
        - virtualplanetbuilder-git
        - wm2
        - codelite-unstable
        - tremulous-git
        - stubgen
        - gnome-twitch
        - lib32-wfdb
        - fvwm-git
        - st-luca
        - exiftags
        - orocos-log4cpp
        - atlas-cpp
        - stlink-git
        - supercollider-git
        - gnome-colors-revival-git
        - ros-indigo-diagnostic-common-diagnostics
        - libsedml
        - yacasl2
        - openmp-svn
        - ros-lunar-shape-msgs
        - libodf-template
        - tpfand-git
        - libit
        - kcoreaddons-git
        - wsjt-svn
        - utilyre-st-git
        - clanlib-23
        - rtl8187se
        - colourpipe
        - libhdate
        - pango-git
        - octetos-db-postgresql
        - setroubleshoot-git
        - quantlib-git
        - kcalendarcore-git
        - pumpa-git
        - mingw-w64-evince-light
        - ddrutility
        - libc++abi-svn
        - coreterminal
        - automatic
        - fontbm
        - retroshare-git-no-sqlcipher
        - asciidoc-py3
        - sii-slp-cups-git
        - easena-git
        - gnome-fuzzy-app-search
        - dscanner
        - grumpy-irc-git
        - xfce4-windowck-plugin-bobko-mod
        - mingw-w64-poppler-static
        - emelf-git
        - pev-git
        - i386-elf-binutils
        - mate-window-buttons-applet
        - mingw-w64-yasm
        - ros-noetic-test-diagnostic-aggregator
        - my_test_package_jabra
        - ros-kinetic-ecl-time
        - oglp-git
        - iptables-mod-randmap-git
        - plasma5-applets-playbar2-git
        - huhfa
        - tinyfugue4-stable
        - tkrzw-git
        - wmcalendar
        - xbanish
        - nautilus-metadata-editor
        - ros-kinetic-tf2-msgs
        - gearsystem
        - vipsdisp-git
        - pulsemeter
        - oneko
        - openvas-manager-postgres
        - tokyocabinet-git
        - stgit
        - seexpr1-2
        - dmrconfig-git
        - awesome-luajit
        - mingw-w64-gstreamer-git
        - system76-power
        - libbcd
        - aarch64-linux-gnu-icu
        - tsvm-git
        - stc8prog
        - breezesierra-aurorare-theme-git
        - evolution-git
        - comgr
        - mct-qt
        - openlte
        - dspam
        - pcraster
        - libfev-git
        - lzdoom
        - xfce4-settings-standalone
        - libnss-extrausers
        - wobbly-git
        - screcord.lv2-git
        - libgeneral-git
        - bcftools
        - mingw-w64-resource
        - kopano-webapp-spellchecker-languagepack-de-ch
        - libx32-mpdecimal
        - dmenu-duncan-git
        - async-profiler
        - ros-indigo-rqt-plot
        - nas-git
        - gvim-wayland-lilydjwg-git
        - kitemviews-git
        - plasma-vault-git
        - coretime-git
        - mp-sonivoxeas
        - kodi-addon-game-libretro-flycast
        - msp430-libc
        - flap
        - mingw-w64-libspatialite
        - mingw-w64-robin-map
        - yorick-usleep
        - libui-git
        - soapysdrplay-git
        - zarchive
        - libsbgn-svn
        - xineliboutput
        - irssi-xmpp
        - newmat-shared
        - yishu
        - btc-cirrus-reporter
        - sysvbanner
        - nelua-git
        - droidcam
        - john-mpi
        - libtmx
        - andns-rpc
        - xapian-core-git
        - gophervr
        - testdisk-git
        - bus-pirate
        - last-align
        - ros-kinetic-joint-trajectory-controller
        - xorg-editres
        - astyle-svn
        - java-quantlib
        - bubblefishymod
        - shadowsocksrr-libev-git
        - gscan2pdf
        - minisphere
        - peakperf-git
        - pico
        - gnome-inform7
        - libchadstr-git
        - fasttext-git
        - gmid-git
        - jsonproc
        - hode-git
        - dh-golang
        - prometheus-libvirt-exporter
        - aegisub-dependency-control
        - powerpc64le-linux-gnu-gcc-stage1
        - xcdroast
        - kodi-addon-vfs-libarchive
        - mympd
        - ros-kinetic-zeroconf-avahi
        - dablin
        - etherwake
        - soapyuhd-git
        - umoria
        - tailman
        - ntch
        - eepclock
        - mingw-w64-dbus
        - cccc
        - gngeo-hg
        - cinelerra-heroine
        - linux-git-rtw89
        - quakespasm-svn
        - google-cloud-cpp
        - icc-brightness-gnome-git
        - texlive-bin-svn
        - manager-accounting
        - ppp-eap-mschapv2
        - gsimplecal-lunar
        - qbittorrent-stable-git
        - melonds-git
        - fetchmail
        - leafnode
        - gmp4-static
        - yaxt
        - xorg-xsetmode
        - ppac-git
        - eggdrop-gseen.mod
        - simplescreenrecorder-qt5-git
        - qotd-git
        - gnustep-corebase-clang-svn
        - bpf-tools
        - libbitcoin-explorer
        - libtickit
        - rpm-builder
        - bitcoin-uasf-git
        - greenbone-security-assistant
        - clang13
        - ros-noetic-moveit-resources
        - wingpanel-indicator-sound-git
        - jitsi-meet-git
        - objgui-git
        - dmscripts-git
        - ags
        - pr-downloader-git
        - nextaw
        - telegram-desktop-customqt
        - himitsu-ssh-git
        - mingw-w64-qt5-activeqt
        - ros-indigo-rocon-python-wifi
        - epson-inkjet-printer-ep-803a-903f-series
        - zlib-ng-compat-git
        - kafkacat-avro-git
        - slimit2
        - obs-v4l2sink-git
        - nvidia-zen-grsec
        - kwinft
        - pallache-git
        - libtorrent-ps
        - gst-plugins-vr-git
        - meters-lv2
        - tinyvm
        - lightdm-pantheon-greeter-git
        - fortune-mod-ducktales
        - racon-git
        - mscompress
        - blocky
        - bsnes-qt5
        - netbsd-fs-utils-git
name: BUILD-26
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-25
