concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - mamba
        - torcs-can
        - libfolia-git
        - lttng-modules
        - apollo-git
        - lib32-isl
        - catppuccin-cursors-git
        - libsimple
        - brahms-git
        - ultrastar-creator
        - salome-paravis
        - wxlua-svn
        - ptouch-print-git
        - ifuse
        - libbacktrace-git
        - librnd
        - gummi-gtk2-git
        - xcircuit-devel
        - logrotate-git
        - mcpelauncher-msa-git-fixed
        - gphoto2-git
        - fogpad.lv2-git
        - xfce4-clipman-plugin-git
        - vim-twig-git
        - xorg-xinit-git
        - ros-indigo-visualization-msgs
        - gwatcher
        - bipscript-ide
        - deuchnord-hermes
        - libadwaita
        - globalprotect-openconnect
        - epson-inkjet-printer-stylus-photo-r3000
        - sdump-git
        - nautilus-checksums-git
        - telegram-desktop-light
        - hp-printer-app
        - hyne-git
        - mingw-w64-libao
        - le-editor
        - lll
        - libibscif
        - varrick-git
        - ftwin
        - obliviate
        - gstreamer0.10-ffmpeg
        - tvheadend-atsc-epg-git
        - memlockd
        - ros-indigo-rostime
        - php-wikidiff2
        - libhttpseverywhere
        - moment
        - ros-kinetic-interactive-marker-tutorials
        - nuvola-app-jupiter-broadcasting
        - libiges-git
        - notes-up
        - purple-hangouts-hg
        - php7-mcrypt
        - dwmblocks-dylan-git
        - flwm-git
        - ros-kinetic-roslisp
        - mingw-w64-gc
        - keyfault
        - apidb-core
        - sselp
        - pdfmixtool-git
        - dolphin-root-git
        - ffmpeg-vaapi-crop
        - playerctl
        - bro-aux
        - ros-kinetic-robot-model
        - ttyd
        - netinstall
        - qelectrotech
        - hpoj
        - amberfish-git
        - rapidjson-git
        - flatzebra
        - wmii
        - beebeep
        - gnome-shell-extension-shuzhi
        - adbfs-rootless-git
        - ros-lunar-rqt-topic
        - ros-kinetic-diff-drive-controller
        - ros-lunar-joint-state-publisher
        - pg_cjk_parser-git
        - dolphin-megasync
        - obs-midi-mg
        - gds3d-git
        - camorama
        - pi-blaster-git
        - zap-soundboard-git
        - linux-xanmod-tt
        - overlay-scrollbar-bzr
        - colorway
        - qt5-multimedia-mdk-plugin
        - ros-indigo-stereo-image-proc
        - usbaudio-git
        - linux-lts318-ck
        - moneymanagerex-git
        - diskfile-git
        - pixiewps
        - inferno-hg
        - pbrt-v3-git
        - dockfmt-git
        - aarch64-linux-gnu-libgcrypt
        - ros-indigo-turtlebot-bringup
        - complexity
        - lib32-isdn4k-utils
        - srcry-git
        - hawaii-system-preferences
        - multimc-git
        - mx3000control-git
        - eolie-next-git
        - zim-tools-git
        - openfec
        - spellutils
        - adms
        - oculus-rift-sdk-jherico-git
        - tome4-git
        - ros-melodic-smach
        - alohomora
        - orocos-bfl
        - wayclip-git
        - shortwave
        - ros-indigo-manipulation-msgs
        - openmodelica-dev-omlibraries
        - fs_mark
        - libpreludedb
        - rott
        - krunvm-git
        - rirc-git
        - ponypipe
        - gr-limesdr-git
        - waterfox-git
        - z80-asm
        - cnrdrvcups-lb
        - liri-eglfs-git
        - ggmud-svn
        - linux-libre
        - tulip-pm
        - graphthing
        - systemd-knock
        - lean-git
        - egawari
        - teem
        - dump-shm
        - avisynth-plugin-removegrainhd-git
        - nginx-mainline-addon-auth_pam
        - clipgrab-kde
        - ttf-twemoji-color-git
        - spdynu
        - ibus-hangul-git
        - abcpp
        - ros-jade-rosmaster
        - minimap2
        - intel-vtune-amplifier-community
        - fortune-mod-betteroffted
        - amule-remote-tools
        - lightdm-bzr
        - bitmask_client
        - mingw-w64-qwt-qt6
        - inox-hard
        - soh
        - desktop-like-mobile-config-firefox
        - openrct2
        - ros-lunar-geometry-msgs
        - powa-archivist-git
        - recipes
        - emovix
        - cups-pdf-to-pdf-git
        - husky-msged-git
        - libmtk-git
        - blueberry-wayland
        - lsdbus
        - netwmpager
        - rdma-core-no-pandoc
        - measurement-kit-git
        - pdfmerger
        - mattermost-push-proxy
        - qwikaccess-git
        - crengine-ng-git
        - rhythmbox-git
        - linux-ck-fbcondecor
        - nmap-svn
        - openresty_luarocks
        - libsoup-gnome
        - opencrg
        - englab
        - aruco
        - onioncat-svn
        - liblogging
        - ros-kinetic-rviz-plugin-tutorials
        - hantek6022api-git
        - mingw-w64-libgcrypt
        - yagy
        - gwankei-git
        - sitecopy
        - ocaml-http-git
        - graphene
        - apm_planner
        - buildtorrent
        - libcsptr
        - docker-registry2-git
        - openmpi-1.10
        - raft
        - intel-hexl
        - qv2ray-plugin-trojan-git
        - corectrl-git-nofan
        - gmp-git
        - wolfssl
        - ophidian-verilog-parser-git
        - gdeskcal
        - gauche-c-wrapper
        - imx_usb_loader-git
        - ros-melodic-rotors-gazebo-plugins
        - danmakufactory
        - glide-git
        - breath-gtk-git
        - permfix
        - mingw-w64-postgresql
        - keurocalc
        - lib_amxo-git
        - ros-lunar-stage-ros
        - cairo-xml
        - qwbfsmanager-git
        - libwebsockets15
        - hivex-git
        - sooperlooper-git
        - dict-freedict-fra-eng
        - imcompressor
        - lib32-a52dec
        - zerotier-one-with-controller
        - net-tools-mptcp
        - rocminfo
        - poissonrecon-git
        - wluma-als-emulator-git
        - tscat
        - correctpony
        - attract
        - ros-lunar-pcl-ros
        - g4python-git
        - cunit
        - robotfindskitten
        - xwiimote-git
        - tigercapture
        - ros-lunar-gl-dependency
        - naemon
        - pd-git
        - plasma5-applets-bandwidth-monitor
        - happy-hacking-gnu
        - osprey-dpd
        - snixembed
        - gpsfish_minimal
        - gnome-shell-extension-ubuntu-dock
        - vapoursynth-plugin-eedi3-ocl-git
        - gpu-viewer
name: BUILD-87
'on':
  workflow_dispatch: ''
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-86
