concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - st-zenburn-git
        - quadra-git
        - ros-indigo-rosserial-embeddedlinux
        - conceal-core
        - gltron
        - psp-libpspvram
        - secretfs
        - capsudo-git
        - tremulous
        - smooth
        - tea-qt-git
        - sddm-conf-git
        - ros-jade-tf
        - katecpp-helper-plugin
        - gorm.app
        - wmtv
        - libretro-snes9x2010-git
        - mstpd
        - protodata-git
        - deadbeef-plugin-lyricbar-git
        - ip2location-c
        - dfl-layouts
        - wio-wl
        - getgauge
        - avvie-git
        - srm
        - jabba
        - nestopia-git
        - xen
        - wordtsar-hg
        - xosd-ex
        - android-x86-x264-bootstrap
        - helib-git
        - chigraph-gui
        - mellowplayer-git
        - rocsolver
        - timetable-git
        - linux-surface3-git
        - teximpatient-git
        - librevisa-git
        - synaptics-led
        - libslink
        - go-filecoin
        - pulseaudio-modules-bt
        - ros-kinetic-rosnode
        - crtmpserver-svn
        - virtboard-git
        - gingerblue
        - abstouch-nux
        - amos
        - libdvd-audio
        - daykountdown-git
        - asdf
        - qv2ray-dev-git
        - mpy-cross
        - mingw-w64-opencolorio1
        - nvtv
        - minuit2
        - fortune-mod-marriedwithchildren
        - gtk3-nocsd-git
        - coq-quickchick-git
        - dosbox-svn
        - horizon-eda
        - dump1090-tomswartz-git
        - hindsight
        - ola-git
        - sane-git
        - rptable-git
        - hashcat
        - madcow
        - osu-handler-git
        - sentry-native-git
        - faust
        - easea
        - dwm-rinne-git
        - fsniper-git
        - qt6-translations
        - libntlm
        - factropy-git
        - pcb-git
        - rsbag-tools-cl
        - citra-emu-fresh
        - lib32-libpaper
        - kim-api
        - epson-inkjet-printer-201202w
        - git-prompt
        - qonk
        - pythia8
        - flite1-patched
        - lib32-shaderc-git
        - crfpp-git
        - aasdk-git
        - vapoursynth-plugin-templinearapproximate-git
        - fluid
        - mxk
        - postgis-src
        - libbrotli
        - nagircbot
        - bbswitch-rt
        - web-eid
        - mingw-w64-mpg123
        - hactool-git
        - zypper
        - sslide
        - ibpd
        - libisf-qt-git
        - gr-osmosdr-git
        - debhelper-git
        - mingw-w64-mman-win32-git
        - libgrapheme-git
        - gnu-apl
        - nyancat-git
        - wingpanel-indicator-monitor-git
        - cppitertools
        - vr2normal
        - hpp-pinocchio-git
        - open62541-git
        - mangl
        - deadbeef-optimfrog-git
        - stack-client-bin
        - markdown
        - beansdb
        - gjdoc
        - lighttpd_minimal
        - trek
        - ros-lunar-rqt-bag
        - lib32-babl
        - hyprland-nvidia-git
        - sugar-datastore
        - mesa-nosystemd
        - lximediaserver-svn
        - mingw-w64-lapack
        - ros-indigo-hector-marker-drawing
        - dsf2flac-git
        - tmxparser-git
        - gnuplot-notk
        - solitude
        - rdd-git
        - setpgrp
        - wine-whatever
        - kydpdict
        - zbackup
        - wrapland-git
        - kopano-webapp-spellchecker-languagepack-pl-pl-git
        - sline-git
        - glosstex
        - lib32-sdl2-hg
        - texworks
        - ros-lunar-camera-calibration-parsers
        - mac-telnet
        - assdraw
        - mauikit-filebrowsing-git
        - tidb-git
        - chromaprint-fftw
        - mate-system-monitor-1.15-gtk3
        - ophidian-units-git
        - tfhe-git
        - bb
        - template-glib-git
        - liberasurecode-git
        - litecoin-daemon
        - socnetv
        - fortune-mod-twoandahalfmen
        - ros-ardent-ament-cmake-export-definitions
        - tagsistant
        - linux-cacule-rt
        - regilo
        - gst-plugins-bad-glonly
        - wxweaver-git
        - diplib-git
        - gnome-shell-extension-app-icons-taskbar
        - ros-kinetic-csm
        - kdegraphics-thumbnailers-frameworks-git
        - gdm-settings
        - sigrok-firmware-fx2lafw
        - ogmrip-webm
        - dbus-glib-git
        - crqt-ng-git
        - youtube-dlc
        - mate-themes-3.20-gtk3
        - anope
        - libexif-git
        - ros-kinetic-ros-core
        - linux-cacule-rc
        - qpdfwalker
        - soletta-git
        - xfce4-terminal-git
        - epson-inkjet-printer-201302w
        - shp2text
        - feh-git-preload
        - osgearth-git
        - vapoursynth-plugin-waifu2x-ncnn-vulkan-git
        - freemol-svn
        - apache-mod_bw
        - google-compute-engine-oslogin-git
        - syslog-ng-latest
        - ghostpp
        - linux-libre-audit
        - caffe2-cpu
        - gnome-applets
        - gmp4
        - neovim-git-ninja
        - tcpreplay-git
        - wmfsm
        - xpenguins
        - libsystemd-eudev-standalone
        - textshine
        - pokesprite-git
        - rat
        - highlighterkit
        - ros-melodic-gennodejs
        - cryptsetup-deluks
        - oculus-wine-wrapper-git
        - hax11-git
        - ros-indigo-nodelet-core
        - libcloudstorage
        - pixbufloader-vtf-git
        - migraphx
        - ros-melodic-nav-msgs
        - uci-git
        - kmesstestserver-git
        - adg-gtk-theme
        - ksshaskpass4
        - etherlab-ethercat
        - ros-ardent-tf2-eigen
        - conterm-git
        - office-runner
        - texmaker-qt4
        - lua51-cjson
        - thedarkmod
        - flashrom-git
        - amule-emc
        - sys76-kb
        - imgui
        - fastdb
        - dfu-programmer
        - jasp-desktop-git
        - fatrace
        - xdg-autostart
        - gtk2-ubuntu
        - libalpm12
        - bluez-tools-git
        - dibbler-git
        - directx-shader-compiler
        - qcomicbook-qt5-git
        - repo-util
        - plymouth-kcm
        - xcursor-retrosmart
        - transmission-svn-gtk
        - yarr-git
        - subread
        - nginx-upload-progress-module-git
        - arm-frc-linux-gnueabi-gcc-stage1
        - ros-melodic-turtlebot3-example
        - nm-tray
        - linux-uek
name: BUILD-100
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-99
