concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - zfs-dkms
        - lib32-libxdg-basedir
        - pngcodec
        - rekonq
        - mingw-w64-pugixml
        - opencpn-plugin-climatology
        - pktstat-git
        - digikam-without-akonadi-mediawiki-vkontakte
        - lib32-libsrtp
        - ocaml-curl
        - telegram-desktop
        - elemines-git
        - syn68k
        - binkd-git
        - gnome-mud-git
        - fbterm-git
        - kolor-manager-git
        - gsvg
        - esdm-git
        - blueman-git
        - kmediaplayer-git
        - zellij-selector-git
        - i3-next-git
        - ros-jade-pcl-conversions
        - binaryen
        - kmail-git
        - xmrig-donateless
        - wlanthy-git
        - liberror
        - chibi-scheme-git
        - xmrig-mo-cuda
        - switchboard-plug-applications-bzr
        - raknet-git
        - newsie
        - libldac-git
        - xmradio-git
        - openra-git
        - phylobayes-mpi
        - anbox-bridge
        - luksmeta
        - planeworld-git
        - libhandy-git
        - ros-kinetic-easy-markers
        - dump1090-mictronics-git
        - ros-jade-rqt-srv
        - diamond-aligner-git
        - bioawk-git
        - capstone-git
        - applet-window-buttons-git
        - plasma-wallpaper-asciiquarium-git
        - engrampa-1.15-gtk3
        - xorinator
        - mullerfoto-fotostar_cz
        - broadcom-wl-uksm
        - solus-artwork-git
        - epulse-git
        - serialdv-git
        - lib32-libtas
        - qtmotifextension
        - nx-plasma-look-and-feel-git
        - quazip
        - blackchocobo-git
        - openssh-gssapi
        - libserial-git
        - asterisk-espeak
        - inox
        - pwsafe-gui
        - dmenu-xresources
        - wf-extra-protos-git
        - gtetrinet
        - ttrk
        - proot-3.2.1
        - gnatcoll
        - kanla
        - asterisk-opus
        - easyssh-git
        - mingw-w64-corrosion
        - hotspot
        - ros-jade-dwa-local-planner
        - libkcoidc
        - tsocks-multilib
        - mate-panel-1.15-gtk3
        - ros-indigo-ros
        - plasma5-applets-qalculate
        - bomutils-git
        - android-ndk-22-ollvm
        - knxd-git
        - luxrender-hg
        - mstflint
        - lsl-core
        - libjit-git
        - glc-lib
        - ace
        - kholidays-git
        - lib32-flac1.3
        - nethack-git
        - libvmime
        - sdl
        - jsoncpp-cmake
        - audacity-local-git
        - busybox-custom-git
        - thunderboltd-git
        - ros-kinetic-controller-manager
        - grsim-git
        - libretro-mednafen-vb-git
        - libosmocore
        - kos
        - gnome-text-editor-without-save-dialog
        - mrtdreader
        - miranda
        - ktexteditor-fix
        - libjson
        - hash-slinger
        - php-runkit
        - openvas
        - libkface-frameworks-git
        - ros-jade-rqt-shell
        - gpredict
        - ros-melodic-rosmake
        - pcmanx-gtk2
        - linux-rt-uksm
        - gnome-control-center-nocheese
        - icet
        - vapoursynth-plugin-replaceframes-hg
        - ros-indigo-rqt-launch
        - kodi-addon-game-libretro-2048
        - ocaml-typerex
        - pvm
        - ccls-clang-git
        - albert-switch-application
        - udp514-journal
        - hunspell-de-base
        - android-x86-64-lame
        - ros-noetic-rqt-logger-level
        - vast-git
        - fontmanager.app
        - pom1
        - aeskulap
        - chromium-wayland-vaapi
        - micropython-lib-git
        - gamenetworkingsockets-git
        - kakoune.cr-git
        - plasma5-runners-jetbrains-runner
        - opencorsairlink
        - linux-vanilla-selinux-414
        - standardese-git
        - gedit-plugins-git
        - nsoq
        - file-roller2-nn
        - ethereum-genoil-git
        - libsmbios-git
        - libksba-git
        - subsurface-libdc
        - concord-git
        - tilp
        - port-protection
        - ovirt-guest-agent
        - mouse-git
        - mandown-md-viewer
        - picturesort
        - dterm
        - dune-alugrid
        - ros-lunar-interactive-marker-tutorials
        - chinadns-c
        - android-aarch64-libwebp
        - armagetronad-git
        - ps3xport-git
        - ros-melodic-image-proc
        - ros-noetic-ecl-build
        - hypervfcopyd
        - linux-raspberrypi4-aarch64
        - nrgrep
        - camlpdf-git
        - networkmanager-l2tp-git
        - vspcplay-git
        - coreboot-utils
        - sierrabreeze-kwin-decoration-git
        - blackshades-svn
        - openvino-git
        - vmd-src
        - douane-configurator-git
        - nginx-mainline-mod-headers-more-git
        - mingw-w64-sdl_net
        - gkrelltop
        - sch_cake
        - dvblast
        - file-commander-git
        - mingw-w64-yajl
        - xlsw
        - libvolk-git
        - ungoogled-chromium
        - shim-efi
        - z80dasm
        - enlightenment-fresh
        - gtkspellmm
        - gr-dab-git
        - lsw
        - openav-fabla2-git
        - libaio-git
        - ktap-git
        - stochas
        - pizmidi-git
        - ros-melodic-rosmsg
        - minecurses-git
        - nano-latest
        - mingw-w64-ffmpeg
        - nsdo-git
        - xdg-sound
        - vt_lock
        - ros-noetic-diagnostic-aggregator
        - rpclib
        - kraft-svn
        - mingw-w64-netcdf-cxx
        - libkface-git
        - alizams-qt5
        - xwrited
        - gapc-fold-grammars-git
        - linphone-desktop-git
        - truecrack-git
        - nfs-ganesha
        - retdec
        - vtk-visit
        - zeit-git
        - skalibs
        - libdill
        - fuf
        - lf-xdg
        - ros-jade-compressed-image-transport
        - cavalier-git
        - rottexpr-shareware-git
        - libnghttp2_asio
        - tsmuxer
        - kicad-i18n-git
        - varuna-git
        - knowthelist-git
        - duma
        - mpd-light
        - php71
        - gstreamer0.10-ugly
        - openmw-git
        - toxcore-git
        - chipmunk
        - bore-client-git
        - emacs-make-regexp
        - xcalib
        - firejail-noapparmor-git
        - dunnart-git
        - libserdes-git
        - uboot-rockpro64
        - entrance-git
        - vdr-recsearch
        - wolf-shaper-git
        - unvpk-git
        - x86_64-efi-pe-binutils
        - ros-noetic-geometry-msgs
        - kodi-devel-audiodecoder-snesapu
name: BUILD-142
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-141
