concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - uconfig
        - dotfonts-git
        - st-dustvoice-git
        - bugseverywhere-git
        - yersinia
        - ocaml-mascot
        - xf86-input-mtrack
        - deadbeef-lyrics-hg
        - php74-memcache
        - libretro-bsnes-mercury-git
        - lightdm-qtquick-greeter-git
        - dune-curvedgeometry
        - dpdk-git
        - libclsp-git
        - ros-melodic-image-transport-plugins
        - faddeeva-cpp
        - nvidia-340xx-ck
        - ros-kinetic-python-qt-binding
        - ros-kinetic-rtabmap-ros
        - deepin-polkit-agent-git
        - osvr-vive-git
        - libretro-fbneo
        - trayer-srg
        - audio-convert-mod
        - cutefish-statusbar-git
        - beegfs-mgmtd
        - revolution-r-open
        - gnome-shell-extension-dash-to-dock43
        - libretro-hatari-git
        - nomad-git
        - linrad-latest
        - kdegraphics-mobipocket-frameworks-git
        - mingw-w64-qwt-qt5
        - xfconf-devel
        - corgids-git
        - opengothic
        - ros-melodic-rviz
        - gnome-remote-desktop-git
        - wine-osu
        - nautilus-tmsu-rs-git
        - php80-apcu
        - ptpd-git
        - zdbsp
        - lightum-git
        - makepkg-meta
        - youtube-viewer-git
        - oqsprovider
        - fbc-git
        - ros-indigo-image-view
        - axecore
        - sind-git
        - rt_lpc-alsa
        - binv
        - mingw-w64-speexdsp
        - wolf-m7m-cpuminer-v2-raspi4-git
        - php-pthreads-git
        - augeas-git
        - arcs-tools-git
        - aseprite-git
        - gamekit-git
        - paletti
        - skychart
        - pulseaudio-equalizer-ladspa-git
        - objfw-git
        - a2png
        - fluent-bit
        - http_load
        - capture
        - clidrag
        - hfstospell-svn
        - btscanner
        - spectrojack
        - pacman-arch
        - cctz
        - opencv-gstreamer
        - obs-freeze-filter
        - libmms-git
        - mumble-snapshot-minimal
        - otpnitro
        - okular-backend-markdown-git
        - greyd
        - editorconfig-geany-git
        - plymouth-legacy
        - tio-git
        - mtscan-git
        - rocrand
        - s2geometry-git
        - freebloks-git
        - spot-on
        - clang-minimal-git
        - console-bridge
        - libretro-beetle-lynx-git
        - fpm
        - kikoplay
        - texstudio-qt5
        - qt5-wayland-nvidia-gbm-fix
        - fontdiff-git
        - libhdcd
        - git-tools
        - ros-kinetic-usb-cam
        - paraview-superbuild
        - xkbset-git
        - conky19-lua-nv
        - wmblueclock
        - ushare
        - kwiml-git
        - nodejs-10.10.0
        - task-maker
        - libarib25
        - kgamma5-git
        - libx32-flex
        - wificurse
        - fprint_demo
        - epson-inkjet-printer-201306j
        - libtinyiiod-git
        - gsl-git
        - mingw-w64-qt6-base-static-nosql
        - ros-noetic-rqt-robot-steering
        - supercollider-mkfaustplugins-git
        - chirurgien-git
        - hashclash-git
        - 64gram-desktop-no-ad
        - tpmtool
        - crun
        - serialtest
        - armake
        - gnome-shell-mobile-git
        - glew-1.13.0
        - codeblocks-svn
        - obs-downstream-keyer
        - sugar-git
        - tinyobjloader
        - slatec
        - slack-libpurple-git
        - sleuthkit-apfs
        - valum-git
        - ibus-table-tlim2
        - ros-indigo-pano-ros
        - zeitgeist-dependencies-git
        - maximus
        - pam_usermount
        - desktop-files-creator
        - qv2ray-plugin-ssr-git
        - intel-hybrid-codec-driver
        - lyricsources
        - db-4.8-raspi4-magi
        - ros-ardent-stereo-msgs
        - nightshift
        - unenigmail
        - ros-indigo-rqt-py-common
        - boinc-app-api
        - pamac-gaura-git
        - kernel-headers-musl-i386
        - gvls
        - mingw-w64-xerces-c-icu
        - traitor-git
        - halibut-git
        - magi-qt
        - graywolf-git
        - bbswitch-uksm
        - sfeed-curses
        - pbuilder-git
        - libffi-minimal-git
        - docker-machine-driver-vmware
        - nolimips-git
        - xbrzscale
        - poac-git
        - blender-2.92-git
        - wireguard-go-git
        - sniffles
        - iio-hyprland
        - timestamp
        - mtx-svn
        - ibm-sw-tpm2
        - xmltooling-c
        - shortwave-git
        - obs-vkcapture-git
        - ros-melodic-tf2-sensor-msgs
        - nbsmtp
        - dwarffortress-lnp-git
        - kernel26-web100-mipl
        - pimenu
        - molequeue-git
        - gimp-plugin-texturize-git
        - termite-bepo
        - nvi
        - etlegacy32
        - vdr-satip
        - kodi-addon-game-libretro-genplus-git
        - ros-lunar-opencv3
        - quilter-git
        - dragon-drag-and-drop-git
        - mingw-w64-meson
        - spla
        - spot-free-client-git
        - lp
        - linuxstopmotion-git
        - newspost
        - networkmanager-wireguard-git
        - aspell-git
        - ds360
        - libinput-fix101796-git
        - mingw-w64-serd
        - mingw-w64-openimagedenoise
        - ripcord-bin
        - lib32-openal-git
        - gelemental
        - swh-lv2-git
        - btrfs-progs-unstable-integration
        - dolfinx
        - libqgit2-git
        - mcpelauncher-msa-ui-qt-git
        - ros-ardent-rosidl-default-runtime
        - picotool-git
        - kcm-uefi
        - openav-artyfx-git
        - rezound-qt-git
        - warmux
        - nixnote2
        - cde
        - wwplot
        - libvpx-full-git
        - great-little-radio-player
        - sidef
        - man-pages-pl-git
        - scrap
        - mingw-w64-double-conversion
        - libpoco-basic
        - php-wxwidgets-git
        - epson-inkjet-printer-201213w
        - amqp-qtools-git
        - emacs-goby
        - setzer-git
        - pace-cli
        - unbird
        - ndt
        - xping-git
        - wmnotify
        - nquake-common
        - lib32-cunit
        - bento4
        - qtbitcointrader
        - bbrun
        - tmview
        - linux-llvm
        - lalcal
        - android-x86-zlib
        - android-x86-lame
        - lg-downloader-git
        - qt5-base-595
        - ros-ardent-std-srvs
        - mousepad-git
        - qtads
        - dowse-git
        - mysql55
        - auto-dwm
name: BUILD-69
'on':
  workflow_dispatch: ''
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-68
