concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - vcvrack-eseries
        - libfreehand
        - codec2-lpcnet
        - ros-jade-kinect2-bridge
        - freeblocks
        - wlroots-nosystemd-nox11-git
        - ros-melodic-roscpp-git
        - fake86-git
        - wxgtk-dev-314-opt
        - yeahwm
        - unidata-decoders
        - polished-map
        - f3d
        - wmdiskmon
        - sfeed
        - d-feet-git
        - openvpn-polarssl-git
        - php82-xdebug
        - mod-utilities-lv2-git
        - ros-indigo-nodelet
        - citus-git
        - android-aarch64-qt6-declarative
        - pcre-ocaml
        - crbtree-git
        - lib32-libnm-glib-nosystemd-minimal
        - lib32-tesseract
        - picket
        - nat-tcp-test-git
        - ypserv-git
        - qwinff
        - littlefly.lv2
        - lparse
        - kanshi
        - linux-threadripper-vfio
        - creduce-git
        - sshgrid-git
        - linux-multimedia-lts
        - gnome-network-displays-git
        - avrm-git
        - libinput-nomiddletap
        - fingerprint-gui
        - mindforger
        - lgogdownloader-qt5-git
        - qwtpolar
        - ros-kinetic-rqt-pose-view
        - necroedit
        - ros-jade-voxel-grid
        - xtest
        - odin2
        - heimer-git
        - peercoin-daemon
        - xf86-video-mga
        - coin-or-qpoases
        - php-dbus-git
        - ros-lunar-stereo-msgs
        - segemehl
        - freemat
        - acl-git
        - ndn-cpp-git
        - xkb-switch-git
        - xvisbell
        - libggiwmh
        - bladerf-git
        - ros-jade-nodelet-topic-tools
        - qcma
        - residualvm
        - kvirc-git-nokde
        - mutter-ubuntu
        - libssm
        - mate-power-manager-upower
        - satysfi-git
        - limesuite
        - audiotube-git
        - ncmines-git
        - rstudio-server-git
        - mingw-w64-pcsx2
        - mediagoblin-git
        - looking-glass-rc
        - smtube
        - deutex
        - simple-obfs-git
        - keyboard-configurator-git
        - soapyrtlsdr
        - laszip
        - rsp_tcp-git
        - canboat-git
        - slicd-musl
        - ephoto-git
        - autopano-sift-c
        - obconf-qt-git
        - gnome-shell-extension-screenshotlocations-git
        - freedv-svn
        - vapoursynth-plugin-fillborders-git
        - naxalnet-git
        - plymouth-nested-cryptkey
        - nightingale-git
        - mingw-w64-attica
        - ne
        - oaklisp-git
        - afflib
        - libsoup3-git
        - pantheon-print-git
        - directfb2-lite-git
        - kitinerary-git
        - ros-melodic-nodelet-topic-tools
        - gnucap-jack-git
        - kbd-git
        - kquickimageeditor
        - ros-jade-bondpy
        - ros-indigo-imu-sensor-controller
        - libretls
        - ros-kinetic-ecl-formatters
        - wmget
        - minidlna-listen-interface-fix
        - mate-backgrounds-dev
        - nowater
        - nginx-mainline-mod-geoip2
        - srb2kart-galaxy-git
        - mars2mseed
        - per
        - neomutt-autocrypt
        - ngrok-git
        - mdview
        - g9xled
        - rssh
        - disomaster-git
        - egpu-switcher
        - libqsqlcipher
        - zsh-autosuggestions-git
        - grub-git
        - fxz-git
        - joe-hg
        - linux-cacule-rdb
        - libredwg
        - cannonball-git
        - mono-addins-git
        - ros-kinetic-diagnostic-common-diagnostics
        - armv7l-binutils
        - eovim
        - vcvrack-bastl
        - lib32-libxkbcommon
        - mingw-w64-ucl
        - polylenticular.lv2-git
        - ros-melodic-rosserial-client
        - nnls-chroma
        - obs-move-transition
        - fortune-mod-chuck
        - lib32-xcb-util-renderutil
        - compleat-git
        - superlu
        - libnuml
        - intercept-git
        - gcc46
        - emacs-sly-git
        - gnu-efi-libs-fedora-git
        - swatd-git
        - sz
        - liri-materialdecoration-git
        - libsurvive
        - yadsync
        - tmate-git
        - grim-git
        - copperspice
        - qt-ffmpeg-imageplugin-git
        - cspice
        - php-ncurses
        - frequensea-git
        - jpeg-archive
        - x2vnc-no-xinerama
        - stackandconquer
        - liburlmatch
        - ros-melodic-rqt-robot-monitor
        - smile-emoji-picker-git
        - ros-kinetic-move-base-msgs
        - webdsl-eclipse-git
        - gnome-multi-writer-git
        - devkitppc-portlibs-expat
        - locale-en-ru
        - usbfluxd-git
        - dunstify
        - guile-gnutls
        - soapylms7-git
        - gydl-git
        - gnome-chess-git
        - valyria-tear-git
        - google-raiden-mod-git
        - ros-kinetic-moveit-controller-manager-example
        - share-preview-git
        - pesconvert-git
        - aws-sdk-cpp-git
        - museekd-git
        - anymeal
        - wayvnc-git
        - lib32-renderdoc-minimal
        - got-diminished
        - vivarium-git
        - artefetcher-qt4
        - nss-docker
        - pinentry-tty
        - lightdm-webkit2-greeter
        - amdvlk-git
        - qlivestreamer-git
        - ros-jade-turtle-tf2
        - fup
        - kopano-webapp-htmleditor-minimaltiny
        - zelda-nsq
        - dict-freedict-lat-deu
        - fp-multiuser
        - avogadro
        - xxdiff-hg
        - transmission-cli-ipv6
        - eigenmath-git
        - idlehack-git
        - kgraphviewer
        - avro-cpp
        - rl78flash
        - libretro-beetle-pcfx-git
        - sidplayer
        - dave-gnukem
        - doomsday
        - birdie-git
        - ardupilot-gazebo-sitl-git
        - libsigc++-patched
        - rocprofiler
        - ros-noetic-turtlebot3-example
        - ayatana-indicator-power
        - ffqueue-git
        - gush-git
        - ultrastar-manager
        - restclient-cpp-git
        - fasda
        - terbilang
        - cups-ocr
        - bubbleswm-git
        - wingpanel-indicator-datetime
        - mingw-w64-pteros-stable
        - anbox-git
        - gnuradio-iio-git
        - extension-manager
        - json-parser-git
        - lm32-elf-gdb
        - git-hg-git
        - qgmailnotifier
        - dyncall-git
        - mingw-w64-videodownloader
        - e4rat-lite-git
        - clac
        - mariadb-mainline-noconflict
        - libsexy3-git
        - mingw-w64-libev
        - can-isotp-git
        - qtviewer
        - museeq-git
        - mingw-w64-python
        - kmarkdownwebview
        - xf86-input-acecad
name: BUILD-66
'on':
  workflow_dispatch: ''
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-65
