concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - libguess
        - xf86-video-amdgpu-nosystemd-git
        - ros-jade-catkin
        - nmly
        - adns-git
        - tcprstat-bzr
        - cattle
        - libbitcoin-node
        - dell-g5se-fanctl
        - libva-minimal-git
        - vmware-auto-unlocker-git
        - nextpnr-ecp5
        - deviced-git
        - swisswatch-git
        - ayatana-indicator-keyboard
        - gba-tools
        - ssr-git
        - gnome-settings-daemon-shutdown
        - desmume-svn
        - likwid
        - eternalterminal
        - linux-mainline-um5302ta
        - netvirt-agent-git
        - lib-fast-winding-number
        - ark-git
        - kernel-headers-musl-arm
        - flow-pomodoro
        - ros-indigo-hector-trajectory-server
        - wesnoth-1.8
        - elfexec
        - hfsprescue
        - ros-lunar-depth-image-proc
        - alchemy-next-viewer
        - php56-memcache
        - obs-command-source
        - paulfrische-dmenu-git
        - xmedcon-extra
        - heasoft
        - trueport
        - ejtagproxy-git
        - littler-git
        - gkrellm-fchart
        - gfxtablet-git
        - strawberry-qt6
        - wmcdplayer
        - libbfio
        - gstpeaq
        - spotblock-git
        - go-cross-major-platforms
        - lsdn-git
        - avahi-nosystemd
        - tracemonkey-hg
        - elkhound-git
        - hawaii-wallpapers-git
        - coqide
        - cutefish-launcher-git
        - gnome-shell-extension-windowoverlay-icons-git
        - elflibviewer
        - libaudec
        - huaweicloud-obs-obsfs-git
        - homegear-max
        - darling-git
        - jim
        - ros-indigo-rviz-animated-view-controller
        - uzbl-git
        - libzypp
        - ifbabel
        - thc-ipv6-git
        - mingw-w64-zstd-static
        - libxmp-aarch64-git
        - wayshot-musl-git
        - block-attack
        - connect
        - g2o-git
        - libcint-git
        - notion-neg-git
        - steel
        - binwalk
        - millionaire-git
        - od-libopendlv-git
        - ros-lunar-rosbash
        - libicu53
        - nmh-git
        - ashpd-demo-git
        - coin-or-hsl
        - dcm2niix
        - linux-xanmod-rt54
        - sixad-git
        - mpd-notification
        - liblwipv6
        - xfce4-equake-plugin
        - zmusic
        - bash-devel-static-git
        - distro-info
        - hare-specification
        - freetds-patched-enum
        - openenroth-git
        - meld-gtk2
        - fortune-mod-blackadder
        - sfbrename-cli
        - nutty-git
        - qml-material
        - xkeyboard-config-rub
        - you-get-git
        - libav-no-libs
        - bones
        - loggedfs-git
        - arxlibertatis-git
        - purc
        - maia-gtk-theme
        - svr
        - mpc-qt-git
        - libyami-utils
        - tuxonice-userui
        - cpuminer
        - lib32-freetype2-minimal-git
        - sdl-openglhq-nokbgrab
        - malbolge-disassembler
        - hpfall-git
        - libtextstyle-git
        - qtalarm
        - libmtp-gvfs-git
        - jitterentropy-git
        - kamoso-git
        - st-anyway-git
        - spacefm
        - libretro-pocketsnes-git
        - qt6-quickcontrols2
        - ring-daemon-git
        - stm32flash
        - libx264-142
        - n-m3u8dl-re-git
        - ros-melodic-rosbash
        - libtxc_dxtn
        - input-leap-git
        - timegen
        - libreoffice-style-elementary
        - sgrep
        - gmfsk
        - ignition-transport-8
        - mingw-w64-qt5-quickcontrols-static
        - ros-noetic-eigen-conversions
        - airwindows-git
        - foonathan_memory-shared
        - hybridreverb2-git
        - deepin-screenshot-copy-patch
        - libscrypt
        - geth-git
        - asignify
        - timeprefix
        - openexr_viewers
        - linux-pf
        - epson-inkjet-printer-201113j
        - lib32-libndp
        - lib32-imath
        - amule-dlp-git
        - pkg2zip-fork
        - signus-git
        - suck
        - cell
        - space_dapp
        - activityfox-git
        - mingw-w64-netcdf-cxx-legacy
        - epson-inkjet-printer-px-602f
        - pal-git
        - qt5-quickcontrols2-git
        - ros-melodic-bond-core
        - libdockapp
        - dynarmic
        - ros-kinetic-geometry-msgs
        - pam_nfc-git
        - wineasio
        - autofs-nfsfix
        - vcvrack-alliewayaudio-freebies
        - pure-ftpd
        - offlineimap3-git
        - mingw-w64-spirv-cross
        - ckmame
        - sweep-sdk
        - libretro-mednafen-pce-fast-git
        - shin-git
        - ps2-sdl_mixer
        - ahab
        - libasi
        - cbmconvert
        - arena-tracker-git
        - cnijfilter-mg3200
        - php-ui
        - password-for-gnome-vala-git
        - pscpug
        - mod-host-git
        - pg_top
        - dfl-wayqt
        - cc-proxy-git
        - cammill
        - n64-git
        - xcfun-pyscf
        - sticky-git
        - zfs-dkms-git
        - uefi-shell-svn
        - bspwmbar
        - qmarkdown-git
        - acarsserv-git
        - sddm-config-editor-git
        - xfwm4-hover-inactive
        - firefox-passff-git
        - edlin
        - debhelpergit
        - ctags-fishman-git
        - wxlua
        - xdg-desktop-portal-kde-git
        - tifig-git
        - library50-c
        - fortune-mod-quantumleap
        - fluxengine-git
        - gnome-twitch-player-backend-mpv-opengl-git
        - ros-noetic-moveit-plugins
        - libecbor
        - oggted
        - linux-lts314-ck
        - glimpse
        - advtty-vcom
        - memstat
        - epson-inkjet-printer-stylus-office-tx510fn-series
        - openclonk-git
        - opendmarc-libspf2
        - civetweb
        - php54-memcache
        - arc-cyberfox-theme
        - ros-lunar-rqt-py-console
        - lib32-eatmydata
        - jack_capture-git
        - libarmedia-git
        - swapspace
        - mutt-hg
        - addresses
        - linrad
        - unbrave-git
        - yabridge
        - hip
        - photospline
        - xsetwallpaper-git
        - goxel
        - massif-visualizer-git
        - plasma5-applets-todolist
        - gtkhash-nautilus
        - freeorion
        - comparepdf
        - gazebo-ogre-1.10
        - ad3
        - php7-systemd
        - salarm-git
        - kmbox-git
        - vegastrike-py2-engine-git
        - faad2-git
        - dcdfort
name: BUILD-54
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-53
