jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - zerotier-one-git
        - panomatic
        - json-fortran
        - mingw-w64-qt5-networkauth-static
        - djmount
        - envview
        - ros-jade-dynamic-edt-3d
        - st
        - cgit-git
        - liboggz-git
        - geos-php
        - caffeinated
        - mingw-w64-qt5-winextras
        - x-corners
        - ros-melodic-ecl-time-lite
        - svg2png
        - matio
        - snapcast
        - akonadi-decsync-resource-git
        - kmarkdownwebview-qt5webkit
        - qt5-style-kvantum-svn
        - discord-rpc-api
        - minidjvu
        - gladrags-gtk3-git
        - liri-wallpapers-git
        - gnome-screensaver
        - tintin-git
        - libretro-snes9x2002-git
        - ros-indigo-joint-trajectory-controller
        - vice-sdl2-svn
        - knossos
        - xlivebg-git
        - lstune-git
        - qownnotes
        - mingw-w64-libsoup
        - libmodbus-dev
        - supercollider-bytebeat-git
        - muse-git
        - gnome-sound-recorder-git
        - pg_tle-git
        - hmmer2
        - samplebrain-git
        - plasma5-applets-tempreader-widget-git
        - keme
        - occt-webgl-viewer
        - jag
        - gnome-settings-daemon-nvidia-backlight-patch
        - emutools
        - mytetra
        - sipp
        - goonies
        - asekey
        - moc-svn
        - gdtoa-desktop-git
        - raditcast
        - juffed
        - cfiles
        - meteor-demod-git
        - gnome-weather-git
        - do-agent-git
        - openvpn-x509-alt-username
        - sysvinit
        - openstreetcam-gui
        - nemo-repairer
        - lastfm
        - heimdallr-git
        - frama-c-git
        - libcurl-gnutls
        - gtk-vector-screenshot
        - mingw-w64-qt6-quicktimeline
        - evince-lcd-standalone
        - gvisor-tap-vsock
        - gr-rds-git
        - arcus
        - acpi_call-git-dkms
        - injures-git
        - datemath
        - mingw-w64-gst-plugins-base
        - nitrofs
        - foosynth-plugin-neo_minideen-git
        - mkpasswd2-git
        - pam_captcha
        - kimageannotator-git
        - yuzu-early-access
        - dmenu-vus-git
        - nanosvg-git
        - abseil-cpp-git
        - badvpn-git
        - vtk9-java
        - patchance
        - qbittorrent-qt5
        - ros-noetic-rtabmap-ros
        - ros-noetic-rotors-gazebo
        - libretro-lrps2-git
        - linux-firewire-utils
        - nvui
        - mingw-w64-libpng-static
        - bindmap-git
        - hdf5-mpich-java
        - libbde
        - suil-git
        - mgw
        - hip-clang
        - theslate
        - nginx-mainline-addon-echo
        - ros-jade-polled-camera
        - libodiosacd-bzr
        - avant-window-navigator-git
        - radit
        - lbm-git
        - ros-noetic-mavros-msgs
        - statping-ng
        - lotech-git
        - ros-jade-librviz-tutorial
        - pdf2htmlex
        - ros-kinetic-bondcpp
        - i686-elf-gcc-aarch64
        - pods-git
        - libgbinder
        - cbmbasic-git
        - freedns-go-git
        - tubefeeder
        - zenity-gtk2
        - lprngtool
        - ros-indigo-yocs-controllers
        - glc-player
        - istatd
        - dynamic-wallpaper-git
        - libfreexl-devel
        - libglibutil
        - clap-host
        - obs-studio-liushui-git
        - gimp-brush-max-512
        - nextpad-git
        - mecab-git
        - lxqt-appswitcher-git
        - kgx
        - rumur
        - joy2key-git
        - pulseaudio-modules-bt-git
        - purple-gowhatsapp-git
        - gnome-common-git
        - tlstunnel
        - ros-indigo-rosping
        - meld-git
        - bindechexascii
        - vivado
        - pcmanfm-qt6-git
        - libafterimage
        - labyrus-git
        - ros-ardent-rviz-rendering-tests
        - hexdiff
        - gmpc-git
        - return-to-the-roots
        - riscv64-unknown-elf-gdb
        - libindi-astrolink4
        - async++-git
        - xlnt
        - android-aarch64-xz
        - readline7
        - pacemaker
        - dxvk-mingw-proton-ge-async-git
        - timer-git
        - matray-git
        - ros-jade-rviz-python-tutorial
        - lsl-imaging
        - lib32-schroedinger
        - rsb-cpp-stable-git
        - linux-jwrdegoede
        - libtga
        - solbuild
        - dxfaktura
        - rp-pppoe-git
        - geo
        - libgcrypt15
        - swift-development
        - contrafold
        - libghemical-mpqc
        - websocketpp
        - btusb-qca-0x3004
        - nct6775-ck-git
        - furnace-git
        - csprng
        - ffmpeg0.10
        - stitchy-git
        - grilo-plugins-git
        - kopano-webapp-desktopnotifications-git
        - pinkie-pie
        - extractpdfmark
        - tetris
        - spherical-cow-backgrounds
        - pgadmin3-lts
        - cmvs-pmvs-git
        - lightdm-devel
        - libaosd-xinerama-git
        - libghttp
        - vdr-tvguideng
        - libx32-libx11
        - libodb
        - pacana
        - swaybg-git
        - qcma-kdenotifier
        - lib32-libshout
        - emacs-git-shallow
        - deepin-dock-plugin-neoweather
        - ros-indigo-rqt-robot-dashboard
        - apertium-isl-swe
        - glpi-agent
        - purple-battlenet-git
        - mingw-w64-qt5-3d-static
        - rofi-code-git
        - emacs-libegit2-git
        - nethack4
        - deal
        - ros-noetic-resource-retriever
        - liftbridge
        - sdb
        - gstreamer0.10-bad
        - deheader-git
        - clicraft
        - openmodelica
        - invada-studio-plugins-lv2
        - alltray-scriptable
        - gstreamer0.10-python
        - loudmouth-ossl
        - bamr
        - imx-usb-loader-git
        - vala0.40
        - lib32-libart-lgpl
        - gnupg1
        - mariadbpp-git
        - deeponion
        - retroshare-svn
        - telepathy-qt-git
        - croco-live
        - cataclysm-dda-tiles
        - qt4-ubuntu
        - wol_qt
        - ros-indigo-diagnostic-msgs
        - ros-lunar-xmlrpcpp
        - lorcon-git
        - batch-git
        - mingw-w64-sqlite
        - sombok
        - subtitleeditor-git
        - tagainijisho-git
        - liblogicalaccess-git
        - landrop-git
        - numix-themes-git
        - kcmsystemd-kde4
        - aursec-git
        - cutelyst
        - cdparanoia-overread
        - volume.app
        - php-decimal-git
        - ros-noetic-rqt
name: BUILD-72
'on':
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-71
