jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - randomx
        - netfleet
        - kdeltachat-git
        - linux-nc
        - wmmp
        - obs-studio
        - desktop-webmail
        - lib32-l-smash
        - lib32-libdbusmenu
        - dumpet
        - krpc-cpp
        - nginx-mainline-mod-fancyindex
        - openssl-1.0-chacha20
        - paulxstretch
        - fmit-git
        - linux-dragon
        - sidplay-libs
        - yamagi-quake2-ref_vk
        - quickddit
        - certspotter-git
        - libclc-git
        - icon
        - qml-material-git
        - avr-libc-16
        - kde2-kdeartwork-git
        - iptckwed-git
        - dantalian
        - lib32-gtkmm
        - engauge-git
        - openstack-guest-agents-unix
        - lycklig-git
        - et-sdl-sound
        - skm
        - lib32-chromaprint
        - goodvibes-git
        - openttd-jgrpp
        - lxqt-archiver-git
        - spectemu
        - libubox
        - libcommuni
        - kopano-libvmime-git
        - libhangul-git
        - qzdl-git
        - nuovext-icon-theme
        - deadbeef-pipewire-plugin-git
        - qtum-core-aarch64
        - drawterm-hg
        - conky-audacious
        - writerperfect
        - go-tun2socks
        - libmpsse-python3-git
        - kisslib
        - tttt
        - mellowplayer-kde
        - gnome-rdp
        - xware-desktop
        - nuvola-app-spotify
        - plocate-git
        - avrdude-bobdude
        - qemu-full-aarch64-git
        - lib32-qt4
        - opencpn-git
        - marble-qt-git
        - plctool-git
        - linux-wifi-hotspot
        - libcurl-compat-nostatic
        - espeak-ng
        - vapoursynth-plugin-fmtconv-git
        - hmtimer
        - ros-kinetic-rqt-graph
        - emacs-jabber-git
        - ffgo-git
        - audacity-git
        - xfce4-hamster-plugin
        - wine-no-pe
        - pgadmin4-last
        - rrthomas-libpaper
        - nxpolkit-git
        - gauge
        - cage-git
        - php-32bits-fixes
        - qt5gtk2
        - caffeine-ng-git
        - dcalc
        - erofs-utils-git
        - qt5ct-svn-translucent
        - mingw-w64-async++-git
        - backports-patched-bcma
        - xrootd4
        - pmc-git
        - qpdfpresenterconsole
        - vegastrike-engine-stable-git
        - mingw-w64-libevent
        - cowfortune
        - 6pm
        - android-x86-libssh
        - profile-sync-daemon-git
        - mingw-w64-libidn
        - vix-git
        - ros-kinetic-rosbag
        - cnijfilter-mx920
        - spl-utils-archiso-linux
        - gmult-git
        - fastc-git
        - krename-git
        - v8-3.15
        - celeste
        - curvetun
        - lua-miniflac
        - deadbeef-plugin-discord-git
        - doctest
        - php74-openswoole
        - lib32-libid3tag
        - gnome-shell-extension-backlight-control
        - ros-indigo-turtlebot-apps
        - gnome2-icon-theme-extras
        - psp-pspirkeyb
        - xapian-tcl-bindings
        - basis-universal
        - git-annex-git
        - ros-melodic-roslz4
        - pam_mount-git
        - xdebug7
        - arm-linux-gnueabihf-binutils
        - wmcpuwatch
        - viking-git
        - patchance-git
        - oglplus
        - wireguard-module
        - eepkeyer
        - kvirc-git
        - taigo
        - zarafa-server
        - utox-multidevice-static-git
        - mythtv
        - solid-git
        - adwaita-custom-cursor-colors
        - gdnsd
        - securecopytools
        - themerrr
        - freetype2-old-hinting
        - wtfutil
        - cstitch-git
        - mod_perl
        - coregarage-git
        - midi-matrix-lv2
        - logdoctor
        - xf86-video-dummy-xpra-patch
        - openclonk
        - powerpc64le-linux-gnu-gcc
        - gimp-plugin-resynthesizer-git
        - bootloadhid
        - findimage
        - lxtask-git
        - xde-menu-git
        - m68k-elf-newlib
        - jkmeter
        - cmocka-git
        - kate-kde4
        - ros-lunar-gazebo-dev
        - libwebp2-git
        - ayatana-indicator-sound
        - cheesecutter
        - lthemeengine
        - crash-lzo-git
        - nemu
        - ros-indigo-python-qt-binding
        - openmpi-gcc8
        - emath
        - vapoursynth-plugin-it-git
        - ros-indigo-cpp-common
        - enigma_sdl
        - libretro-bsnes-git
        - qflipper-git
        - ocelotgui
        - ttygif
        - deadbeef-git
        - libcineform
        - qperf-nordma
        - mingw-w64-yaml-cpp
        - rocm-bandwidth-test
        - g15stats
        - tupi
        - wget-xdg
        - gromacs-mpi
        - st-git-tic
        - ktextwidgets-git
        - gspiceui
        - repmgr
        - libdisplay-info-git
        - lightdm-mini-greeter-git
        - jpmidi
        - pulseaudio-bluedio
        - safe-iop
        - avxsynth-plugin-fft3dfilter-git
        - gnurobbo
        - dynamips
        - tntdb
        - kwooty-frameworks-git
        - gnuscope
        - gnome-tour-git
        - alsa-lib-audacity-pulseaudio-fix
        - qt5-quickcontrols-595
        - imvirt
        - phosh-mobile-settings
        - i3-kde
        - scannerextract
        - munipack
        - kalzium-git
        - pollymc
        - linux-cacule-garuda
        - prison-git
        - xorg-xdm-xlogin-git
        - buildg-git
        - libtorrent-rasterbar-1
        - ros-noetic-joint-state-controller
        - arsenic
        - php73-geoip
        - proxygen
        - lorem
        - fbdesk
        - core-lightning-git
        - purc-git
        - ros-kinetic-nodelet
        - cp2k
        - flow-tools
        - efl-git
        - kdeplasma-applets-stdin-svn
        - rocm-core
        - xf86-video-intel-mir
        - fqgrep
        - zim-bzr
        - lunar-date
        - cutycapt
        - clevo-wmi-dkms-git
        - gsteg
        - ot-commissioner-cli-git
        - ce
        - prometheus-speedtest-exporter
        - serveez
        - spdlog_setup
        - gimp-webp
        - recoll-with-recollq
        - mozc-ut-united
        - nvfand-git
        - sipgrep
        - 2048-terminal-git
        - gtknodes-git
        - webcamstudio-module
        - arx-libertatis-git
        - eiskaltdcpp-git
        - guile-sdl2-git
        - tigervnc-server
        - ros-lunar-resource-retriever
        - deeptags
        - lib32-libxmp-git
name: BUILD-145
'on':
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-144
