concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - flowerss-bot
        - kmailapplet-git
        - pt3-drv
        - cwm-git
        - lib32-oxygen-gtk2-git
        - java8-openjdk-hsdis
        - foo2zjs-minimal-nightly
        - falltergeist-git
        - rbfeeder-git
        - last-resort
        - libsafec
        - ballerburg
        - iojs-git
        - bbswitch-uksm-ck
        - xtables-addons-rawnat
        - mawk2-git
        - hxl-git
        - vidalia
        - ippusbxd
        - zfs-linux-rc
        - darkhttpd-git
        - inox-edgy
        - unicon
        - compton-old-git
        - apertium-isl-eng
        - esekeyd
        - con2fbmap
        - pantheon-files-bzr
        - kata1-containers
        - ros-noetic-rotors-joy-interface
        - nuvola-app-amazon-cloud-player
        - tuner
        - libmikmod-git
        - avm
        - lua-luaogg
        - program-shell-git
        - st-scrollback-git
        - im-emoji-picker-ibus-git
        - vapoursynth-plugin-bm3dcuda-cpu-git
        - znc-backlog-git
        - xbat
        - plasma-pass-git
        - mingw-w64-qt6-declarative
        - remind-me
        - supercollider-headless-git
        - libcmb
        - dovecot2-antispam-hg
        - jamin-gtk2
        - simtrace
        - playmyvideos
        - realmd
        - ginger-git
        - pam_wrapper
        - vnote
        - cs-libguarded
        - zorin-appgrid-lite
        - sdlblocks
        - tuxclocker-git
        - powder-toy-snapshot
        - java-inetlib
        - brunsli-git
        - mercury
        - bcwc_pcie-git
        - higan-qq
        - r352
        - navidrome-git
        - whatmask
        - st-luke-git
        - winregfs-git
        - ros-melodic-gps-common
        - kissplayer
        - sdrangel_no_xtrx-git
        - mate-applets-gtk2
        - pluma-gtk2
        - sysrqd
        - android-x86-64-libvorbis
        - glimpse-editor
        - geomspace
        - ufiformat
        - gst-plugins-opencv
        - ros-melodic-rosnode
        - niftyreg
        - epson-inkjet-printer-201111w
        - ros-indigo-ros-base
        - nginx-mod-dav-ext
        - toggldesktop
        - ros-kinetic-twist-mux-msgs
        - jconvolver
        - simple-diary-gtk-git
        - dlib
        - sdrpp-tetra-demodulator-git
        - nheko-git
        - infinisql
        - fcitx5-configtool-git
        - stone-phaser.lv2-git
        - resp
        - libblip_buf
        - ros-noetic-interactive-markers
        - dict-freedict-deu-fra
        - nickvision-application-git
        - linux-drm-intel-testing-git
        - cinelerra-gg-git
        - edi
        - sysfence
        - emu2-git
        - gnome-firmware-git
        - mingw-w64-muparser
        - stilo-themes-git
        - calculix-cgx
        - wire
        - virtlyst
        - mingw-w64-spirv-tools
        - ros-kinetic-libuvc-ros
        - beye
        - opentimelineio-git
        - evdevhook-git
        - sushi-git
        - hydrajoy-git
        - cmtp-responder-git
        - scd
        - verifybamid
        - kubeless-git
        - ptxdist-2018.02
        - opusfile-git
        - rapidcheck
        - jtc
        - gdm-plymouth-nox
        - avcut-git
        - linux-cx2072x
        - kdoctools-git
        - sysbox-ce-git
        - txr
        - dwm-ekollof-git
        - tntnet
        - mesa-steamos
        - comtrol-rocketport-express-infinity
        - pcmanx-gtk3-git
        - xfce4-appfinder-git
        - tfautomv
        - openswan
        - libmcs
        - orocos-kdl-git
        - diogenes
        - libomxil-component-xvideo
        - proftpd-git
        - plainpanel
        - supermin-git
        - myipd
        - qtractor-git
        - ros-ardent-rcl
        - html2text-cpp
        - chocolate-doom
        - cutemarked
        - dtc-python2
        - foomatic-db-foo2zjs
        - xruncounter-git
        - pylibcoopgamma
        - nuvola-app-8tracks
        - ros-noetic-robot
        - openmpi-slurm
        - needrestart-git
        - shutter-bzr
        - ros-melodic-turtlebot3-slam
        - emacs-d-mode
        - mingw-w64-qt6-serialbus
        - bitcoin-headless-addrindex-git
        - pure-octave
        - kicad-git
        - barrier
        - gammu-json
        - qca-qt5-git
        - apertium-fr-ca
        - myodbc
        - ksnapshot-frameworks-git
        - freerdp-102
        - aarch64-linux-gnu-binutils
        - xde-styles
        - tubefeeder-git
        - shuttlepro-git
        - bamtools
        - skype-call-recorder
        - kodi-devel-libcec
        - resin-pro
        - libui-ng-git
        - simulide
        - i386-elf-gcc
        - fb-adb-git
        - turbodiary
        - qtermwidget-cjk-git
        - intel-svt-av1
        - enventor-git
        - nginx-mainline-addon-srcache
        - android-aarch64-qt6-connectivity
        - satellite-decoders
        - evolution-on-appindicator
        - xlivebg
        - radiotray-ng-git
        - yorick-yutils-git
        - qtinline-git
        - ipwatchd-gnotify
        - eolie-next
        - bib2x
        - jellyfish-pythonbound
        - pngcrush-bundled
        - pg_qualstats-git
        - clhep
        - mcpelauncher-thesonicmaster
        - freetype2-infinality-ultimate
        - filelight-git
        - gnubik
        - cmus-git
        - epson-inkjet-printer-ep-703a
        - spl-linux-headers
        - crystal
        - yt-dlp-git
        - lumail
        - wmbluecpu
        - optimus-manager-qt-kde
        - rf24-network
        - pacstats-hg
        - ros-melodic-rqt-nav-view
        - inspircd
        - gst-plugin-pipewire-git
        - ros-noetic-trac-ik-kinematics-plugin
        - nsxiv
        - immer-git
        - dragonplayer-git
        - pikaur
        - sysjitter
        - pidgin-recent-contacts-git
        - oscar-git
        - lib32-libmodbus
        - ros-ardent-examples-rclcpp-minimal-composition
        - switchboard-plug-about-bzr
        - dlm-git
        - pure-pcre-git
        - kicad-nightly
        - fs2_open-git
        - mess822
        - libutvideo-asm-git
        - kmpcore-git
        - mingw-w64-cblas
        - elfy
        - open-lldp
        - sometris-git
        - supercollider-graphloopgrain-git
        - sonic-visualiser3
        - linsim
        - torodofi-git
        - vpnc-fortigate
        - xlauncher
        - oacapture
        - dynd
        - ros-melodic-ddynamic-reconfigure
        - android-simg2img
        - go-bee
name: BUILD-8
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-7
