concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - zthread
        - miniupnpc-git
        - man-pages-fi-git
        - manpager
        - surge-xt
        - daemon-engine
        - moksha
        - libcal
        - gkrellsun
        - sensors-lxpanel-plugin
        - linux-mainline-bcachefs-lts
        - squeeze-git
        - squid5
        - openscenegraph-2.8
        - ros-lunar-nodelet-core
        - libcutl
        - nemesis
        - qmidictl
        - photoflow
        - appstream-glib-git
        - flac123
        - kodi-platform
        - git-remote-bzr
        - mingw-w64-popt
        - kn0ck0ut-lv2-git
        - kmediaplayer
        - mingw-w64-tinyxml
        - complx
        - autowiring
        - emacs-pgtk-git
        - airtame-streamer
        - tic-80-lovebyte-git
        - ros-ardent-lifecycle
        - xvidcap
        - mingw-w64-zfp
        - ros-melodic-kalman-filter
        - linux-libre-grsec-knock
        - emacs-harfbuzz-git
        - libadwaita-git-pkgs
        - android-x86-64-strace
        - wxgtk-dev
        - elixir-git
        - xfce4-i3-workspaces-plugin-git
        - opendoas-git
        - luksmeta-git
        - nidhugg-git
        - amgcl-git
        - lib32-gstreamer0.10
        - cairo-infinality-remix
        - linux-hp-envy-x360-git
        - waterfox-classic-git
        - gadap
        - stumpwm
        - tumblrtv-xscreensaver
        - libhomegear-ipc
        - libadios
        - check_postgres
        - wattsi
        - ros-melodic-opencv-apps
        - openblok
        - sylpheed
        - kde-gtk-config-kde4
        - csmith-git
        - genie-systemd-git
        - lua51-pam
        - psi-plus-plugins-git
        - t4kcommon-git
        - zlib-zpipe
        - blender-plugin-syncaudio-git
        - firefox-kde-opensuse
        - opencpn-plugin-polar
        - vis-standalone
        - libmfile-git
        - ros-noetic-pluginlib-tutorials
        - xbelld
        - gmux_backlight
        - rainbow-lollipop-git
        - sys-hostaddr
        - libnss-unknown
        - armv8l-linux-gnueabihf-glibc
        - devkitppc-portlibs-libjpeg
        - labelmanager-git
        - cppgraphqlgen
        - corefm
        - synergy-free
        - oomd
        - timekeeper-git
        - proxychains-ng-multilib
        - hashlibpp
        - last-mission-sdl
        - gsi-sshterm
        - amule-gtk3
        - viewnior-git
        - libnss-extrausers-git
        - nginx-mod-nchan
        - catfish-python2
        - mingw-w64-uchardet-git
        - flobby-git
        - serval-dna-git
        - mingw-w64-libtool
        - axoloti-runtime-git
        - muffin-git
        - obs-studio-git
        - libzlog
        - android-x86-64-libtheora
        - polkit-no-script-git
        - transmission4
        - lib32-openmp-rc
        - scantools
        - taskopen
        - miniyacc-git
        - libexude
        - ndyndns
        - postgis-sfcgal
        - barrier-headless-git
        - dfzitarev1
        - shuttlepro-v2-git
        - libplasma
        - manatee
        - thunar-archive-plugin-gtk2
        - ros-noetic-rostopic
        - ton-git
        - properties-cpp
        - spreed-webrtc-server-git
        - bassoon
        - php80-rar
        - xml-security-c
        - abook-git
        - kodi-matrix-git
        - sdtool
        - xfdesktop-git
        - fortunereader
        - roger-router
        - jsonrpc-glib-git
        - scite
        - ros-noetic-unique-id
        - kcheckers
        - ros-kinetic-visualization-marker-tutorials
        - pd-else
        - openctm-tools
        - nodemcu-firmware-git
        - libsdformat-hg
        - riscv-sifive-elf-newlib
        - innoextract
        - obs-hevc-vaapi-git
        - group-service
        - raspi-gpio-git
        - cnijfilter2
        - ros-noetic-smach-msgs
        - playonlinux
        - fancontrol-kcm
        - ros-melodic-rosboost-cfg
        - apt-git
        - phonon-qt4-mplayer-git
        - libxfont
        - simgear
        - visual-sfm
        - gpa-git
        - musepack-tools
        - vapoursynth-plugin-nnedi3cl-git
        - zukitwo-themes-git
        - libtorrent-rasterbar-1_2-git
        - gfm
        - gradio
        - autofdo-git
        - ros-noetic-slime-ros
        - ngsxfem-git
        - stc8prog-git
        - imp-git
        - bbswitch-lts
        - npapi-vlc-git
        - xr-hardware
        - ros-ardent-logging-demo
        - ttyd-git
        - ovmf-svn
        - mingw-w64-qt5-xmlpatterns
        - netplug
        - riscv-fesvr-git
        - tinymembench-git
        - ros-indigo-rosserial-windows
        - ros-ardent-ament-cmake-export-dependencies
        - auralcap
        - podiff
        - sassc
        - libcgif
        - spirv-tools-git
        - lxde-common-gtk3
        - firefox-theme-adwaita-git
        - kgeotag
        - rsb-tools-cl-stable-git
        - buzztrax
        - tactics
        - system-tools-backends
        - cppformat
        - rfdump
        - skipfish
        - librtfcomp
        - hubrelease
        - salome-geom
        - bspwm-git
        - xonotic-git
        - cantarell-static-fonts
        - tizonia-all
        - ros-noetic-gazebo-ros-control
        - nvramtool-corevantage-git
        - ros-indigo-librealsense
        - graph-drawer
        - slock-git
        - opencpn-plugin-oesenc-git
        - auto-07p-git
        - zlib-git
        - smc
        - gtksu-git
        - kak-lsp-git
        - sugar-artwork
        - necpp-git
        - ros-indigo-qt-gui-cpp
        - fuse-nx-git
        - tvtime-alsa
        - hellcat-git
        - sirit-git
        - viper4linux-gui-git
        - brother-dcp-9020cdn
        - briar-gtk-git
        - als-controller-git
        - mingw-w64-miniglog
        - fruit
        - libretro-flycast-git
        - kime-bin
        - notepadqq-ote-git
        - avisynth-plugin-yadifmod2-git
        - rivet-git
        - plasma5-applets-supergfxctl
        - vlc-vr-git
        - mpv-amd-full-git
        - cpp-netlib
        - wlr-sunclock-git
        - libmatthew-unix-java
        - jamesdsp
        - twister-core-git
        - yakuake-frameworks-git
        - xfce4-power-manager-git-xsccomp
        - jpegtran_crop
        - bully
        - ros-lunar-catkin
        - alsa-utils-transparent
        - xfburn-git
        - gnucap-python-git
        - bbswitch-ck-fbcondecor
        - mingw-w64-pybind11
        - mailimporter-git
        - serial-git
        - mingw-w64-sdl2_net
        - firmata-test-git
        - opm-common
        - ft2-clone
name: BUILD-21
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-20
