concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - ros-indigo-rosgraph-msgs
        - signing-party-svn
        - kde1-kdemultimedia-git
        - pinephone-dev-tools
        - libretro-mame2003-git
        - idsk
        - agenda
        - icewm-utils
        - qtermwidget-git
        - factortime-git
        - deadbeef-plugin-vk
        - llvm36-split
        - qgis-ltr3
        - lib32-libtiff5
        - ftnchek
        - obs-backgroundremoval-git
        - librttopo-devel
        - kcrap
        - qt5-declarative-git
        - tdom-git
        - quiterss-qt4
        - ttylog
        - dale-git
        - osl-git
        - linux-cacule-llvm
        - bcl2fastq
        - ocaml-ocamlgraph
        - avr-fboot-git
        - ebu
        - gnome-music-git
        - tmux-git
        - mgetty-vgetty
        - ros-noetic-genlisp
        - rocprim
        - ipad_charge
        - linux-zen-grsec
        - mp3blaster
        - openfx-gmic-git
        - ros-indigo-velocity-controllers
        - man-pages-nb-git
        - ros-indigo-rocon-apps
        - ros-indigo-kdl-parser-py
        - polo-git
        - ubgpsuite-git
        - r8168-uksm-ck
        - cosfs
        - sevensquare-git
        - google-authenticator-libpam-git
        - libqaccessibilityclient-git
        - libaxolotl-c-git
        - jeff
        - zip-natspec
        - timezone-clock
        - ros-noetic-rosclean
        - mingw-w64-qt6-shadertools
        - xinput_calibrator
        - makefile2graph
        - belcard
        - paexec
        - gwsocket-git
        - atl-git
        - gincoin-qt
        - darktable-cr3
        - kldap-git
        - dosbox-staging
        - ros-indigo-visualization-tutorials
        - strongswan-nosystemd
        - hipify-clang-git
        - aerospike-client-c-libevent
        - cvassistant
        - chromasig-seq
        - qt5-tools-595
        - opencv-with-python2-support
        - gnome-control-center-vrr
        - dantalian-git
        - turbomem-git
        - nopoll-git
        - roswell-git
        - sonic-pi
        - gatling
        - mono-git
        - rakarrack-plus
        - mingw-w64-qt5-svg
        - pinecil-firmware-updater-git
        - utimer
        - 86box
        - flopoco
        - piper
        - st-sane-defaults
        - tlf
        - slockd
        - switchboard-plug-locale-git
        - n-ipv4ll-git
        - avisynth-plugin-medianblur2-git
        - pissircd-git
        - hentaiathome
        - ros-melodic-tuw-geometry-msgs
        - ros-kinetic-gennodejs
        - php80-zts
        - postgresql-git
        - ros-melodic-joy-listener
        - guglielmo
        - qtforkawesome-git
        - ros-kinetic-pluginlib
        - libcoap
        - ethercoin-qt-git
        - beehive
        - switchboard-plug-power
        - obs-scene-notes-dock
        - pk2dft
        - fuzzel-git
        - aarch64-linux-gnu-lz4
        - ros-noetic-imu-sensor-controller
        - cornas-git
        - rwc-git
        - openrtm-aist
        - aegisub-japan7
        - handbrake-no-qsv
        - libevent-compat
        - gimp-plugin-mathmap
        - cv-git
        - ros-indigo-rosclean
        - ketm
        - loudgain-git
        - seashell-git
        - infer
        - plasma5-applets-nx-networkmanagement
        - arm-linux-gnueabihf-gcc
        - confclerk-git
        - waifu2x-converter-qt-git
        - libbitcoin-explorer-git
        - uxplay-git
        - pcsx2-plugin-usbqemu-wheel
        - xzoom
        - fluff
        - crawl-sdl
        - wintoggle-git
        - open3d
        - mingw-w64-qca-qt5
        - php80
        - telegram-desktop-dark-git
        - libsavitar
        - libcxgb3
        - libdrng
        - tack
        - emacs-monky-git
        - art-rawconverter
        - libfastjson
        - busybox-crond
        - gxe
        - lua53-lanes
        - medit3d-git
        - ros-noetic-moveit-ros-manipulation
        - gtkpod1
        - caffe-cmake-git
        - fallingtime
        - ccpnmr
        - libevdevplus
        - ros-jade-ros-base
        - deepin-anything-git
        - ima-evm-utils-git
        - tgs-to-gif-cpp-git
        - bareftp
        - mp3val
        - discretize4crf-svn
        - icd2-osso-ic-headers
        - oxefmsynth
        - bsd-games2
        - wxcode-git
        - sysexxer
        - hp-git
        - electron14
        - foomatic-filters-lprng
        - gtkd-dmd
        - fragview-git
        - subliminal-develop-git
        - naspro-bridge-it
        - libfprint-goodixtls-55x4
        - endless-sky-editor
        - libbitcoin-system
        - sane-frontends
        - emblem
        - xamarin-android-git
        - captdriver-git
        - timeline-git
        - unstickpixels
        - glasswm
        - flaa
        - simpleburn
        - kimageformats-git
        - ros-noetic-message-generation
        - gnome-loop-git
        - hexchat-javascript-git
        - openssh-aur
        - yaru
        - lib32-pango-minimal-git
        - rezonateur
        - ipset-git
        - clatexmath-git
        - openmodelica-qwt
        - zypak
        - qtzff
        - journal-gateway-gelf
        - extfstools-git
        - ros-noetic-moveit-visual-tools
        - dropbear-client
        - igel-git
        - curl-http2
        - gvm-libs
        - lush2-svn
        - prusaslicer
        - ros-noetic-roscpp-core
        - xulrunner192
        - raiblocks-cli-git
        - sublime-text-dev-imfix2
        - swaylock-git
        - lib32-cjson
        - mangohud-opengl2
        - annotator
        - wleave-git
        - cinelerra-gg
        - nixio-git
        - zerobrane-studio
        - compiz-bcop-git
        - lgogdownloader-git
        - fceux-git
        - mingw-w64-enca
        - vapor-toolbox-git
        - libgepub-git
        - liblxi-git
        - vte3-ng-emoji-terminix-zsh-notify
        - ros-indigo-openni2-camera
        - mingw-w64-qwt
        - ros-indigo-rqt-msg
        - lepton-eda-git
        - r-devel
        - qbittorrent-enhanced
        - yubikey-touch-detector
        - synergy-git
        - openmsx-catapult-git
        - infernal
        - libdai
        - time-to-matrix-git
        - audacious-plugins-gtk
        - dwarffortress-spacefox
        - libxtend
        - lib32-aom
        - le-editor-git
        - bird-babel-rtt-git
        - fntsample
        - dvtm-git
        - kde1-kpackage-git
        - ledger-mode
        - mplayer-gui-svn
        - plasma5-applets-audio-device-switcher
        - gnome-shell-extension-pop-shell-git-master_jammy
name: BUILD-46
'on':
  workflow_dispatch: ''
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-45
