jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - subtitlecomposer
        - osvr-core-git
        - k81x-fkeys
        - curlcpp
        - fcdctl
        - mplayer-gui
        - stretchy-snek-boi-git
        - weechat-git
        - thextech-supermariobrosx
        - fuse_xattrs
        - synaesthesia
        - opencv-contrib
        - lith-git
        - icu48
        - msi-keyboard-git
        - linux-linode
        - ceres-solver-git
        - ros-melodic-summit-xl-control
        - suitesparse-mkl
        - bitcoin-infinity
        - libvsq-git
        - kdstatemachineeditor
        - openfoam-esi-1712
        - screengrab-git
        - guile-gcrypt
        - marblemarcher-git
        - arangodb
        - linthesia-git
        - vocp
        - openmodelica-omedit
        - remmina-plugin-ultravnc
        - systemd-godns
        - intel-ucode-xeon-x5570
        - qccrypt
        - zsxd-git
        - android-aarch64-libtheora
        - gensio-git
        - dboxfe2
        - xorg-xrx
        - psoc-programmer-git
        - gale-git
        - ldc-git
        - ros-ardent-ament-cmake-include-directories
        - sassc-git
        - terminus-font-td1
        - anjay-git
        - keynav-enhanced
        - pmbw
        - libpthread-stubs
        - lcab
        - mingw-w64-qcustomplot-qt5
        - auto-multiple-choice
        - perfetto-git
        - wingpanel-indicator-session
        - dragonfly-reverb-git
        - lua52-lpty
        - emacs-buttercup
        - claws-mail-git
        - ros-melodic-rqt-runtime-monitor
        - domino-chain
        - pwman
        - apertium-pol
        - dsdcc
        - libcerror-git
        - openss7-modules-lts419-git
        - zopfli
        - pd-faustgen2
        - libtiff3
        - dwm-dylan-git
        - exfat-utils-debug
        - jk
        - openocd-zephyr-git
        - shc-git
        - slump
        - mingw-w64-qt6-datavis3d
        - mingw-w64-spirv-llvm-translator
        - arm-none-eabi-linaro-binutils
        - gimp-plugin-normalmap
        - day-image-git
        - libbulletml
        - liri-calculator-git
        - revbayes-mpi
        - orgtbl-query
        - pappl-git
        - shallot-git
        - k290-fnkeyctl
        - lib32-enca
        - xde-sounds
        - vtk-git
        - flif
        - fqterm-git
        - bitcoinxt-gui-git
        - stderred-git
        - keybase
        - baka
        - wmnd
        - armv7l-linux-gnueabihf-binutils
        - ncurses-full
        - psp-sdl_image
        - itex2mml
        - vserver-git
        - hivex
        - potool
        - parallel-netcdf
        - nanoboyadvance-git
        - alpine-make-oci
        - gitscover
        - tym-git
        - picoasm
        - athena-jot
        - tpl-git
        - sbm
        - st-solarized-light
        - lylibrary
        - mocicon
        - ada_spawn
        - ocaml-libocaml_plus
        - finlib
        - libgroove-git
        - davix
        - nvme-cli
        - gemmi
        - mathgl
        - libretro-nxengine-git
        - pianobooster-qt5-git
        - mingw-w64-libdvdcss
        - universal-ctags
        - ffmpeg-usdx
        - eprosima-micro-xrce-dds-client
        - mctrd-git
        - xcman
        - jack_mixer-git
        - sxemacs-git
        - qt5-gamepad-git
        - libtai
        - kyotocabinet-java
        - firetools-git
        - ps2-zlib
        - kdeplasma-runners-vbox
        - ros-jade-message-filters
        - xkb-switch-i3
        - sigrok-cli-git
        - skype-classic
        - switchboard-plug-sharing
        - qt-gtk-platform-plugin
        - deadascend
        - font-manager-git
        - zoem
        - newmoon-uxp-git
        - deadbeef-replaygain-scan-git
        - mcp2210-git
        - slock-dylan-git
        - gcc48
        - usetaglib-git
        - electron3
        - gnuplot-git
        - libpthread_workqueue-git
        - libretro-pcsx2-launcher-git
        - lib32-libpulse-nosystemd-git
        - dmenu-bbaovanc-git
        - lib32-sdl2-minimal-hg
        - dosemu2-git
        - colortail-git
        - xrt-git
        - cardboard-git
        - nginx-mod-naxsi-git
        - u9fs-git
        - soundkonverter-frameworks-git
        - ros-indigo-yocs-velocity-smoother
        - bitlbee-discord-git
        - corebird
        - font-downloader-git
        - jml
        - perfutils-git
        - lightdm-gtk-greeter-git
        - dosbox-openglide-svn
        - shards-git
        - libretro-snes9x-next-git
        - blitz
        - odroid-xu3-clinfo
        - cpp-netlib-uri-git
        - dataexplorer
        - xde-theme-circuits
        - msktutil-git
        - hex2hcd-git
        - intel-vaapi-media-driver-git
        - watchman-git
        - iperf3-git
        - xgcom-git
        - odf-converter
        - youtubedl-gui
        - yank-git
        - ros-melodic-franka-gripper
        - ikos
        - gamehub-epic-git
        - gnss-sdr-git
        - knewstuff-light
        - ktexteditor-git
        - lib32-libevdev
        - optipng-hg
        - wastesedge
        - cnijfilter-mg4200
        - osm2xmap
        - tk-togl
        - libpedsim
        - mesa-nowayland
        - passwordmanager-qt6
        - x86_64-apple-darwin-binutils
        - xavs
        - bamf-ubuntu-bzr
        - drevo-power-console-git
        - midimonster-git
        - cups-bjnp-backend
        - libnetfilter_cthelper-git
        - qlibc
        - libretro-dosbox-core
        - linux-hunter-git
        - ros-melodic-plotjuggler
        - epdfview-gtk3
        - ros-kinetic-moveit-kinematics
        - cxx-run
        - picsimlab
        - mjpg-streamer-svn
        - llmnrd-git
        - libffi-git
        - kwinft-git
        - jhbuild
        - dwayland-git
        - libucw-git
        - gwc
        - gromacs-git
        - anypaper
        - pgn-extract
        - weblog_parse
        - gnome-shell-extension-dash-to-panel
        - swcdb-lib-fs-broker
        - vorbissimple
        - x11-bell-gst-git
        - vdr-favorites
        - ros-kinetic-rosauth
        - stlink-server
        - ghdl-mcode-git
        - notcurses-git
        - swiftshader-git
        - artriculate-git
        - v86d
        - opnplug-git
        - qt-style-virtuality-git
        - arm-linux-gnueabihf-gcc-stage2
        - conkeror
        - sil-q
        - mingw-w64-proj
        - xk-git
        - vice-sdl
        - d11amp
        - termite-git
name: BUILD-35
'on':
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-34
