concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - pdsh
        - unvanquished-git
        - linux-dell-e7x70
        - waybar-hyprland-no-systemd
        - yorick-git
        - sipp-git
        - hoedown-git
        - obs-virtual-cam-filter
        - protoc-gen-grpc-web
        - yacas
        - libmacspoof
        - feedreader-decsync-git
        - ros-jade-std-srvs
        - mingw-w64-libbacktrace-git
        - tldr-cpp-git
        - cdb
        - torrential
        - php-sqlsrv
        - lemonbuddy
        - form-git
        - lib32-ladspa
        - antlr2
        - erebus
        - buteo-git
        - mingw-w64-directx-headers-cmake
        - budgie-desktop-view-git
        - sessiond
        - gtkmmorse
        - brick
        - systemd-plasmoid-git
        - ovh-ttyrec-git
        - madjack
        - ros-melodic-openni2-launch
        - multicat-git
        - papyros-files
        - ros-melodic-moveit-resources-fanuc-moveit-config
        - irssistats
        - osgqt-rrs
        - ros-lunar-class-loader
        - vivictpp
        - ros-kinetic-rqt-robot-plugins
        - zyn-fusion
        - purple-discord-git
        - java7-openjdk
        - libpurple-carbons
        - liri-qbs-shared-git
        - blender-3.0-git
        - ros-indigo-sick-tim
        - lib32-libxpm
        - xwiimote
        - rankcheck
        - edk2-git
        - tbb-boost-git
        - vmpk-svn
        - unexicon-sound-theme-git
        - lxsession-git
        - build2
        - silc-toolkit
        - miniterm
        - silc-server
        - symmy-git
        - p8-platform-gb
        - xkblayout-state
        - xfce4-remmina-plugin
        - s7
        - caffe-cuda-slim-git
        - telegram-desktop-systemqt
        - tinyows
        - ectool-samus-git
        - lumail2
        - jack-dbus
        - x2goclient-qt5
        - gopherfs
        - vapoursynth-plugin-awarpsharp2-git
        - qt6-shadertools
        - redshift-wayland-git
        - img
        - ros-jade-gazebo-plugins
        - gtk3-ubuntu
        - xorg-server-rpi
        - st-bydarch
        - hyperdex
        - fortune-mod-carnivale
        - beaver
        - fsthost
        - espanso-wayland
        - mongodb-tools-git
        - mikmod
        - brother-mfc-j985dw
        - serioussam-dancesworld
        - xorg-xfindproxy
        - vmware-component-extractor-git
        - shticker-book-rewritten
        - kde-syndication-git
        - wmtime
        - videotrans
        - gamehub
        - adapta-gtk-theme-git
        - tango-test
        - dtodo
        - visit-build
        - multiwatch
        - micromanager-git
        - autohaltd
        - qvge
        - scws
        - detex-git
        - php7-yaml
        - karbowanecwallet-git
        - feathernotes-git
        - yt-popball
        - nomad-plasma-look-and-feel-git
        - mariadb-connector-cpp-git
        - simgear-git
        - bash-completion-git
        - conky-nvidia
        - gama_tts-git
        - deepin-polkit-agent-ext-gnomekeyring-git
        - clearsilver
        - ros-indigo-media-export
        - tcllauncher
        - ffrouting
        - frobtads
        - ros-jade-diagnostic-common-diagnostics
        - mod_ruby
        - rowhammer-native-git
        - lua-cqueues-git
        - lib32-swh-plugins
        - zfs-utils-raidz-expansion-git
        - glpk-git
        - xskat
        - fleng
        - krename-frameworks
        - bdsup2subpp-git
        - mingw-w64-libthai
        - yasem-git
        - stow-git
        - libsigc++3
        - ros-noetic-vision-msgs
        - diffutils-git
        - zyre-git
        - mygtkmenui-git
        - mcalc
        - gimp-plugin-exif-browser
        - deadbeef-plugin-quicksearch-git
        - rancid
        - numworks-epsilon
        - lib32-lash
        - coreaction
        - ktimetracker-git
        - gtk-chat
        - msim
        - emerald-gtk3
        - go-beta
        - ev-git
        - pakku-git
        - wireshark-gtk2
        - ros-melodic-rotors-gazebo
        - wpimath
        - gnome-software-snapd
        - bc-gh
        - polis
        - xscreensaver-hacks
        - fortune-mod-dexterslab
        - libhandy-4-git
        - libixp-git
        - rnablueprint
        - cgal-swig-bindings
        - nodejs-bigger-heap
        - gogs-dev-git
        - libretro-neocd-git
        - ros-melodic-libfranka
        - k0s
        - infinipath-psm
        - boost-python2
        - gnome40
        - cantara
        - gjs-git
        - epson-inkjet-printer-201215w
        - ncview
        - usbdm-git
        - php54
        - gnome-health-git
        - howm
        - ros-indigo-yocs-msgs
        - vdr-plugin-rotorng
        - curl-inject-opt
        - hexchat-python2
        - gnome-shell-extension-system76-power-git
        - gnuradio-multi-rtl-git
        - ros-melodic-geographic-msgs
        - glew1.5
        - mingw-w64-ceres-solver
        - igetnonce-git
        - canu-git
        - vkmark-git
        - plasma-wallpaper-makethatpape-git
        - android-armv7a-eabi-zlib
        - cnmem
        - gnulium-git
        - nana
        - libarstream-git
        - libretro-beetle-ngp-git
        - compton-git
        - libtsm-git
        - gnome-software-snap
        - libx32-e2fsprogs
        - fsqlf-git
        - garcon-git
        - hawaii-qt5-wayland
        - sqliteman
        - shortcut-git
        - pipewire-git-unbiased
        - ddcui
        - mingw-w64-potrace
        - ros-melodic-rqt-logger-level
        - paper-git
        - c2ffi-git
        - mousemode-git
        - wyebab-git
        - public-inbox
        - passwdqc-utils
        - meataxe
        - kde-rounded-corners
        - linux-minidisc
        - linux-rpi2
        - ramses-git
        - libbus1-git
        - paycoin-qt-git
        - tidy-html5-git
        - argparser-java
        - bin32-edb-debugger
        - x265-hg
        - uwm
        - dune-vtk
        - polymc-qt5
        - guile-emacsy-git
        - lcj
        - pcsclite-toolbox
        - ros-noetic-ros-comm
        - ros-melodic-moveit
        - nwipe-git
        - libqxt
        - php74-apcu
        - hexxagon
        - simple-image-filter-git
        - links-g-directfb
        - rygel024
        - dbc_parser_cpp-git
        - aircrack-ng-git
        - bar-aint-recursive-xft-git
        - mingw-w64-cgal
        - git-spindle-git
        - pipelinedb
        - wine-discord-ipc-bridge-git
        - qxkb
name: BUILD-110
'on':
  workflow_dispatch: ''
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-109
