concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - gnome-flashback
        - myrepos-git
        - urjtag-svn
        - farbfeld-git
        - lib32-vulkan-mesa-layer
        - libdrm-proptest
        - vk-layer-flimes-gui-git
        - espressomd-git
        - ros-indigo-common-msgs
        - pure
        - gonvert
        - dupmerge
        - rttt-git
        - tsschecker-git
        - subspace
        - alibpulse
        - epson-inkjet-printer-201212j
        - nvptx-tools-git
        - ros-kinetic-octomap-server
        - smarttrafficmeter
        - aclock
        - wedder-git
        - ros-melodic-media-export
        - yabar-git
        - tsid
        - xpointerbarrier-git
        - pcp-git
        - dloopdetector-free
        - accumulate-git
        - libeno
        - repro
        - cosmosis
        - p2c
        - hdrview-git
        - lib32-keyutils-git
        - xcursor-dmz
        - lib32-oniguruma
        - cmmk_ctrl-git
        - fastrpc-git
        - psftools
        - calcmysky
        - rocr-runtime
        - twiccian
        - libretro-catsfc-git
        - guile-redis
        - youtube-dl-anime-git
        - ksuperkey
        - mingw-w64-openssl-1.1
        - amalthea-ldc2
        - vapoursynth-plugin-motionmask-git
        - xiate-git
        - btcdeb
        - cli53
        - dmenu-ekollof-git
        - libjuice
        - gtkwrite_git
        - libticalcs
        - tty-clock-borderless
        - bitcoin-abc-qt
        - lua-luaossl-git
        - cppinclude
        - brother-mfc-j870dw
        - pcb-app-git
        - maui-shell-git
        - animtext
        - clunc
        - easyexif
        - ttymidi
        - aurbrowser
        - epson-inkjet-printer-201212w
        - modprobed-db-git
        - udisks2-nosystemd
        - aprx-git
        - beagle-lib-cuda
        - x11-emoji-picker-git
        - mosquitto
        - libretro-quicknes-git
        - ros-melodic-moveit-ros-perception
        - libgphoto2-git
        - vapoursynth-plugin-cnr2-git
        - msp430-elf-gdb
        - paho-mqtt-c
        - cdu
        - lib32-tcl-ar
        - awn-extras-applets-git
        - banshee
        - flycast-2.0-git
        - peek
        - rxvt-unicode-intensityfix
        - dctrl-tools
        - php81-amqp
        - pulseaudio-airplay
        - ghc-cabal-arts
        - ripmime
        - ncmdump-git
        - backupto
        - schematic
        - hevcesbrowser
        - romog-git
        - ccminer-git
        - espanso-wayland-git
        - kodi-addon-pvr-vdr-vnsi-git
        - procenv
        - ros-lunar-controller-manager
        - check-sieve-git
        - sagecal
        - exanic
        - hackrf-git
        - stagit-gopher
        - vdr-duplicates
        - ccstudio
        - qt-sdk-raspberry-pi
        - nixnote2-git
        - tuxedo-wmi
        - gen-oath-safe-git
        - asterisk-odbc-mysql
        - spl-dkms-rc
        - onscripter
        - nickvision-money
        - mingw-w64-mpfi
        - tomato.c-git
        - aaaaxy
        - libindi-astrolink4usb-git
        - open3d-git
        - opm-material
        - apache-orc
        - keepassxc-kde-fix
        - mingw-w64-cmake-static
        - candycrisis
        - freeswitch-git
        - buffer
        - php-gearman
        - implay
        - gcolor3-git
        - gnome-shell-extension-xrdesktop-git
        - cri-o-git
        - ros-noetic-moveit-commander
        - qtgrace
        - mb-git
        - example-robot-data
        - qtfind
        - edb-debugger-git
        - dtkdeclarative-git
        - urbackup2-server
        - tome4
        - fibre-git
        - garlicoin-cli-git
        - bitlbee-git
        - spl-linux-lts-git
        - libdesqui-git
        - mingw-w64-kdsoap
        - apng-utils
        - hiprompt-gtk-git
        - nvidiabl
        - mingw-w64-dbh
        - gtklock-git
        - kcm-colorful-git
        - qvwm
        - mtrx-git
        - ros-melodic-moveit-resources-panda-description
        - qsvgstyle
        - imageburner
        - nanonote-git
        - ladish-py3-no-gui-git
        - bas
        - overmix
        - jgmenu
        - cottage-git
        - pidgin-gpg
        - umview-mod-umlwip-svn
        - osvr-vive-libre-git
        - strongswan-networkmanager
        - liblxi
        - polly-stable
        - notejot
        - flacon-git
        - epiphany-pantheon-bzr
        - ipxe-git
        - gnatcoll-xref
        - lib32-openal-minimal-git
        - gnustep-back
        - dropbox-fix
        - dooble-qt4
        - kmflcomp
        - tiptop
        - valgrind312
        - furnace
        - pcloudcc
        - linux-libre-librem
        - ros-lunar-rviz
        - liggghts-git
        - statusbar-alarm-dbus
        - postgresql15
        - ros-noetic-rgbd-launch
        - rp++
        - pgrouting-1.x
        - lalcore
        - mingw-w64-glib-networking
        - lib32-libmnl
        - j4-dmenu-desktop
        - ring-kde-git
        - why3
        - iotas
        - libqhy-git
        - drogon
        - ros-ardent-rosidl-typesupport-c
        - switchboard-plug-security-privacy-bzr
        - gqrx-git
        - tty0tty-dkms-git
        - octopus
        - xwingridselect
        - grc-rs
        - ignition-msgs-1
        - hatari-enhanced-git
        - ffmpeg-amd-full
        - lagrange-nosse41
        - rnxcmp
        - milton
        - ros-noetic-rosbridge-suite
        - libsmi
        - fez-dot
        - mhddfs
        - xastir
        - radit-essential
        - linphone-git
        - mingw-w64-libfilezilla-svn
        - recode-pybliographer
        - mate-multiload-ng-applet-gtk2-git
        - remmina-plugin-rdesktop
        - debhelper-python
        - kencfs
        - ros-indigo-gazebo-msgs
        - sass
        - valadate-git
        - papermc
        - zencash
        - libllfat
        - es-shell
        - libnxml
        - gcc49
        - davix-git
        - libasyncns-git
        - openrc-sysvinit
        - opencl-caps-viewer
        - php81-pdo_sqlsrv
        - pacredir-git
        - xtrlock-pam-fp-git
        - drbl-experimental
        - pkgupd-git
        - xorg-xmh
        - libudev-zero-git
        - nimf-libhangul-git
        - 6sv11
        - piuio-git
        - wordgrinder
        - distrho-git
name: BUILD-122
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-121
