concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - lua-gd
        - texmacs
        - kadimus-git
        - xfce-theme-greybird
        - saba-git
        - dvorak7min
        - concurrencykit
        - vapoursynth-plugin-dfttest2-cpu-git
        - firefox-gtk3
        - helm-git
        - pqiv-git
        - jsbsim-git
        - gstreamer0.10-good
        - xyzsh
        - lammps-ryzen-opencl
        - freetype2-demos
        - pyside2-git
        - xz-static-git
        - blasfeo-git
        - jfa-go
        - aquila-git
        - spl-utils-linux-git
        - newflasher
        - lib32-freeglut-git
        - stratisd-single
        - freebayes
        - qhotkey-git
        - midori-bzr
        - hcraft
        - blender-wayland-git
        - neartree
        - boblight-v4l
        - audiotools-git
        - pygplates
        - kalibrate-rtl-git
        - lib32-sdl-nobackingstore
        - guayadeque-wx3
        - proton-git
        - ros-indigo-sensor-msgs
        - kgamma-git
        - lemon-lang-git
        - zdl
        - headsetkontrol
        - irccloud
        - php70-redis
        - createrepo_c
        - ipkg
        - ttyecho-git
        - mixxx-git
        - libayemu
        - espeak-ng-git
        - mesen-s
        - openhantek
        - wmshutdown
        - qt4wvdialer
        - xcruiser
        - library-git
        - directfb2-tools-git
        - lxd-lts
        - noice-git
        - php-zstd
        - ctunnel
        - vcp
        - libfm-gtk2-git
        - ros-kinetic-laser-filters
        - network-manager-sstp-gtk4
        - augustus
        - protracker-svn
        - shtools-fortran
        - ros-lunar-rosservice
        - devilspie2
        - checkmedia
        - rocm-smi-lib
        - mmdvmhost-git
        - powerctl-git
        - plasma-systemmonitor-git
        - dovecot-xaps-plugin
        - qemacs-git
        - gimp-plugin-lqr
        - intersect.lv2-git
        - yarock-mpv
        - libkdegames-git
        - mingw-w64-qt5-quickcontrols2
        - mavlink-git
        - openkeeper-cli
        - mingw-w64-libxdiff
        - filezillasecure
        - unfuckify-git
        - gnome-cowsay-git
        - mingw-w64-gcc-fs
        - mingw-w64-qt5-script
        - cellframe-node
        - mickey
        - vapoursynth-plugin-rife-ncnn-vulkan-git
        - libne10-git
        - nginx-mod-auth-ldap-git
        - st-test
        - mingw-w64-hmat-oss
        - pythia6
        - switchboard-plug-locale
        - printer-driver-ptouch
        - chipper
        - muffin36
        - ksmoothdock-git
        - deepin-qt5integration-git
        - epson-inkjet-printer-201209j
        - clazy-git
        - openct
        - ros-kinetic-rosconsole-bridge
        - vc-dwim
        - sshuttle-git
        - highcommand-git
        - brother-mfc-j5910dw
        - cppqed-git
        - nvi-multibyte-upstream
        - lmod
        - ros-indigo-transmission-interface
        - qemu-screamer-git
        - pam-krb5
        - kubernetes-kubectl
        - xupnpd
        - attica-qt5-git
        - mumps-seq-shared
        - apertium-es-ro
        - libevdev-git
        - roboptim-core-plugin-cminpack-git
        - gtk3-optional-csd
        - gnuserv
        - linux-tomoyo
        - opensplice-dds
        - rkward-git
        - pfff-git
        - i3-exitx-systemd-git
        - getoverhere-git
        - dlib-git
        - libopenaptx
        - fmidi-git
        - lziprecover
        - hets-desktop
        - ros-jade-rospack
        - yadex
        - bbswitch-r500v
        - taarich
        - mingw-w64-qt6-shadertools-static
        - s2n-git
        - gummi-git
        - flamethrower-git
        - lumina-desktop
        - kermit-git
        - qdc
        - ros-jade-urdfdom-py
        - libtreadstone
        - pn
        - rsbag-tools-cl-stable-git
        - nextcloud-app-polls
        - ros-noetic-base-local-planner
        - pocketsphinx
        - grub-efi-arm64
        - mrmodeltest
        - t230c2-git
        - ros-noetic-joint-limits-interface
        - xosview
        - ogre-pagedgeometry-git
        - ros-kinetic-ecl-license
        - meteo-gtk
        - stressapptest-git
        - nvidia-bfs
        - f30-backgrounds
        - mingw-w64-libffi
        - wingpanel-indicator-sensors-git
        - aha-git
        - easy_spice
        - powerpc-linux-gnu-gcc-stage2
        - ultrastardxwp-git
        - img4tool-git
        - exonerate
        - qflow
        - linux-xanmod-lts419
        - lambdapad-git
        - rtfreader
        - slstatus-git
        - nrsc5-git
        - vkquake-git
        - strongswan
        - vkd3d-git
        - stormbaancoureur
        - cgproxy-git
        - ffmpegyag
        - kwin-effects-yet-another-magic-lamp-git
        - bird-babel-git
        - labwc-git
        - jemalloc-git
        - gawk-nl_langinfo
        - kcm-pointing-devices-git
        - gtox-git
        - blis
        - wxmaxima
        - vkaudiofs-git
        - pology-git
        - alpscore-git
        - socketw
        - libx32-openssl
        - tinyssh-git
        - selinux-refpolicy-git
        - prboom-plus-svn
        - okit-git
        - gmusicbrowser-rhfork-git
        - sacc
        - lineo-git
        - libusbpp-git
        - gdb-multiarch
        - ps2-sdl
        - etcher-git
        - plasma5-applets-virtual-desktop-bar-git
        - pamac-qt-aur
        - sshpass-svn
        - blender-2.8-git
        - qmlvlc-git
        - nanogui-git
        - wayland-nodocs-git
        - lite-xl
        - libp11-static
        - easytag-opensuse-ogg-patch
        - kodi-addon-game-libretro-only-git
        - mingw-w64-gcc
        - xstow
        - katago-avx2
        - couchapp-git
        - picsim
        - srec-git
        - spiffy-git
        - vdr-vdrboblight
        - ros-indigo-rplidar-ros
        - webcamoid
        - directx-headers-git
        - cwalk
        - php-xapian
        - xmr-stak-rx-git
        - pcsxr-pgxp-emu-fresh
        - materia-transparent-gtk-theme-git
        - jbofihe-git
        - plasma5-applets-netspeed
        - xob
        - akonadi-git
        - nanodbc
        - autoconf-git
        - xfce-theme-greybird-git
        - 915resolution
        - gstreamer-screenrecording-git
        - android-aarch64-ffmpeg
        - ros-melodic-topic-tools
        - garfieldpp-svn
        - linux-r500v
        - karma-dashboard
        - cdsclient
        - php7-pdo_sqlsrv
name: BUILD-2
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-1
