concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - gedit-latex
        - game-of-life
        - mpd-notification-time-git
        - ros-noetic-rosnode
        - fcl-git
        - kcgi
        - ros-jade-self-test
        - apertium-svn
        - x2goclient
        - wmtrash
        - podman-remote
        - vim-wayland
        - bitcoin-qt-addrindex-git
        - kodi-addon-visualization-starburst
        - wmcpumon
        - dnsproxy
        - syslog-notify
        - smuview-git
        - inadyn-opendns
        - ass2bdnxml
        - nginx-quic-openssl-hg
        - mingw-w64-gbafix
        - lib32-mesa-stable
        - konversation-legacy
        - gjitenkai-git
        - nbtp
        - justify-git
        - btag-git
        - sacd-decoder-bzr
        - eapol_test
        - hyperpad
        - tile-world
        - thinkcontrol-int-git
        - envchain
        - olsrd
        - usbmuxd2-git
        - zulucrypt-git
        - taskflow-git
        - compcert
        - r2-iaito-git
        - srs
        - vhba-module-lts318-ck
        - blastem
        - imv-git
        - pugl-git
        - gobject-introspection-git
        - gr-satellites
        - hget-git
        - opendkim-git
        - linak-usb-desk-control-git
        - porg
        - iftop-git
        - warmux-git
        - android-armv7a-eabi-fribidi
        - oss-nonfree
        - hal-flash
        - arename
        - pmw
        - brightnessctl-sd-git
        - iputils-git
        - nftables-fullcone
        - sealcrypto
        - qodem
        - xenia-git
        - razercfg
        - kni
        - hawaii-icon-theme-git
        - comgen
        - ffcss
        - mingw-w64-unshield
        - boxes-git
        - nvidia-fbcondecor
        - krunner-firefox-git
        - rife-ncnn-vulkan
        - lib32-tslib
        - atomizer-git
        - lf
        - colorgrab
        - gpaint
        - containernet-git
        - sqlar-fossil
        - ardhue-git
        - pict-git
        - ekg2
        - link-grammar-git
        - ros-jade-sensor-msgs
        - libdali
        - soapyuhd
        - draco
        - libvpx-1.5
        - nvidia-352-git
        - kopano-webapp-spellchecker-languagepack-italian-it-git
        - pentadactyl-git
        - ssf-git
        - ros-noetic-moveit-ros-control-interface
        - lib32-ldns
        - ros-melodic-bondpy
        - ipw2x00-firmware
        - qt5-connectivity-git
        - thefile
        - xfce4-diskperf-plugin-git
        - etlegacy
        - tgfs
        - retroshare
        - sfxr-qt
        - iir1
        - em8300-utils-hg
        - hdapsicon-git
        - sdrangel-without-sdrplay-git
        - lttoolbox
        - livewallpaper-bzr
        - altermime
        - jftui-git
        - pantheon-screencast
        - kimi-linphone-desktop-beta
        - ps2-libyaml
        - mingw-w64-librime-git
        - ros-ardent-ament-cmake-libraries
        - omniorb425
        - tumiki-fighters
        - gdm3setup-utils
        - fixsrcip
        - lib32-gnome-themes-extra
        - dxfplotter
        - ros-melodic-franka-ros
        - tint2-minimal-git
        - oselas-arm-v7a-linux-gnueabihf
        - lxc-wrapper
        - crrcsim
        - pd-flext-git
        - cheat-git
        - hostapd-noscan-dynamic-vlan
        - seahorse-caja
        - unclutter-xfixes
        - linux-drm-tip-git
        - linux-rpi2-latest-git
        - plasma5-applets-weather-widget-2-git
        - xvile
        - ucon64
        - ros-jade-rosmsg
        - seexpr1
        - getfem++
        - linux-tip-git
        - qbittorrent-nox-git
        - vkd3d-proton-mingw-git
        - libcurl-compat-minimal-git
        - gnome-calendar-no-evolution
        - cairo-infinality-lcdfilter
        - bedtools-git
        - icu63
        - infnoise
        - libad9361-iio-git
        - lambdacommon-git
        - ipmitool-git
        - xf86-video-amdgpu-git
        - opentheory
        - remmina-gtk2
        - cli-visualizer
        - ros-melodic-ps3joy
        - tango-database
        - libraptorq
        - zorba
        - drawpile-beta
        - pirate-cli
        - ros-melodic-pr2-machine
        - folding
        - lz4-static
        - irmpc
        - smw-git
        - ros-kinetic-perception
        - libraqm-git
        - qtchan
        - ghz-git
        - nginx-mainline-mod-ndk
        - fortune-mod-lost
        - raphnet-manager
        - armv7l-gcc
        - sbagen
        - libkeccak
        - dv-runtime
        - bcmatroska2-git
        - ros-lunar-rqt-logger-level
        - libad9361-git
        - polymc-qt5-git
        - android-x86-openjpeg2
        - schroedinger-cat-backgrounds
        - yad-git
        - cppfs
        - petri-foo
        - wxmedit-git
        - libart-lgpl
        - lib32-jasper
        - net-tools-git
        - i8kutils
        - ros-noetic-viso2-ros
        - peruse
        - sdl_sound-patched-hg
        - mato-icons-git
        - icinga2
        - codeviz
        - id3
        - netkit-bsd-finger
        - nyble
        - mingw-w64-coin-or-coinmp
        - ros-noetic-rqt-launch
        - fuzz-git
        - iaito-git
        - libnn-git
        - ossec-hids
        - fltrdr
        - amazon-ssm-agent
        - proxygen-git
        - gnome-calls
        - pplatex
        - nvidia-uksm-ck
        - skopeo
        - guile-sdl2
        - bspwm-rounded-corners-git
        - icc_examin
        - numix-frost-themes-git
        - l2tp-ipsec-vpn-daemon
        - ignition-math-6
        - xlibinput-calibrator
        - istyle-verilog-formatter-git
        - xfce4-terminal-devel
        - ros-indigo-robot-pose-ekf
        - libxkbcommon-git
        - mips64-linux-gnu-gdb
        - zathura-cb-git
        - swcdb-broker
        - linux-cachyos-cfs
        - avida
        - ndjbdns
        - bmdcapture
        - osd_countdown
        - forklift-git
        - nginx-devel
        - bearlibterminal-hg
        - bcpp
        - libmodule
        - coccinelle
        - ros-melodic-rosgraph
        - gfxreconstruct-git
        - decpwd
        - proxysql
        - mingw-w64-xerces-c
        - mingw-w64-qt5-winextras-static
        - qpdfview-bzr
        - dimension
        - system-config-users
        - cutycapt-qt5-git
        - pickle-beta
        - dune-uggrid
        - ros-kinetic-sound-play
        - cutemupen
        - dnsbalancer
name: BUILD-6
'on':
  workflow_dispatch: ''
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-5
