concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - openocd-nuvoton-git
        - yefm-git
        - fastjet-contrib
        - simpleitk
        - amule-adnza
        - fget
        - pacman-saltedcoffii
        - get-binary-git
        - mupen64plus-video-parallel-git
        - jfbterm-git
        - ros-kinetic-rosmake
        - simple-process-tracker
        - fife-git
        - tang
        - ocaml-psmt2-frontend
        - curaengine-git
        - retrosmart-qtcurve-theme
        - piscesde-core-git
        - mingw-w64-libelf-lfg-win32
        - tetriser-git
        - openssl-hardened
        - zabbix-server-mysql
        - lib32-smbclient
        - plasma-thunderbolt-git
        - sway-latest-git
        - ibus-kmfl
        - scourge
        - vegastrike-git
        - amarok-ffmpeg4
        - sm64ex-us-git
        - i3lock-epita
        - gnome-shell-extension-proxy-switcher-git
        - tinc-pre
        - ros-kinetic-xdot
        - freefall
        - dapper
        - route-rnd
        - ros-noetic-catkin
        - tarlz
        - ros-noetic-stereo-msgs
        - ros-indigo-ecl-lite
        - sqlrpt-git
        - yapan
        - serial-studio-git
        - finitodo
        - gtklash-git
        - purelibc-git
        - posterize
        - poldi-git
        - mkbold-mkitalic
        - rkdeveloptool-git
        - mumble-jack-git
        - tangram-web
        - right-window-git
        - hiptext
        - powerdevil-ddcutil
        - samaya-git
        - epson-inkjet-printer-201307j
        - java-15-openjdk
        - android-aarch64-qt6-quicktimeline
        - czmqpp-git
        - wine-staging-dev
        - octopi-git
        - mingw-w64-fpc
        - munin-libvirt-git
        - belle-sip
        - eris
        - heirloom-doctools-cvs
        - libkate-git
        - todo-mekb-git
        - ros-lunar-rviz-python-tutorial
        - ros-melodic-robotnik-msgs
        - kmines-git
        - ros-noetic-roslisp-repl
        - npm6
        - qucs
        - ros-melodic-soem
        - veracrypt-latest
        - mblaze
        - mingw-w64-paraview510
        - selene-media-converter
        - fuego
        - calamares-croco-git
        - qpdftools
        - emacs-scala-mode-git
        - audacity-qt-git
        - tar-parallel
        - kodi-eggz
        - graphos.app
        - hsm-git
        - cawbird-stable
        - mingw-w64-qt5-serialport-static
        - ros-ardent-rcl-lifecycle
        - apertium-dan
        - mls
        - hqx
        - thanos-xfdesktop-gtk3
        - ros-noetic-moveit-ros-visualization
        - waterfox-kde-git
        - fbpanel
        - libnpa
        - simplescreenrecorder-git
        - gtkglarea1
        - mumble-stable-minimal
        - gnome-shell-extension-blur-my-shell
        - dungeon-gdt-glk
        - gnatcoll-core
        - wch-isp
        - linux-enable-ir-emitter
        - gimp-develop-git
        - wayab-git
        - smokeqt-git
        - scalasca
        - emacs-with-editor-git
        - wofi-hg
        - ros-jade-python-qt-binding
        - rottexpr-git
        - cadabra2-git
        - vifm-git
        - dlt-viewer-git
        - ghostwriter-git
        - oculus-rift-sdk
        - lunzip
        - wxmedit
        - lief
        - nginx-mainline-addon-cache_purge
        - ocaml-json-wheel
        - eli
        - libressl-side
        - kittehplayer
        - streameye
        - proton-ge-custom-legacy-bin
        - pinephone-compass-git
        - qpmx
        - fortuner2
        - lcdf-typetools
        - ros-jade-rqt-logger-level
        - basez
        - instantwm
        - lib32-clutter
        - systemd-legacy
        - spice-protocol-git
        - faq
        - lib32-amdvlk-2021q2.5
        - lib32-llvm-rc
        - image-optimizer-git
        - mesa-stable
        - libtool-git
        - rp-bookshelf
        - kded-rotation-git
        - distcc-git
        - linvstmanager
        - tbs-linux_media-git
        - ros-indigo-rqt-runtime-monitor
        - netpipe
        - gnuradio-grnet-git
        - cal3d-svn
        - modutils
        - wwwoffle-svn
        - beagle-lib-opencl
        - mshr
        - proton
        - img2xterm
        - libmmd
        - darkbar-git
        - vitamtpmod-git
        - mingw-w64-coin-or-bcps
        - vdr-hddarchive
        - backlight-tooler
        - ros-lunar-rqt-graph
        - st-neonwave-git
        - nostromo
        - hactool
        - purple-gowhatsapp
        - nvidia-bl
        - zarafa-libical
        - lib32-ffmpeg-ex
        - ow-zlib
        - egypt
        - mingw-w64-qt6-3d
        - tracker-git
        - jacknotifier-git
        - sowing
        - x264-noffmpeg-git
        - mingw-w64-qt6-webchannel-static
        - spidermonkey-git
        - kdevelop-qmljs-git
        - libtorrent-rasterbar-1_1-git
        - vmtouch
        - citra-git
        - gtksourceview2
        - allegro5-git
        - dualsensectl
        - mp3guessenc
        - kde-thumbnailer-mp4cover
        - ibus-m17n-git
        - gawkextlib
        - gohup
        - dualscreen-mouse-utils
        - matiec-hg
        - din
        - highfive
        - latte-integrale
        - c10t-git
        - libngf
        - qsnapstore-git
        - nvidia-texture-tools
        - moc-lyrics-git
        - xfce4-weather-plugin-git
        - jxcore
        - mingw-w64-winpthreads
        - c-list
        - libdbus-minimal
        - cork-git
        - sysfex-git
        - xrestrict-git
        - beamer-theme-m-git
        - linux-aufs
        - moksha-git
        - luakit-git
        - racket-minimal
        - openmpi3-gcc7
        - valentina-hg
        - mingw-w64-openblas-lapack
        - wmitime
        - rxvt-unicode-256xresources
        - zpipe
        - ros-ardent-ament-cmake-export-include-directories
        - globe
        - vapoursynth-plugin-vcmove
        - ima-evm-utils
        - asroot
        - openldap-mod-argon2
        - the_silver_searcher_wild-git
        - wingpanel-indicator-sys-monitor-git
        - nailgun-git
        - pasang-emas
        - gtk3-nobroadway-nowayland-nocolord
        - permafrost-git
        - lazylpsolverlibs-git
        - papirus-folders-gui
        - argparser-c
        - curlcpp-git
        - gcc63-multilib
        - openni-primesense-sensor
        - gnome-shell-extension-smart-auto-move-git
        - libkgeomap-frameworks-git
        - ros-indigo-ecl-mobile-robot
        - cimplefetch
        - yagf
        - pmk-dumper-git
        - fragrep
        - lua-luaopus
        - bzflag
        - snapper-tools-git
        - htpdate
name: BUILD-18
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-17
