concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - pebbles-git
        - bake
        - lib32-zbar
        - lone_wolf-clang-git
        - pavucontrol-compact-git
        - nexuiz
        - divideandsucceed
        - wowlet-git
        - layer-shell-qt-git
        - pantheon-screenshot
        - cryptsetup-keyscript
        - ttf2cxf
        - djgpp-djcrx-beta
        - electron-ozone
        - exo-devel
        - xpilot
        - libfdk-aac-git_p
        - libmdcpp-git
        - ocaml-odn
        - pbdagcon-git
        - wattsi-git
        - rsb-spread-cpp-stable-git
        - freecad-assembly3-git
        - guile-json
        - flare-game-git
        - mingw-w64-libxslt
        - groonga-tokenizer-friso
        - sundials23
        - ros-kinetic-theora-image-transport
        - formido
        - nautilus-checksums
        - darling-dmg-git
        - libgrapheme
        - copperspice-git
        - stklos
        - nginx-unit
        - dbm
        - tty0tty
        - ros-kinetic-tf2-py
        - kraft-git
        - ros-lunar-roscpp-core
        - light-git
        - fortune-mod-americandad
        - rainbowpath
        - soapyremote
        - partitionmanager-git
        - gdigi
        - gtsam-mkl
        - qrouter-git
        - apertium-hbs
        - foliate-git
        - gkeybind
        - vdr-gamepad
        - drawtiming
        - ros-noetic-rosgraph-msgs
        - kjs-git
        - vdr-svdrpservice
        - mkcue
        - timg
        - budgie-vala-panel-appmenu-applet
        - namecoin
        - networkmanager-ssh
        - ros-jade-tf2-py
        - phylonium
        - pxlart
        - pure-glpk
        - bash4
        - git-merge-changelog-git
        - qt5pas-lazarus
        - sdbus-cpp-nosystemd-git
        - liblbxutil
        - isoimagewriter-git
        - sleepyhead
        - batman-adv
        - kdsoap-git
        - libchardet-fresh
        - gtkman
        - mingw-w64-cubeb-git
        - stl-thumb-kde
        - wlc-git
        - short-circuit-git
        - minesviiper-git
        - gsimplecal-gtk2
        - freeminer
        - sh3eb-elf-gcc
        - hpp-model
        - ros-kinetic-rqt-topic
        - ghc7.10
        - gnumeric-minimal
        - ros-jade-robot
        - valum
        - exceptions4c-git
        - sqlsmith
        - genext2fs
        - sfeed-curses-git
        - hungry-sniffer-git
        - smrender-git
        - clib
        - milena-data
        - freetz-ng-tools-git
        - opengnb
        - fast-rtps-git
        - ros-indigo-realsense-camera
        - ee-editor
        - ros-melodic-mrpt-bridge
        - matplotplusplus
        - ros-noetic-rqt-web
        - ros-lunar-rqt-plot
        - ros-noetic-message-runtime
        - dmenu-wayland-git
        - iscdcommons-git
        - wfa2-lib
        - shapeit4
        - mmv-go
        - cgo-git
        - uboot-odroid-xu3-mainline
        - djgpp-watt32
        - alwaysatty-git
        - sway-force-ssd-git
        - pcm
        - omega
        - openmm
        - tufao-git
        - xradio-sl-git
        - gshisen.app
        - pulseaudio-raop2
        - mangonel-frameworks-git
        - tunefish4
        - gnuplot-cvs-pdflib
        - vkcube-git
        - breeze-kde4-git
        - infra-arcana-git
        - flite1
        - gnudatalanguage-gdlkernel
        - kcm-ufw
        - openvas-scanner-systemd
        - rastertokpsl-git
        - annotator-git
        - zshdb-git
        - stm32flash-ex-git
        - mt7610u_wifi_sta
        - m4acut
        - lfortran
        - persosim_driver
        - gshowtv
        - adjtimex
        - pol-git
        - hhsuite
        - onigmo
        - loki
        - lua-unix
        - tinytriangle
        - mingw-w64-coin-or-alps
        - exiso-git
        - libdisasm
        - libusbp-1
        - mediainfo-gui-git
        - elements-project
        - android-armv7a-eabi-libogg
        - morseall
        - ps2-aalib
        - wingpanel-indicator-cpufreq-git
        - lalsimulation
        - jmtpfs-git
        - noweb
        - pure-gl
        - grub-customizer5-git
        - anttweakbar
        - fprint_demo-git
        - mate-sensors-applet-gtk2
        - wput
        - hippoplayer-git
        - lib32-boost-libs
        - nyx-qt
        - openface
        - libkar-git
        - omi
        - execline-git
        - ldid-git
        - pulseaudio-nosystemd-git
        - mtftar-git
        - emacs-ace-window-git
        - php56
        - gphotofs
        - gtk3-aqd
        - pc6001vx-git
        - objconv
        - radeon-profile-git
        - xtris
        - brickd
        - entt
        - calcoo
        - jsq
        - lilo-git
        - libx32-glibc
        - profetch
        - gvim-gc-responsiveness-patch
        - spek-x-git
        - enroute-git
        - schemes
        - osm2pgsql
        - xine-ui-hg
        - krunner-vscodeprojects-git
        - ladspa-bs2b
        - silentjack-git
        - pep8-asm-git
        - gasmeter
        - libpamac-nosnap
        - grumpy
        - md5
        - ros-indigo-ecl-console
        - soundtouch-svn
        - textseeker
        - ptoc
        - yip-git
        - methane
        - ros-kinetic-rqt-py-common
        - r8s
        - kio-mtp-git
        - tint3-cpp-git
        - gitid
        - gnome-twitch-player-backend-gstreamer-clutter-git
        - mutter-catalyst
        - hzs_reminder
        - lmdb-git
        - gnucash-xbt-minimal
        - pcspkr-git
        - magid
        - scid-vs-pc-svn
        - cups-bjnp
        - bspwmbar-git
        - freemcboot
        - kodi-devel-pvr-mediaportal-tvserver
        - kiwix-cli-git
        - doh-curl-git
        - pegasus-fe-git
        - madbomber
        - wangle
        - profanity-omemo-git
        - torita
        - libcxgb4
        - nasc-git
        - ros-indigo-roscpp
        - denise-git
        - ros-indigo-pano-core
        - linux-neo_chen
        - ros-ardent-intra-process-demo
        - jaromail
        - gnome-blog
        - ccut-git
        - bitcoin-gui-git
        - geoclue
        - compton-garnetius-git
        - nextcloud-systemd-cron
        - xde-desktop
        - psi-plus-webkit-qt5-git
name: BUILD-105
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-104
