concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - tigervnc-git
        - yorick-yao-git
        - devtools32
        - kerberosio-machinery
        - qdigidoc
        - dave-gnukem-git
        - livsdiary
        - kactivities-stats-git
        - php-ds
        - ros-noetic-openslam-gmapping
        - qtcreator-gitqlient-plugin-git
        - pixymon-git
        - jamin
        - linux-zen-letsnote
        - daphne-svn
        - crunch-test
        - neoleo
        - slade
        - smile
        - gmonitor-git
        - matchbox-common
        - qbittorrent-qt4
        - simdock
        - gtk-3-fortran-git
        - bgs-git
        - archc-git
        - ros-melodic-rqt-robot-plugins
        - libva-vdpau-driver-chromium
        - vitali64-dwm-git
        - qtcreator-plugin-layoutsupport-git
        - wsjtx-git
        - alphaplot-git
        - tabby-fossil
        - trojan-qt5
        - iconthemebrowser
        - neatmail
        - gr-sdrplay3-git
        - universalindentgui-svn
        - ufc2-hpc-git
        - i2pd-git
        - bareftp-legacy
        - cegui
        - ros-indigo-roscreate
        - vapoursynth-plugin-tnlmeans-git
        - pidgin-opensteamworks-svn
        - pnginfo-git
        - libdeflate-git
        - lightdm-gtk-greeter-bzr
        - streamripper-gui
        - grive-git
        - audacity-3.0.2
        - gtklock-powerbar-module
        - asciiworld-git
        - givemelyrics
        - vlc-plugin-fluidsynth-git
        - libtorrent-pyro-git
        - vte3-git
        - gitlab-gitaly-git
        - kim-api-models
        - kvantum-qt5
        - acme-client-git
        - qt5-pmp-base
        - lib32-liblrdf
        - exif
        - ccd2cue
        - rakarrack
        - surf-ashin-git
        - libebur128-git
        - rms-pics
        - xinputd-git
        - gdc
        - trio
        - mingw-w64-pteros-git
        - gtk-sharp-2-git
        - lcms
        - ros-ardent-demo-nodes-cpp-native
        - bibletime-git
        - bt-tracker-add
        - ros-melodic-std-msgs
        - c-intercal
        - ros-kinetic-roslz4
        - key-tools
        - gtk-engine-equinox
        - kirigami-git
        - busybox-coreutils
        - android-openssl-armeabi-v7a
        - openmp-rc
        - nginx-vts-exporter
        - libfap
        - ir-lv2
        - libtasn1-git
        - lib32-libxnvctrl-470xx
        - linux-hardened-git
        - newsd
        - libudfread-git
        - hogc
        - gr-soapy-git
        - mercurial-hg
        - pantheon-settings-daemon-git
        - qtgain
        - coin-or-lemon
        - tmux-xdg-git
        - mingw-w64-schroedinger
        - lib32-fcitx
        - sm64ex-nightly-60fps-git
        - lbrycrd
        - rsync-git
        - ros-noetic-rosmaster
        - advcpmv
        - voxelands
        - libcli
        - efl-fresh
        - deadbeef-plugin-vu-meter-git
        - ros-jade-rosboost-cfg
        - john-opencl
        - audacity3
        - dnaa
        - switchboard-plug-mouse-touchpad-bzr
        - xfce4-panel-profiles
        - cpp-io2d-git
        - qt5-gsettings
        - rtpmidid-git
        - neper
        - libretro-genesis-plus-gx-wide-git
        - ros-jade-urdf
        - todo-stupid-git
        - ros-noetic-rospack
        - xsecurelock
        - libasr-snapshot
        - cups-nosystemd-minimal-git
        - hush-lightwalletd
        - deepin-topbar-git
        - linux-renoir-backlight
        - eternity-engine
        - gnome-settings-daemon-volume-step-patch
        - mednafen-server
        - create-verthash-datafile
        - diskscan
        - texi2latex
        - xabber-websocket
        - gchooser
        - snapd-glib-libsoup2
        - nwcc
        - radharc
        - 3dstool
        - spiel-git
        - lib32-dconf
        - flatpak-git
        - icecast-kh
        - gmrun-xdg
        - opmsg-git
        - shotcut
        - fist
        - syncmaildir
        - chestnut
        - firestorm-git
        - cxbqn
        - pcc-libs-cvs
        - xfce4-screensaver-git
        - booth
        - libxtrxdsp-git
        - nwg-launchers
        - webkit2gtk-hvml
        - binkd
        - hoichess
        - gppcscconnectionplugin
        - mingw-w64-x264-bootstrap
        - mingw-w64-qt5-tools
        - lib32-gobject-introspection
        - at-spi2-core-minimal-git
        - similarity-tester
        - decoder
        - bluecurve-classic-metacity-theme
        - libchimara-git
        - helloworld
        - cdspeed
        - gemini
        - artefetcher-qt5
        - bgrep-git
        - kimap2
        - ros-kinetic-shape-msgs
        - ros-kinetic-rqt-runtime-monitor
        - pf_ring-kernel-git
        - lean-display-manager
        - terraform-lsp-git
        - kxstitch
        - sioyek-git
        - unix2dos-asm
        - libbitcoin-client
        - ioport-git
        - lib32-cmocka
        - yolo-mark-git
        - rxvt-unicode-patched-with-scrolling
        - ignite-git
        - amazon-ecr-credential-helper
        - php73-pdo_sqlsrv
        - gnome-shell-extension-mediaplayer-git
        - libmysofa
        - libretro-db-tools
        - linux-wallpaperengine-git
        - libcron
        - libnetfilter_log-git
        - opentimelineio0.14
        - android-armv7a-eabi-libvpx
        - vala-language-server
        - pam_mysql-git
        - android-aarch64-lame
        - ros-indigo-librviz-tutorial
        - php54-xdebug
        - ros-noetic-rotors-description
        - diamond-aligner
        - bamf-ubuntu
        - kmod-git
        - linux-cacule-rdb-rt
        - mangonel-git
        - rand
        - linux-clear-lts2019
        - libjcat
        - venom
        - liborcania
        - kcharselect-git
        - ros-indigo-kobuki-random-walker
        - mastercard-pkcs11-tools
        - man-pages-de-git
        - avisynth-plugin-fillborders-git
        - x88000
        - gimp2.10-plugin-lqr
        - qtask-git
        - dynconf
        - mackerel-agent
        - bitlbee-mastodon-git
        - gnome-text-editor-git
        - ossim-svn
        - gxml
        - libsha2
        - lib32-gegl
        - schismtracker-hg
        - macaon-data
        - lightdm-webengine-greeter-git
        - comodo-modules
        - mbelib
        - libmsym-git
        - lottie-qml
        - prboom-svn
        - getdata
        - mongoose
        - lib32-cracklib
        - xlnt-git
        - kodi-devel-pvr-stalker
        - lchat
        - nano-git
        - cicada-git
        - tclsoap
        - polkit-consolekit
        - spice-up-git
        - alsa-utils-nosystemd-minimal-git
name: BUILD-144
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-143
