concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - poppler-qt-lcd
        - dduper-git
        - mash
        - makepp
        - font-downloader
        - fastd-git
        - qv2ray-plugin-trojan-go-git
        - liblwan-git
        - wxdfast
        - ros-indigo-turtlebot-description
        - fccf
        - glabels-qt-git
        - maya-calendar
        - gimp-plugin-toy
        - nginx-mainline-mod-brotli
        - wofi
        - mavlink-router-git
        - linux-macbook-pro
        - lmao
        - match
        - slashem
        - pt1_drv-dkms-hg
        - jamovi-git
        - syscoin-git
        - nyan-lang-git
        - purple-rocketchat
        - apple-darwin-qt5-translations
        - gracegtk
        - libdatachannel
        - xqproxy
        - redfang
        - freetype2-ultimate5
        - flam3
        - ibm-tpm2-tss-git
        - hpgl
        - hercules-analysis-git
        - duff-git
        - ros-indigo-tf-conversions
        - libm2k-git
        - gpmp2-git
        - mauikit-accounts-git
        - indiprop-git
        - minmad-git
        - deadbeef-mpris2-plugin-git
        - rifiuti2
        - ros-noetic-panda-moveit-config
        - any-proxy-git
        - ros-indigo-libuvc
        - showmethekey-git
        - katago-cpu
        - xournalpp-micro
        - ros-melodic-ecl-errors
        - intelbacklight-git
        - wownero-git
        - lib32-muparser
        - fdns-git
        - libcfg+
        - fwbuilder-qt4
        - kodi-addon-pvr-mythtv
        - zonefs-tools
        - shark-ml-git
        - libx32-xz
        - corebird-git
        - vte3-nohang
        - android-x86-libjpeg-turbo
        - ros-melodic-dynamic-reconfigure
        - dbus-x11
        - aerotools-git
        - ros-melodic-moveit-ros-move-group
        - ictree
        - qore
        - libunwind-git
        - lib32-libglvnd12
        - faust-git
        - kdeconnect-bluetooth
        - sysbro
        - swappy
        - orage-git
        - samplecat-git
        - gerris
        - ros-melodic-image-transport
        - ros-jade-diagnostic-aggregator
        - http-parser
        - php-ibm_db2
        - mingw-w64-tcl
        - waynergy
        - vapoursynth-plugin-eedi3cl-git
        - ffmpeg-libfdk_aac
        - chm-thumbnailer
        - crt-calibrator
        - linux-bfq-dev
        - klish
        - linux-radxa-rkbsp5-git
        - domruler-git
        - libressl-latest
        - moksha-modules-extra-git
        - bcm2835
        - xpilot-atoms-git
        - libfreeaptx
        - libretro-mupen64plus-git
        - basix
        - nginx-mainline-mod-modsecurity-git
        - wcc-git
        - racon
        - ethminer-git
        - xfce4-multiload-ng-plugin-git
        - libcommunist
        - ts-player
        - vapoursynth-plugin-eedi3-git
        - spirv-llvm-translator-stable
        - linux-aarch64-raspberrypi-4.14
        - sdlume
        - gnocl-canvas
        - nheqminer-aayanl-cuda-git
        - piscesde-fishui-git
        - git-credential-gnome-keyring
        - ros-jade-roscpp-traits
        - bviplus
        - dng
        - icat-git
        - php-pdlib
        - doukutsu
        - libvisca
        - mesen-git
        - gctwimax-modacom-u3500
        - purple-mm-sms-git
        - sol2
        - ccid-morpho
        - mkbootfs
        - serious-engine-git
        - sidfactory2-git
        - zasm
        - mauikit-imagetools-git
        - emulationstation-fcamod-git
        - podofo-lua52
        - ros-melodic-rtabmap
        - cuberok
        - onednn-git
        - ros-noetic-cmake-modules
        - openscenegraph-openmw-git
        - cerberus
        - cups-noudev
        - httpry
        - koko
        - connman-gtk-git
        - fontopia
        - libkexiv2-frameworks-git
        - libdigidocpp
        - kreport-git
        - gnucash-dev
        - qt5-webview-git
        - vtflib-git
        - kodi-addon-inputstream-adaptive-git
        - ros-kinetic-moveit-ros
        - completion
        - ros-indigo-filters
        - hyperd-git
        - diary
        - easymp3gain-gtk2
        - ros-indigo-genlisp
        - archmaker
        - xdarkterror.lv2-git
        - gnome-shell-extension-one-thing-git
        - disper
        - muttvcardsearch
        - elogind-git
        - kops
        - clam-git
        - ropium-git
        - osgqt-qt4
        - v8-r
        - libpng15
        - deepin-network-utils-git
        - sandy-git
        - kcm-polkit-kde-git
        - epos
        - zifd-git
        - armhf-musl
        - libimobiledevice-git
        - guile-sdl
        - sdl2trs
        - peerunity
        - ocaml-pipebang
        - vartypes-qt5-git
        - jd-gtk3
        - czmq
        - qt5-pmp-webengine
        - xfce4-volumed-pulse
        - hippo-canvas
        - ros-indigo-rosconsole-bridge
        - libpng12-minimal
        - ros-kinetic-mavlink
        - kpack
        - xbyak
        - chez-scheme-racket-git
        - sums
        - lib32-libgdiplus
        - plumed
        - multistrap
        - winestreamproxy-git
        - cbm
        - psensor
        - iortcw-git
        - telepathy-kde-accounts-kcm-git
        - modmanager
        - gr-op25-git
        - postgis-git
        - linux-threadripper
        - bubbros
        - vapoursynth-lib-vsfilterscript-git
        - tepl3
        - mpfr-git
        - ympd
        - go-ethereum-git
        - ros-noetic-rqt-gui-py
        - mingw-w64-qt6-imageformats
        - smatch
        - zeek
        - stint-git
        - s3fs-c-git
        - swayout
        - kudus
        - uzem-git
        - digikam-frameworks-git
        - cliqr
        - osirisedit
        - picosat
        - sooperlooper-headless
        - libstardustxr-git
        - pidgin-pushbullet-git
        - nullidentdmod-git
        - homegear-intertechno
        - libclc-stable
        - vlc-debug
        - go-go2go-git
        - docker-git
        - sdbusplus-git
        - dune-fem
        - amrnb
        - libretro-openlara-git
        - ros-kinetic-moveit-ros-move-group
        - dict-freedict-fra-deu
        - mklittlefs
        - nextcloud-app-markdown
        - mingw-w64-coin-or-csdp
        - nyan-lang
        - elementary-xfce-icons
        - mympd-git
        - bitlbee-bzr
        - bit-babbler
        - capnet-assist
        - plasma-camera-git
        - as31
        - lollypop
        - dao-git
        - coremod-git
name: BUILD-138
'on':
  workflow_dispatch: ''
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-137
