concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - linux-simple-bcachefs-git
        - nginx-mainline-addon-pagespeed
        - blogc
        - rofi-lbonn-wayland-only-git
        - gri
        - isync-utf8-mailboxes
        - rnnoise-git
        - mingw-w64-intel-tbb
        - openpht
        - scmxx
        - st-nu1ll1nux
        - kopano-webapp-mattermost
        - kea-git
        - buoh
        - nightmode-git
        - emacs-git
        - sfml1.6
        - kvirc-nokde
        - liquidfun
        - rapidxml
        - ros-lunar-message-generation
        - avs2yuv-git
        - linvst
        - openmp-nvptx
        - ros-lunar-cpp-common
        - mkclean
        - ckb-next
        - socketpipe-git
        - gauche-fastcgi
        - gsequencer
        - cbatticon-git
        - qcef
        - mivisionx
        - lib32-colord-git
        - qotpnitro
        - blender-new-object-types-git
        - ros-indigo-rosbag-migration-rule
        - ume-git
        - cirkuit-kf5-git
        - iguanair-lirc
        - bart
        - sasm
        - qqc2-breeze-style-git
        - moonjit
        - megazeux
        - oggfwd
        - castools-git
        - abseil-cpp
        - holo-ssh-keys
        - rox-filer-git
        - cutemarked-git
        - mate-power-manager-1.15-gtk3
        - ros-melodic-turtlebot3-simulations
        - ros-indigo-rosauth
        - lua-libmagic
        - slrn
        - polkit-kde-kcmodules-frameworks
        - mingw-w64-pagmo2
        - mate-user-guide-dev
        - mingw-w64-speex
        - breeze-hacked-cursor-theme-git
        - libindi-astromechfoc
        - qmlkonsole
        - nginx-minimal
        - kpatch
        - gtkwrite
        - dos2unix-git
        - paxctl
        - im-chooser
        - fastp
        - afl_llvm_mode
        - orca-git
        - dmenu-demonkingswarn-git
        - freessm-git
        - magma
        - caja-gtk2
        - lanes
        - ddate
        - epix
        - ros-melodic-message-runtime
        - bsdwhois-drizztbsd-git
        - libaacplus
        - sent
        - souffle
        - xeventbind-git
        - kealib
        - treeleaves-git
        - cparser-git
        - avr-gcc-85
        - liquidshell-git
        - tarquin
        - ros-lunar-message-runtime
        - zabbix-agent-2.2
        - batmon
        - glportal
        - master-key
        - pidgin-jabber-pseudo-invisibility
        - gnome-shell-extension-hibernate-git
        - lib32-esound
        - libcompizconfig-git
        - wmload
        - moc-https
        - csuper-cli
        - zrandr
        - epson-inkjet-printer-201112w
        - powershell-beta
        - pamac-all
        - libpod
        - ptii-git
        - xmrig-nvidia
        - icecream-git
        - gf_backup_tool-git
        - bin2c-yama
        - linux-zen-515lts
        - xmltooling
        - mingw-w64-jemalloc
        - ros-indigo-joint-state-publisher
        - mingw-w64-spdlog
        - apidb-mariadb
        - miopen-hip
        - udt
        - networkmanager-ssh-git
        - arpc
        - miniflux
        - flatpak-lol
        - lxpanel-gtk3
        - revelation
        - parchives
        - paho-mqtt-cpp-git
        - ossec-agent
        - openskyscraper-git
        - qt5-location-git
        - hawaii-wallpapers
        - devpath-git
        - morgenrot-git
        - ff-git
        - mod-arpeggiator-lv2-git
        - blockbar-git
        - ethq
        - sudx
        - ros-melodic-rqt-bag
        - mokutil-git
        - ros-melodic-smach-ros
        - nginx-mainline-boringssl
        - llvm4+clang+wasm
        - espeak-test
        - meshoptimizer
        - ktexteditorpreviewplugin
        - postsrsd-git
        - ahven
        - uniutils
        - nginx-mainline-waf
        - cpufrequtils
        - libuecc
        - spacenav-plus
        - lib32-egl-wayland-git
        - kicad-step-git
        - openttd-git
        - posixovl
        - hashlink
        - mingw-w64-rapidyaml
        - vcl-git
        - php-datastructures-git
        - open-phd-guiding-svn
        - gtkballs
        - k-izer
        - mingw-w64-libsoundio
        - fvwm-themes
        - freecad
        - podsleuth
        - ros-lunar-rqt-service-caller
        - mesa-noglvnd
        - lrpt-pp-git
        - asmail
        - vlan
        - mednaffe-gtk2
        - orocos-utilmm
        - rdrview-git
        - dfl-power
        - kwin-effects-yet-another-magic-lamp
        - json-c-git
        - face-analysis-sdk
        - lib32-rtmpdump
        - libeap-modacom-u3500
        - ros-lunar-rqt-reconfigure
        - conserver
        - linux-xps13
        - db5.2
        - libkdumpfile-git
        - libconcord
        - cppglob
        - timblserver
        - cpu-x
        - vapoursynth-plugin-mvtools-git
        - tclmpi-git
        - dbus-broker-git
        - vdr-radio
        - gr-framework-git
        - tg
        - frozen-git
        - libconfig-git
        - qamqp-git
        - openrw
        - ros-noetic-ros
        - udefrag
        - ms-tpm-20-ref-git
        - kismet-ng
        - wdt-git
        - mpd-server-minimal
        - bullet-git
        - eclim-fixed-git
        - bubblemail-gnome-shell-git
        - eolie
        - recdvb-b25
        - husky-tosser-git
        - ddd-ftn
        - hpmor-man-pages-git
        - spl-linux-vfio
        - swhkd-musl-git
        - dwm-jadecell-git
        - beegfs-meta
        - inform7-ide
        - lmarbles
        - xf86-video-chips
        - kalarmcal-git
        - paperback-cli-git
        - xxdiff-git
        - osmo-sip-connector-git
        - pure-gtk
        - ros-lunar-rospy
        - nginx-mainline-addon-dav-ext
        - m17client-git
        - demolito-git
        - ros-kinetic-unique-id
        - vo-aacenc_p
        - jack-git
        - xeus2
        - netns-exec
        - wyrmsun
        - duma-git
        - picom-rounded-corners
        - midisnoop-git
        - discord-screenaudio
        - ncl
        - tracebox-git
        - libemu-git
        - glslang-svn
        - ocs-url
        - networkmanager-sstp
        - libdxfrw-git
        - ros-kinetic-roscpp-tutorials
        - ros-noetic-hls-lfcd-lds-driver
        - osmctools
        - hdf-eos2
        - enhanced-ctorrent
        - kopano-core-git
name: BUILD-93
'on':
  workflow_dispatch: null
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-92
