concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - dnspod-sr-git
        - librime-git
        - ros-indigo-roslisp
        - telegrand-git
        - usd19
        - lib32-glib1
        - choqok-git
        - pristine-tar
        - adapta-gtk-theme-3.94
        - engrampa-dev
        - simplest-studio
        - wbxml2
        - opentrack
        - haunt
        - utox
        - vatsim-manager
        - liboqs-git
        - nymea-networkmanager-git
        - nvidia-390xx-settings
        - gfxreconstruct
        - c3c-git
        - st-n1
        - fruit-di
        - glib1
        - slibtool
        - pyconfigure
        - wiiload
        - wxsqlite3-2.8
        - spdynu-git
        - lasercalc
        - libzookeeper
        - x3270-git
        - libadalang
        - openelp
        - clblast-git
        - vlock-original
        - asix-module
        - gr-ieee802-15-4
        - libjson-rpc-cpp
        - mpz-qt6
        - ros-kinetic-moveit-resources
        - kcolorpicker-git
        - unity
        - libime-jyutping
        - advancedgenieeditor-git
        - nemo-dropbox
        - cista
        - collectd-graphite-git
        - blink1-git
        - gamehub-git
        - mystiq
        - scalapack-static
        - mathmod-cvs
        - libgrid-svn
        - qwebapp
        - ros-indigo-libnabo
        - verifpal
        - gazebo-sitl-git
        - gimp-plugin-bimp
        - libunique3
        - kid3-git
        - ctwm-git
        - gnome-shell-git
        - mpv_inhibit_gnome
        - gimp-plugin-refocusit
        - libaesrand-git
        - apertium-en-gl
        - kiwix-desktop-git
        - raven-qt
        - ros-indigo-rospack
        - xi-gtk-git
        - spacefm-git
        - lib32-sdl-nokbgrab
        - libtrace
        - lbreakouthd
        - texi2mdoc
        - neosiji
        - evjl
        - virt-viewer-git
        - lddgraph-git
        - mkg3a
        - madrigal-git
        - netvirt-agent-beta-git
        - pridecat-git
        - radium7
        - libsignal-protocol-c
        - libgnunetchat
        - places-git
        - flashmq-git
        - catch-git
        - sjasmplus-z00m128
        - qemu-loongarch64
        - scrcpy-git
        - gf
        - silentarmy
        - dhcpcd8
        - ros-noetic-rqt-runtime-monitor
        - obs-image-reaction
        - libvirt-vnc
        - u2f-hidraw-policy
        - string-theory
        - pamac-snap-flatpak
        - kate-git
        - transmission-cli-git
        - xxdiff
        - wayst-x11-git
        - lib32-util-linux-nosystemd-minimal-git
        - linux-amd-mainline-git
        - gnokii-git
        - lf-git
        - rundaemon
        - gimp-cce-git
        - brasero-git
        - vlc-decklink
        - moony-lv2-git
        - ntrig_calib-bzr
        - texmaster
        - tomahawk
        - libiqa-git
        - midori-no-zeitgeist
        - nestopia
        - citadel
        - vmn-git
        - fifth-git
        - tunefish4-git
        - zrythm
        - g4music
        - gnome-bluetooth-pantheon
        - proctal-git
        - quickfm-git
        - camllight
        - afb-helpers-git
        - libretro-parallel-git
        - svt-vp9-git
        - openmodelica-git
        - milagro-crypto-c
        - ng-jackspa
        - kscd-git
        - script-communicator-git
        - gibsonclient-git
        - periscope-git
        - kplot
        - nvidia-vulkan
        - pipo
        - java-berkeleydb
        - logapp
        - somanyjaggedshards
        - casparcg-server
        - quark-git
        - libasl
        - ua608d
        - goslice
        - plasma5-applets-system-panel
        - lib32-libkate
        - fluidsynth-git
        - xlog
        - amide
        - httpfs2
        - mingw-w64-librsvg
        - kex-git
        - linux-asus-aura
        - z3-git
        - qt5-color-widgets
        - lib32-icu51
        - desq-utils-lock
        - tir
        - kvkbd
        - rdma-core-git
        - roboschool-git
        - espresso-logic
        - snb-git
        - hfsprogs
        - nupack4
        - postgresql-lts
        - plasma-mobile
        - skywire-git
        - ncpong-git
        - obsetlayout
        - ocaml-pa_bench
        - gaviewer
        - ros-indigo-effort-controllers
        - linux-test-project-git
        - libsysstat-git
        - tvheadend-satip-server-git
        - gromacs-4.6-complete
        - nbfc-linux-git
        - web-greeter
        - khal-git
        - ht-editor
        - stargate
        - irctl
        - pamtester
        - rolisteam
        - ros-noetic-moveit-ros-robot-interaction
        - kamule
        - shapelib-tools
        - washdc-git
        - geos-git
        - core
        - signal-cli
        - lib32-libmm-glib
        - midibench-git
        - coreutils-git
        - supercell-git
        - qt5-multimedia-git
        - cmdfs
        - sequoia-redactor
        - msigd-git
        - wayland-log-reader
        - gsettings-desktop-schemas-ubuntu
        - restorecond
        - klibc
        - bmkdep
        - bayeselo
        - mmixware
        - cpeditor
        - nogil-python
        - byacc-noconflict
        - cppcheck-git
        - ros-melodic-bondcpp
        - maui-calendar-git
        - lib32-gperftools
        - gnome-mime-data
        - libvhdi-git
        - jrtplib
        - pcal
        - abeep-git
        - kdesudo-frameworks-bzr
        - faustfilters-git
        - psp-libtremor
        - kbbi-qt
        - lua51-compat53
        - fimpp-git
        - postgresql-9.4
        - pldebugger-git
        - fitsh
        - php56-mailparse
        - darkbar
        - ros-jade-collada-urdf
        - ros-lunar-collada-parser
        - gvfs-git
        - kopano-webapp-google2fa-git
        - mediaelch-git
        - net-snmp-lmsensors
        - libdx
        - linux-uksm-ck
        - dqlite
        - sqlfuse-git
        - sdr-j-dabreceiver
        - thin-provisioning-tools-git
        - i3lock-fancier-git
        - libcmaes
        - log4cxx
        - vera++
        - mingw-w64-nlopt
        - iptables-git
name: BUILD-99
'on':
  workflow_dispatch: ''
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-98
