concurrency:
  cancel-in-progress: true
  group: ${{ github.head_ref }}
jobs:
  buildPKGBUILD:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: makepkg
      name: Build PKGBUILD
      uses: ./build_pkgbuild_action
      with:
        aurDeps: true
        pkgdir: ./pkgs/${{ matrix.PKGBUILDs }}
    - name: Zip directory
      run: cd ./pkgs && zip ../${{ matrix.PKGBUILDs }}.zip ./${{ matrix.PKGBUILDs
        }}/pkg/* -r
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ matrix.PKGBUILDs }}.zip
        tag: packages
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - mdliveview
        - minbif
        - ssss
        - mingw-w64-libsamplerate
        - lib32-jemalloc
        - cfssl
        - corrade-git
        - ros-melodic-rqt-reconfigure
        - vapoursynth-plugin-vsrawsource-git
        - simavr-git
        - igmpproxy-git
        - toml11
        - ubus-git
        - ros-jade-tf2-sensor-msgs
        - llvm70
        - dashcore-git
        - linux-bld
        - kdewebkit-git
        - hasklock
        - gforth
        - grpc-cpp-git
        - neatrefer-git
        - seatd-git
        - evopop-gtk-theme
        - php-xmlrpc
        - redasm-beta
        - pica-pica-client
        - libiio
        - ros-melodic-tf2-eigen
        - kubectl
        - hunspell-smj
        - b43-tools
        - thtk-git
        - libceed
        - zegrapher
        - grabber
        - kdebase-workspace-consolekit
        - dino-notification-sounds-git
        - snmp++
        - spatialite-gui-devel
        - osmose
        - rc
        - vdeplug_agno-git
        - tinmop-git
        - fchat-pidgin-git
        - treefrog-framework-git
        - waybar-eyes
        - tree-sitter-git
        - kochmorse-git
        - searchmonkey
        - fortune-mod-scrubs
        - skype1ico-git
        - startactive
        - ros-indigo-navfn
        - normaliz
        - nautilus-legacy
        - selinux-dbus-config
        - arcpp
        - qgis-1.6
        - gp2c
        - selene-git
        - ros-kinetic-genlisp
        - qcsxcad-git
        - json2tsv
        - kodi-addon-vfs-rar-git
        - cross-mingw-w64-gdb
        - tracy
        - megacmd
        - zenity-gtk4-git
        - lib32-libgcrypt15-minimal-git
        - spectator-rest-client-git
        - ros-noetic-pybind11-catkin
        - physlock
        - clipgrab
        - chinese-calendar-git
        - etterna-git
        - qt5-base-headless
        - nanopolish
        - bandwidthd
        - pe-parse-git
        - openvpn-rrf
        - harminv-git
        - frameworkintegration-git
        - wingpanel-standalone-git
        - orbit2
        - libx11-nokeyboardgrab
        - dpdk
        - libindi-gphoto
        - sntop
        - rofi-json-menu-git
        - libtcod-git
        - zram-generator
        - gn-m76
        - opensmtpd-extras-git
        - obs-source-copy
        - gpac-git
        - zxtext2p
        - gitea-git
        - vulkan-caps-viewer-wayland
        - vte3-kinetic
        - wesnoth-1.2
        - daa2iso
        - pam-ssh-git
        - moksha-module-diskio-git
        - ros-kinetic-rosbuild
        - bloonix-plugins-apache
        - pgadmin3-git
        - grcompiler-git
        - ffmpeg-git
        - kopano-webapp-smime-git
        - dumphive
        - libumlib0
        - sherpa-git
        - mbmp-git
        - ros-noetic-ivcon
        - bsa-analytics
        - bracmat-git
        - mingw-w64-gst-editing-services
        - kicad-symbols
        - ros-indigo-roswtf
        - phoebetria
        - hplip-lite
        - brave-git
        - smplayer-skins-git
        - pgl
        - t50
        - ros-ardent-ament-cmake-gmock
        - tagsistant-svn
        - fbpanel-git
        - clangd-svn
        - magic-git
        - csvtools-git
        - atheme
        - volunode-git
        - netsed-opt
        - mingw-w64-seafile-shared
        - kdenlive-applications15.08-git
        - adwmod-theme-git
        - ros-melodic-octovis
        - cadabra2
        - thunar-gtk3-git
        - katago-opencl
        - souffle-git
        - pmdk-git
        - wingpanel-indicator-power-git
        - badabib
        - gvolwheel
        - zint
        - muse-fresh
        - ros-kinetic-moveit-ros-perception
        - ros-kinetic-cmake-modules
        - grass
        - xapian-glib
        - libosmo-sccp-git
        - bacula5-client
        - mingw-w64-angleproject
        - kdesu-git
        - ros-noetic-moveit-resources-fanuc-description
        - interception-caps2esc-4modifiers-git
        - hop-devel
        - libvc
        - ffmpeg-tmblock-git
        - multipath-tools-git
        - scscp
        - winbar-git
        - libopenrazer
        - direwolf
        - ros-indigo-rocon-interactions
        - nimf-stable
        - ros-indigo-hector-imu-tools
        - hpanel
        - gimp-plugin-webp
        - scrotty
        - ffmpeg-semifull-git
        - dosbox-x-sdl2-git
        - mgard-git
        - scamper
        - chdkptp-svn
        - go-luks-suspend-git
        - virt-viewer
        - iop-token
        - icu56
        - mingw-w64-agrum
        - quickerd
        - boinc-client-next-git
        - plasma5-applets-mpdnowplaying
        - fstar
        - cave9
        - tlog
        - carl-git
        - cgterm-git
        - noson-app-git
        - piscesys-screenlocker-git
        - ros-melodic-hardware-interface
        - kooha-git
        - pxz
        - authenticator
        - interception-uswitch
        - remake
        - xmille
        - fancon
        - spatialite-tools
        - ntkmonitor
        - mingw-w64-libpaper
        - ladybird-git
        - ritchie-git
        - latco
        - pgtcl
        - libcerf-git
        - linux-clear-lts2021
        - scap-security-guide-git
        - spglib-git
        - cemu
        - i2util
        - qt5-wayland-bugfixport-git
        - koku-xinput-wine-git
        - crazydiskinfo-git
        - geogram
        - nvidia-lts310-ck
        - extrae
        - tint3
        - ppcoin-qt
        - gnome-python
        - nginx-mainline-mod-auth_spnego
        - ninjam-server
        - bindtointerface
        - hatari2
        - gala-stable
        - pnmixer-gtk2
        - xapps-git
        - c-rbtree
        - consel
        - qpanda-2-git
        - ros-jade-depth-image-proc
        - plata-gtk-theme-git
        - lib32-hdf5
        - mstflint-inband
        - charge-log
        - openlibrary
        - ibutils
        - artanis-git
        - microperl
        - pulseaudio-hsphfpd
        - riscv64-unknown-elf-picolibc
        - passmate
        - hddtemp-git
        - audacious-imms-git
        - docker-credential-pass
        - libappindicator-ubuntu
        - video-downloader
        - linux-cacule-testing
        - xfwm4-move-monitor
        - garcon-devel
        - networkmanager-vpnc-gtk2
        - busysteg-git
        - libticonv
name: BUILD-38
'on':
  workflow_dispatch: ''
  workflow_run:
    types:
    - completed
    workflows:
    - BUILD-37
